- android/build.gradle
- android/gradle.properties
Potentially fixes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/4
> [RNKC-035] - downgrade kotlin and androidx.core versions

- android/src/main/java/com/reactnativekeyboardcontroller/TranslateDeferringInsetsAnimationCallback.kt
Using `println` statements is not commonly adopted practice, so in this MR I'm converting it to `Log`.
> [RNKC-039] - println -> Log

- README.md
- gifs have the same height
- demonstration section doesn't have an overlap with installation
- no big words so layout on npm should be the same as on GitHub
- removed empty line in installation bash script
> [RNKC-040] - fix layout in readme

- ios/KeyboardControllerModule.m
> fix: old import styles

- .github/PULL_REQUEST_TEMPLATE.md
Now every PR will have structure and will shed a light on some important aspects.
> [RNKC-047] - PR template

- src/animated.tsx
Exported `KeyboardContext`.
It may be needed in future, if user wants to have a custom control of soft input mode (for example return it to default state in stack navigator if screen becomes visible/invisible).
- added `export` for `KeyboardContext` variable;
Tested manually. Developers have an access to this variable and can import it in their code.
> [RNKC-048] - export KeyboardContext

- .github/workflows/verify-js.yml
Added unit tests stage in CI which running unit tests.
To keep better code quality we need to assure that unit tests are not broken (even if right now this project has 0 real unit tests - I will add them later).
- added new stage in CI for running unit tests;
Tested on CI.
> [RNKC-044] - unit tests CI

- README.md
- package.json
> chore: release 1.0.0-beta.0

- example/ios/Podfile.lock
- package.json
First stable version `1.0.0` 😊
> chore: release 1.0.0

- example/ios/Podfile.lock
- package.json
> chore: release 1.0.1

- .github/workflows/build-android.yml
Added android builds to pipeline.
It's important to check, that app is compiling correctly and without errors.
- added android & example app builds;
Will be tested in this PR.
> [RNKC-044] - android build

- example/ios/Podfile.lock
- package.json
> chore: release 1.1.0

- .github/workflows/build-ios-fabric.yml
- FabricExample/ios/Podfile.lock
CI builds for iOS (Fabric).
To assure new changes are not breaking builds.
- added a script/scenario for building FabricExample app on iOS;
- update Podfile.lock;
Tested using GitHub actions.
> [RNKC-059] - iOS Fabric builds

- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/patches/react-native-gesture-handler+2.5.0.patch
- FabricExample/yarn.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.2.0

- .github/PULL_REQUEST_TEMPLATE.md
Added emojis for PR template.
To make it more readable I decided to add emojis for PR templates to headers. In my opinion it looks better visually and it's easier to read sections.
- updated PR template;
Tested in this PR 😅
> [RNKC-066] - PR template emojis

- docs/package.json
- docs/yarn.lock
Update docusaurus to latest version.
Just a regular update of dependencies to keep project up-to-date.
- use `docusaurus` 2.1.0;
Tested locally.
> [RNKC-068] - docusaurus 2.1.0

- src/animated.tsx
- src/context.ts
- src/hooks.ts
- src/index.ts
- src/internal.ts
- src/native.ts
- src/replicas.ts
- src/types.ts
Reworked file structure of `src` directory.
Right now it's a little bit messy. Every file may have several responsibilities and in future it will be hard to support. So the purpose of this PR is to make every file more single responsible. 
- added `context`, `hooks`, `types` and `internal` files;
- re-export members from `context`, `hooks`, `types` files;
Tested manually on iPhone 11 and Pixel 3.
> [RNKC-075] - new src (JS/TS) file structure

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.3.0

- docs/docs/recipes/platform-differences.md
Correct link to a new hook (fixed deploy CI job).
I want to see a new version of docs under `next` tag 🙂 
- correct link to a new hook;
Tested locally via `yarn build` command.
> fix: docs build

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.4.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.4.1

- .github/workflows/verify-android.yml
- android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardControllerModule.kt
- android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
- android/src/fabric/java/com/reactnativekeyboardcontroller/StatusBarManagerCompatModule.kt
- android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
- android/src/main/java/com/reactnativekeyboardcontroller/KeyboardControllerPackage.kt
- android/src/main/java/com/reactnativekeyboardcontroller/extensions/Float.kt
- android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardControllerViewManagerImpl.kt
- android/src/main/java/com/reactnativekeyboardcontroller/modules/KeyboardControllerModuleImpl.kt
- android/src/main/java/com/reactnativekeyboardcontroller/modules/StatusBarManagerCompatModuleImpl.kt
- android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
- android/src/paper/java/com/reactnativekeyboardcontroller/KeyboardControllerModule.kt
- android/src/paper/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
- android/src/paper/java/com/reactnativekeyboardcontroller/StatusBarManagerCompatModule.kt
Reorganized files structure of Android source code.
I started to work on interactive keyboard on Android and quickly realised that current File Structure is not good enough. That's why I decided to group files by categories (i. e. `views`/`managers`/`modules`/etc.).
- reorganized file structure of android source code;
- added `extensions` folder;
- updated `ktlint` version;
|Before|After|
|-------|----|
|<img width="291" alt="image" src="https://user-images.githubusercontent.com/22820318/208062935-6a94f0de-de10-45f3-ae8a-f34f40ae6da4.png">|<img width="292" alt="image" src="https://user-images.githubusercontent.com/22820318/208063093-775d65f4-1772-4b87-b0ba-2eac1bc32890.png">|
> refactor: reorganize fs structure for android

- FabricExample/ios/KeyboardControllerFabricExample.xcodeproj/project.pbxproj
- FabricExample/ios/KeyboardControllerFabricExample.xcworkspace/contents.xcworkspacedata
- FabricExample/ios/Podfile.lock
- example/ios/KeyboardControllerExample.xcodeproj/project.pbxproj
- example/ios/KeyboardControllerExample.xcworkspace/contents.xcworkspacedata
- example/ios/Podfile.lock
- package.json
Release v1.4.2
Started to use new CocoaPod version, that's why some files were also changed in example apps.
> chore: release 1.4.2

- docs/package.json
- docs/yarn.lock
Updated docusaurus to latest version.
Just a regular maintenance :)
- updated docusaurus to `2.3.1`;
Tested locally.
> docs: use latest docusaurus (2.3.1)

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.4.3

- docs/docs/api/keyboard-controller-view.md
- docs/docs/api/keyboard-provider.md
- docs/versioned_docs/version-1.4.0/api/keyboard-controller-view.md
- docs/versioned_docs/version-1.4.0/api/keyboard-provider.md
Added documentation about new `navigationBarTranslucent` property.
Need to document all changes and all new functionality 😎 
- added infor about new prop for `KeyboardControllerView` and `KeyboardProvider`;
Tested manually on localhost:3000
> docs: add info about `navigationBarTranslucent` property

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.4.4

- docs/docs/api/hooks/use-keyboard-handler/index.mdx
- docs/docs/api/keyboard-gesture-area.md
- docs/docs/guides/interactive-keyboard.md
- docs/src/components/HomepageFeatures/index.tsx
- docs/src/css/custom.css
Updated docs to include new iteration on interactive keyboard guide.
Initially I wanted to release only support for Android. However recently plans were changed and I decided to add support for iOS too. That was the main factor why I've reworked documentation 🙂 
- fixed typos;
- added few words about iOS platform;
- tweaked a little bit colors;
Tested on localhost:3000
> docs: interactive keyboard (next iteration)

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.5.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.5.1

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.5.2

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release v1.5.3

- docs/docs/guides/first-animation.md
> Fix spelling in first-animation.md

- docs/versioned_docs/version-1.0.0/guides/first-animation.md
- docs/versioned_docs/version-1.4.0/guides/first-animation.md
- docs/versioned_docs/version-1.5.0/guides/first-animation.md
Fixed spells in documentation.
To produce better quality of documentation 🙃 
- changed `ShareValues` -> `SharedValues`;
Tested on localhost:3000
> docs: fix spells

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release v1.5.4

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release v1.5.5

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.5.6

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.5.7

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.5.8

- .github/workflows/verify-docs.yml
- docs/docusaurus.config.js
- docs/src/components/HomepageFeatures/index.tsx
Added an ability to preview PRs.
Sometimes it's easier to review PR when it's deployed (check how it looks on mobile devices etc.).
The list below is important to take into consideration when PR will be merged:
- don't remove pr-review directory in main deployment pipeline
- remove preview when PR was closed/merged (.nojekyl?)
- be sure that there is no race condition, when PR is getting merged
- added new job which deploys preview to github pages;
- conditionally change `baseUrl` to handle case for previews;
Tested using GitHub actions.
> docs: PR preview

- .github/workflows/size-diff.yml
- .github/workflows/verify-android.yml
- android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
- android/src/fabric/java/com/reactnativekeyboardcontroller/StatusBarManagerCompatModule.kt
- android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
- android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationController.kt
- android/src/main/java/com/reactnativekeyboardcontroller/events/KeyboardTransitionEvent.kt
- android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardControllerViewManagerImpl.kt
- android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardGestureAreaViewManagerImpl.kt
- android/src/main/java/com/reactnativekeyboardcontroller/modules/KeyboardControllerModuleImpl.kt
- android/src/main/java/com/reactnativekeyboardcontroller/modules/StatusBarManagerCompatModuleImpl.kt
- android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
- android/src/main/java/com/reactnativekeyboardcontroller/views/KeyboardGestureAreaReactViewGroup.kt
- android/src/paper/java/com/reactnativekeyboardcontroller/KeyboardControllerModule.kt
- android/src/paper/java/com/reactnativekeyboardcontroller/StatusBarManagerCompatModule.kt
Added `detekt` for static analysis of `kotlin` code.
I wasn't satisfied with the quality of the `kotlin` code, because sometimes I wrote big lines of the code, sometimes I wrote code-smells and didn't know about it. With the usage of `detekt` all these issues will be detected and reported.
I've added CI job to constantly run it whenever `kotlin` files were changed.
Potentially `detekt` could be added as a `gradle` plugin and we could run it during the build, but I decided to integrate it as a separate tool, since all other linters/tools integrated in CI as separate tools (so just decided to keep a consistency).
- resolved all issues reported by `detekt`;
Tested manually on Pixel 7 Pro (android) + verified that CI can be passed.
> ci: added `detekt` for kotlin static analysis

- docs/docs/recipes/platform-differences.md
- docs/versioned_docs/version-1.0.0/recipes/platform-differences.md
- docs/versioned_docs/version-1.4.0/recipes/platform-differences.md
- docs/versioned_docs/version-1.5.0/recipes/platform-differences.md
Added a reference why setting `adjustResize` is needed
Just to add more information why it's needed. For experienced developers it may be obvious, but for people who just started to use this functionality - it's crucial to understand it 🙂 
- added a comment why setting `adjustResize` is needed;
Tested via preview 🙂
> docs: added a reference why setting `adjustResize` is needed

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.6.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.6.1

- docs/blog/2023-09-08-components/index.mdx
Added a new blogpost about upcoming `1.7.0` release.
To keep people aware about new changes and about roadmap of the library.
- added blogpost for `1.7.0` release
Tested on localhost:3000 🙂
> docs: blogpost 1.7.0

- FabricExample/ios/Podfile.lock
- FabricExample/src/screens/Examples/KeyboardAvoidingView/index.tsx
- example/ios/Podfile.lock
- example/src/screens/Examples/KeyboardAvoidingView/index.tsx
- package.json
> chore: release 1.7.0

- README.md
Added info about `KeyboardAvoidingView` in README.
There is only blogpost and API page describing `KeyboardAvoidingView`. For new users it may be difficult to understand that such component is available out-the-box from the package, so I've decided to add an info into "Key Features" in README.
- added info about `KeyboardAvoidingView` in README;
Tested via github preview.
> docs: update key features

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.8.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.9.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.9.1

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.9.2

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.9.3

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.9.4

- docs/blog/2023-12-26-release-1-10/index.mdx
Blogpost for new upcoming release.
To make people aware about new features plus improve SEO search.
- added new blogpost;
> docs: blogpost 1.10.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.10.0

- .github/workflows/label-sponsors.yml
Adds "sponsor" badge to issues if user is my sponsor.
To attract more attention to issues that needs to be prioritized.
- added `label-sponsors.yml`;
There is no way to test it, but I hope it'll work 🤞
> feat: automatically add sponsors label to issues

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.10.1

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.10.2

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release v1.10.3

- docs/docs/api/hooks/input/use-focused-input-handler.md
- docs/versioned_docs/version-1.10.0/api/hooks/input/use-focused-input-handler.md
- e2e/kit/004-masked-input.e2e.ts
- example/package.json
- example/patches/react-native-text-input-mask+3.1.5.patch
- example/src/screens/Examples/Main/constants.ts
- example/src/screens/Examples/TextInputMask/index.tsx
- example/yarn.lock
- ios/observers/TextChangeObserver.swift
Fixed a problem when `onTextChange` is not fired on iOS if `TextInput` from `react-native-text-input-mask`.
The issue and solution is described [here](https://github.com/RedMadRobot/input-mask-ios?tab=readme-ov-file#uitextfieldtextdidchange-notification-and-target-action-editingchanged-event).
However, if I add delegate with `onEditingChanged` method, then I can not assign my listener to this callback (the delegate can not be casted to my own type and I can not import existing class from another module because RNKC is not depending on another module). And adding an optional dependency to Podfile makes installation process harder and I don't see explicit benefits of making the approach more complex.
For now I'll go with this solution (also I opened a PR to `react-native-text-input-mask`, …
> fix: `useFocusedInputHandler` and `onChangeText` handler ignores an input from `react-native-text-input-mask` on iOS

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.10.4

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.10.5

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.10.6

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.11.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.11.1

- docs/docs/api/components/keyboard-aware-scroll-view.mdx
- docs/docs/api/hooks/keyboard/use-keyboard-handler/index.mdx
- docs/docusaurus.config.js
- docs/package.json
- docs/versioned_docs/version-1.10.0/api/components/keyboard-aware-scroll-view.mdx
- docs/versioned_docs/version-1.10.0/api/hooks/keyboard/use-keyboard-handler/index.mdx
- docs/versioned_docs/version-1.11.0/api/components/keyboard-aware-scroll-view.mdx
- docs/versioned_docs/version-1.11.0/api/hooks/keyboard/use-keyboard-handler/index.mdx
- docs/versioned_docs/version-1.4.0/api/hooks/use-keyboard-handler/index.mdx
- docs/versioned_docs/version-1.5.0/api/hooks/use-keyboard-handler/index.mdx
- docs/versioned_docs/version-1.6.0/api/hooks/use-keyboard-handler/index.mdx
- docs/versioned_docs/version-1.7.0/api/hooks/use-keyboard-handler/index.mdx
- docs/versioned_docs/version-1.8.0/api/hooks/keyboard/use-keyboard-handler/index.mdx
- docs/versioned_docs/version-1.9.0/api/hooks/keyboard/use-keyboard-handler/index.mdx
- docs/yarn.lock
Updated docs engine to docusaurus 3.0
Docusaurus brings new features, so it's important to stay up-to-date. Moreover previous versions support can be dropped in a near future.
- update all deps;
- use docusaurus 3.1
Tested via CI.
> docs: docusaurus 3.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.11.2

- FabricExample/ios/KeyboardControllerFabricExample.xcodeproj/project.pbxproj
- FabricExample/ios/Podfile.lock
- example/ios/KeyboardControllerExample.xcodeproj/project.pbxproj
- example/ios/Podfile.lock
- package.json
> chore: release 1.11.3

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.11.4

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.11.5

- tea.yaml
> chore: tea integration

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.11.6

- docs/docs/api/components/keyboard-aware-scroll-view.mdx
- docs/versioned_docs/version-1.10.0/api/components/keyboard-aware-scroll-view.mdx
- docs/versioned_docs/version-1.11.0/api/components/keyboard-aware-scroll-view.mdx
Added an info about integration `KeyboardAwareScrollView` with virtualized lists.
I constantly see that people are searching for:
So decided to add this information into the guide.
- added an information about `KeyboardAwareScrollView` + `FlatList` integration;
Tested on localhost:3000 and preview.
> docs: `KeyboardAwareScrollView` + `FlatList`

- docs/docusaurus.config.js
Added API link to footer.
To make API reference page in quick access 🙂 
- Added API link to footer;
On localhost and preview.
> docs: add API to footer (Docs column)

- cspell.json
- docs/blog/2024-05-13-release-1-12/index.md
- docs/blog/2024-05-13-release-1-12/index.mdx
Added blogpost for upcoming release.
To highlight all upcoming changes on a single page 👀 
- wrote blogpost for 1.12.0;
> docs: blogpost for 1.12.0

- docs/versioned_docs/version-1.10.0/guides/compatibility.md
- docs/versioned_docs/version-1.11.0/guides/compatibility.md
- docs/versioned_docs/version-1.12.0/guides/compatibility.md
- docs/versioned_docs/version-1.5.0/guides/compatibility.md
- docs/versioned_docs/version-1.6.0/guides/compatibility.md
- docs/versioned_docs/version-1.7.0/guides/compatibility.md
- docs/versioned_docs/version-1.8.0/guides/compatibility.md
- docs/versioned_docs/version-1.9.0/guides/compatibility.md
Updated compatibility table.
For Fabric we sometimes did changes before actually started to support this architecture in package.
So I updated a table reflecting 100% compatible versions.
- update compatibility tables;
Tested `localhost:3000`.
> docs: update compatibility table

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.12.1

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.12.2

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.12.3

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.12.4

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.12.5

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release v1.12.6

- .github/workflows/publish.yml
Added "verified" badge near to package version to npm registry.
Such badge gives more confidence to users that such package is official etc.
Than more confidence in package quality people have, than more they like the pacakge and in the end it will gain the popularity of the pacakge 👀 
- add `provenance` flag to `npm publish` command;
Can be tested only when new release gets published 🤷‍♂️ 
Hopefully we'll get this badge 👀
> ci: add verified badge to npm

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.12.7

- docs/docs/api/components/keyboard-toolbar/index.mdx
- docs/versioned_docs/version-1.11.0/api/components/keyboard-toolbar/index.mdx
- docs/versioned_docs/version-1.12.0/api/components/keyboard-toolbar/index.mdx
Added theme type to KeyboardToolbar theme example
> docs: add KeyboardToolBarTheme type example

- docs/docusaurus.config.js
- package.json
Added `interactive` keyword to `package.json` and website keywords.
"Interactive" keyboard is a big part of this library so let's make sure it can be properly indexed 😎 
- mention `interactive` keyword;
There is no way to test it without a deploy 😅
> docs: added `interactive` keyword to improve SEO search

- docs/package.json
- docs/yarn.lock
Update site engine (`docusaurus`) to `3.4.0` version.
New version brings more optimization, better SEO search etc.
So the update is higly desirable 😊 
- regenerate `yarn.lock` file;
- update docusaurus and corresponding dependencies in  `package.json`;
Tested on localhost + e2e (pixel perfect) tests.
> docs: use docusaurus 3.4.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.13.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.13.1

- ios/observers/KeyboardMovementObserver.swift
Reduce code duplication and repeated code.
Reduce code duplication and repeated code by:
- moving creation of `AnyHashable` into separate function;
- working with notification data in separate method.
- created `metaDataFromNotification` and started to use this function;
- created `getEventParams` and started to use this function;
Tested via e2e tests.
> refactor: reduce code duplication in `KeyboardMovementObserver`

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.13.2

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.13.3

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.13.4

- docs/docs/api/components/keyboard-aware-scroll-view.mdx
- src/components/KeyboardAwareScrollView/index.tsx
Added an ability to render custom `ScrollView` for `KeyboardAwareScrollView`.
Sometimes it may be necessary to render custom `ScrollView` instead of default implementation from RN (for example from RNGH). Before it wasn't possible, but this PR adds this ability.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/593
- added `ScrollViewComponent` property for `KeyboardAwareScrollView` component;
Tested manually on Pixel 3a (API 33, emulator).
|Before|After|
|<video src="https://github.com/user-attachments/assets/1fd4be4e-2669-4fec-bc9b-5a12fc9cf1f6">|<video src="https://github.com/user-attachments/assets/4b5ca359-dc2d-4433-9914-97d218cfeef3">|
> fix: `KeyboardAwareScrollView` + gesture-handler

- docs/docs/api/components/keyboard-aware-scroll-view.mdx
- docs/versioned_docs/version-1.10.0/api/components/keyboard-aware-scroll-view.mdx
- docs/versioned_docs/version-1.11.0/api/components/keyboard-aware-scroll-view.mdx
- docs/versioned_docs/version-1.12.0/api/components/keyboard-aware-scroll-view.mdx
- docs/versioned_docs/version-1.13.0/api/components/keyboard-aware-scroll-view.mdx
Added link + change style to match props name style.
To keep everything consistent 😊 
- add hyperlink to prop inheritance;
- change style to match props name style.
Tested on `localhost:3000`.
> docs: unify prop inheritance style for `KeyboardAwareScrollView` component

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.14.0

- CODE_OF_CONDUCT.md
Automatically added `CODE_OF_CONDUCT` contained prettier violations. In this PR I'm fixing it.
To keep CI green again 😊 
- formatted `CODE_OF_CONDUCT.MD`;
Tested on CI.
> chore: format `CODE_OF_CONDUCT`

- .github/workflows/verify-cpp.yml
Fixed cpplint.
Latest `cpplint` requires newer python version.
- bump `python` to `3.13` for `cpplint` job
Tested on CI.
> fix: cpplint

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.14.1

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.14.2

- docs/docs/api/over-keyboard-view/index.mdx
- docs/versioned_docs/version-1.14.0/api/over-keyboard-view/index.mdx
Added meaningful description for `OverKeyboardView` page for preview.
`<Lottie` as description doesn't make any sense to developers + makes SEO search worse.
- changed preview of `OverKeyboardView` page;
|Before|After|
|<img width="1018" alt="image" src="https://github.com/user-attachments/assets/504db84c-df75-47db-9940-d894b6fe2ea6">|<img width="1023" alt="image" src="https://github.com/user-attachments/assets/ad8df4aa-2e59-405c-9588-7c33cc28c837">|
> docs: meaningful page description for `OverKeyboardView`

- docs/docs/faq.md
- docs/docs/installation.mdx
- docs/docs/troubleshooting.md
- docs/versioned_docs/version-1.14.0/faq.md
- docs/versioned_docs/version-1.14.0/installation.mdx
- docs/versioned_docs/version-1.14.0/troubleshooting.md
Added FAQ section.
Installation guide contains too many tips/info badges. I decided to keep info in installation guide only which related to the installation process. For other important topics I created a separate page (FAQ) where I'll place the questions and answers.
- added `FAQ` section;
- removed one `info` badge and move it to FAQ page.
|Before|After|
|<img width="990" alt="image" src="https://github.com/user-attachments/assets/38fea8d9-9dc7-4aef-825b-606d623b6fdc">|<img width="987" alt="image" src="https://github.com/user-attachments/assets/b2282655-3d26-4b60-824f-703f14443351">|
> docs: FAQ section

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.14.3

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.14.4

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.14.5

- docs/blog/2024-12-12-release-1-15/index.mdx
- docs/blog/2024-12-31-release-1-15/index.mdx
Added a blogpost about new `1.15` release.
To keep people aware about upcoming changes.
- added blogpost about new version;
Tested locally on `localhost:3000`.
> docs: blogpost 1.15

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.15.0

- docs/src/components/HomepageFeatures/index.tsx
Fixed typo 🙃 
Thanks to @hirbod who spotted that issue 🙌 
- Reach -> Rich
Tested manually on `localhost:3000`.
> docs: reach -> rich

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.15.1

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.15.2

- ios/observers/KeyboardMovementObserver.swift
Fixed newly discovered warnings.
In paper example I've seen even more warnings and fixed them as well 🙂 initially these warning were added in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/727
Follow up for https://github.com/kirillzyusko/react-native-keyboard-controller/pull/766
- fixed 2 warnings in `KeyboardMovementObserver`;
Tested manually.
> refactor: remove other warnings

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.16.0

- docs/blog/2025-01-27-release-1-16/index.mdx
Added missing wording for blogpost.
To make sure people can read the blogpost without questions 🙂 
- added missing words;
Via preview.
> docs: fix blogpost wording

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.16.2

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.16.3

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.16.4

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.16.5

- docs/docs/api/components/keyboard-avoiding-view.mdx
- docs/versioned_docs/version-1.16.0/api/components/keyboard-avoiding-view.mdx
Added description for all behavior modes.
Since we have 4 modes (instead of 3) I decided that it would be better to document a difference somehow, so I updated docs.
- explain when and which mode to use;
Tested manually via preview.
> docs: `KeyboardAvoidingView` behavior explanations

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.16.6

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.16.7

- FabricExample/src/navigation/ExamplesStack/index.tsx
- example/src/navigation/ExamplesStack/index.tsx
Fixed a typo in the title of the example repository.
This change corrects a minor typographical error in the repository example repo to maintain consistency and readability.
- Fixed typo in the example repository.
- No changes.  
- No changes.  
Manually reviewed the updated title to ensure correctness. No functional code changes were made, so no additional testing was required.
N/A
> fix example title

- docs/src/css/custom.css
Follow up for https://github.com/kirillzyusko/react-native-keyboard-controller/pull/890
> fix: css in `keyboardVerticalOffset`

- docs/src/pages/index.tsx
Added Rainbow app to "Trusted by" section.
To keep list of apps up-to-date.
- added "Rainbow" app to "Trusted by" section.
> docs: add Rainbow to "Trusted by" section

- docs/blog/2025-04-09-release-1-17/index.mdx
- docs/docs/guides/compatibility.md
- docs/docs/guides/components-overview.mdx
- docs/versioned_docs/version-1.17.0/guides/compatibility.md
- docs/versioned_docs/version-1.17.0/guides/components-overview.mdx
Added components overview page.
I want to make docuemntatino easier to understand. Going through the all API pages can be difficult for mental perception, so I thought it would be beneficial to have a documentation page that compares all components with each other to make a choice easier.
This is the first PR in series of re-writing documentation.
- added components overview guide;
Tested manually via preview.
> docs: components overview

- docs/docs/api/keyboard-gesture-area.md
- docs/versioned_docs/version-1.16.0/api/keyboard-gesture-area.md
- docs/versioned_docs/version-1.17.0/api/keyboard-gesture-area.md
Improved documentation for `KeyboardGestureArea`.
The good documentation is key aspect of each software development process. I realised, that `KeyboardGestureArea` page was created a long time ago, so in this PR I decided to improve that page.
Inspired by https://github.com/kirillzyusko/react-native-keyboard-controller/issues/937#issuecomment-2864237920
- add reference to example app;
- mention that `KeyboardGestureArea` works for iOS starting from 1.16+;
- add `keyboardDismissMode="interactive"` to `ScrollView` as it's needed for iOS anyway;
- update description for `textInputNativeID`;
> docs: improvements for `KeyboardGestureArea` view

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.17.3

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.17.4

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.17.5

- cspell.json
- docs/src/pages/index.tsx
Added more apps to "Trusted by" section
Planned check for who uses the lib to reflect the actual state.
- update Trusted by content
> docs: more trusted apps

- FabricExample/ios/Podfile.lock
- FabricExample/yarn.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.18.0

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.18.1

- docs/docs/api/views/keyboard-extender/index.mdx
- docs/versioned_docs/version-1.18.0/api/views/keyboard-extender/index.mdx
Fix example code for `KeyboardExtender` view.
The old code was more like a scratch API. That code:
- wasn't working on Android
- wasn't handling different keyboard appearance;
So I thought to replace it with a more comprehensive code. I took the code from example app and removed testId, images, etc. to simplify and remove external dependencies as much as I can. The new code better reflects how to use the new API, which edge cases to cover etc.
- update code example for `KeyboardExtender`;
> docs: update `KeyboardExtender` code sample

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.18.2

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.18.6

- FabricExample/ios/Podfile.lock
- example/ios/Podfile.lock
- package.json
> chore: release 1.19.0
