kirillzyusko/react-native-keyboard-controller

example/ios/Podfile.lock
example/src/screens/Examples/AwareScrollView/index.tsx
example/src/screens/Examples/KeyboardAnimation/index.tsx
ios/KeyboardControllerModule.swift

As per react-native [docs](https://reactnative.dev/docs/native-modules-ios#sending-events-to-javascript) we shouldn't dispatch events without registered listeners.
Also in example app I removed an unused listener in Keyboard animation and changed function `randomColor` to produce always 6 symbols color (before it could produce 5 symbols color and RN was throwing errors, though I haven't seen them because I ignored all warnings 🤦‍♂️ )
Closes: https://github.com/kirillzyusko/react-native-keyboard-controller/issues/8

issue #8: no listeners registered warnings

---

android/src/main/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
src/animated.tsx
src/native.ts

Fixes: https://github.com/kirillzyusko/react-native-keyboard-controller/issues/14
This PR adds new prop called `statusBarTranslucent`
The problem was in the fact that in `ApplyWindowInsetsListener` we always add constant paddings. In case of translucent status bar we should apply 0 paddings. Prop `statusBarTranslucent` now control this aspect.

issue #14: translucent status bar on android

---

ios/KeyboardControllerViewManager.swift

Reorganised subscription mechanism as per [this](https://stackoverflow.com/a/8203326) SO answer.
The problem with old code was in the fact, that if subview is getting removed, then we unsubscribe from keyboard events. It's incorrect behaviour, since we should unsubscribe from events **only** in case if view **itself** is getting removed (not subviews, not sibling views).
It was reproducible using code below:
```jsx
// App.tsx
import 'react-native-gesture-handler';
import * as React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { KeyboardProvider } from 'react-native-keyboard-controller';
import {
SafeAreaProvider,
initialWindowMetrics,
} from 'react-native-safe-area-context';
import { PortalProvider } from '@gorhom/portal';
import RootStack from …
```

[RNKC-041] - correct subscribe/unsubscribe mechanism for keyboard events on iOS

---

src/animated.tsx

- used `useRef` for keeping Animated reference (`useMemo` is more expensive way, and `useRef` more commonly adopted)
- wrapped style in `useMemo` to avoid unnecessary re-renders

[RNKC-042] - use more standart way of working with animated values in functional component (useRef rather than useMemo)

---

.github/workflows/verify-kotlin.yml
android/build.gradle
android/gradle.properties
android/src/main/java/com/reactnativekeyboardcontroller/EdgeToEdgeReactViewGroup.kt

Added `./gradlew lint` to inspect known issues and fix them.
To maintain high code quality it's necessary to use various linters. In this PR I'm adding support for `gradle/android lint` which will inspect most common mistakes/issues in kotlin code and will prevent merging PR which are breaking rules.
- added ling for Android;
Tested on CI.

[RNKC-044] - android lint

---

.github/workflows/publish.yml

Automatic publishing to `npm` registry when release on GitHub occurs.
It's a little bit difficult to perform two actions (publishing to npm and preparing a release on GitHub). So publishing can be automated and in this PR I added this GitHub action.
- added `publish.yml` file;
Will be tested later in `alpha.4` release.

[RNKC-044] - autopublishing

---

ios/KeyboardControllerViewManager.swift

Fixed compilation in XCode.
In https://github.com/kirillzyusko/react-native-keyboard-controller/pull/23/files#diff-8975efc71b3a8dead3c983b4720088d0f3348a58f07f9e8ed278ea90165486a4 I've renamed param from reactTag to viewTag, but forgot to change it in other places of library 🤦 
- `reactTag` -> `viewTag` in events creation;
Tested manually in example app.

[RNKC-050] - fixed iOS compilation issues

---

example/ios/Podfile.lock

Synchronize `Podfile.lock` after changing library version.
It should happen in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/34 but I forgot to update it 🤦‍♂️ 
- update Podfile.lock file in example app;
Tested in example app on iOS simulator.

chore: update Podfile.lock file

---

android/src/main/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
android/src/main/java/com/reactnativekeyboardcontroller/StatusBarManagerCompatModule.kt
android/src/main/java/com/reactnativekeyboardcontroller/TranslateDeferringInsetsAnimationCallback.kt

Rewrite `!!` operator to `null checks with early return statements`.
Fixes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/38
Operator `!!` is not safe and we should avoid the usage of it everywhere it's possible, since it forces compiler to think that the object will never be `null` (but we are living in a real world, and you never know in advance the value of the object is coming to you).
Using this operator may lead to undesired crashes.
- Rewrite `!!` operator to `null checks with early return statements`;

fix: activity nullability

---

example/package.json
example/yarn.lock

Use `link:../` instead of `../`.
Using `../` instead of `link:../` can cause circular dependencies and because of that `node_modules` will take a lot of space on the disk.
- use symlink for local dependency linking
Tested manually.
|Before|After|
|------|-----|
|![tg_image_1095628465](https://user-images.githubusercontent.com/22820318/184607116-0e24bc47-05f2-44c6-90e2-2d3ce54c206a.jpeg)|<img width="742" alt="image" src="https://user-images.githubusercontent.com/22820318/184607301-0ce96afd-021b-4dbe-bdb8-f85a82366e09.png">|

chore: use symlink for local dependency linking

---

docs/package.json
docs/yarn.lock

Update docusaurus to `2.0.1`.
Use latest libraries version to keep the project in up-to-date state.
- bump `docusaurus` to `2.0.0`
Tested running locally.

chore: update docusaurus to 2.0 version

---

FabricExample/src/screens/Examples/Events/index.tsx
android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
example/src/screens/Examples/Events/index.tsx

Added `onApplyWindowInsets` into `WindowInsetsAnimationCompat.Callback` to detect keyboard size changes.
It seems like it's only one option to detect such changes. For me it's a little bit strange, that `onProgress`/`onEnd` callback is not called and we need to write additional code to track such cases.
Fixes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/54
- changed `Events` example - show `height` in all events;
- fixed a bug with missing `height` in all `keyboardDid*` events;
- detect keyboard size changes;
- renamed class that implements `WindowInsetsAnimationCompat.Callback` to `KeyboardAnimationCallback`;
- Xiaomi Redmi Note 5 Pro (Android 9)
- Pixel 3 (Android 12)
|Before|After|
|-------|----|
|<img width="343" alt="image" …

[RNKC-054] - detect keyboard size changes

---

ios/KeyboardController.xcodeproj/project.pbxproj
ios/KeyboardControllerViewManager.swift
ios/KeyboardMovementObserver.swift

Moved tracker implementation into own file.
It will be useful when we will reuse logic (when Fabric & Paper will be supported at the same time).
- added new `KeyboardMovementObserver` file;
- moved all tracking-related functionality into new file;
- simplified `KeyboardControllerViewManager` implementation;
Tested manually on iOS simulator using example app.

[RNKC-056] - move implementation from View to separate file

---

android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt

It turned out on API 30 `onApplyWindowInsets` can also be dispatched during keyboard animation.
To fix it I added a check `!isTransitioning`. It will exclude false positive calls and animation will be smooth.
Related PRs/issues:
- https://github.com/kirillzyusko/react-native-keyboard-controller/pull/62
- https://github.com/kirillzyusko/react-native-keyboard-controller/pull/58
- https://github.com/kirillzyusko/react-native-keyboard-controller/issues/54
- added `isTransitioning` property (changes its values in `onStart`/`onEnd`);
- use `isTransitioning` variable to prevent undesired calls.
Tested on:
- API 25
- API 28
- API 29
- API 30
- API 31
- API 32

[RNKC-054] - detect keyboard size changes (post post fix)

---

FabricExample/src/screens/Examples/ReanimatedChat/index.tsx
FabricExample/src/screens/Examples/ReanimatedChat/styles.ts
example/src/screens/Examples/ReanimatedChat/index.tsx
example/src/screens/Examples/ReanimatedChat/styles.ts

Slightly better version of chat example.
This PR brings a new (common) approach for chat-like ScrollViews. Instead of scrolling on mount we are applying double `scaleY: -1` and thus scroll view will show its content from the end.
- no overlapping effect on Android;
- no content position changes on iOS (fabric only);
- no scroll on mount;
- changed color of text input for better UI;
Tested manually on Pixel 3 (API 32, emulator) and iPhone 11 Pro (15.5, simulator) both architectures (paper + fabric).
|old|new|
|---|----|
|<video src="https://user-images.githubusercontent.com/22820318/193419301-c0a377ca-ba1e-49a3-9f65-c89384d49d6d.mov">|<video src="https://user-images.githubusercontent.com/22820318/193419328-fe76bd8d-3c1a-4c14-b709-972ced8f6a46.mov">|

[RNKC-069] - updated chat example

---

FabricExample/ios/Podfile.lock
android/src/main/java/com/reactnativekeyboardcontroller/KeyboardControllerPackage.kt
react-native-keyboard-controller.podspec
src/architecture.ts
src/monkey-patch.ts
src/native.ts

Use backward compatible `TurboReactPackage` instead of `ReactPackage`.
According to a new RN documentation it's the way how we should declare packages now.
- removed `architecture.ts` file since it's not used anymore;
- use `specs` as a single source of truth;
- added `OTHER_CPLUSPLUSFLAGS` in `Podfile` for `fabric` arch;
- use `TurboReactPackage`;
Tested manually on Pixel 3 (API 32).

[RNKC-071] -  convert ReactPackage to a backward compatible TurboReactPackage (android)

---

FabricExample/android/app/src/main/AndroidManifest.xml
FabricExample/src/components/KeyboardAnimation/index.tsx
FabricExample/src/components/KeyboardAnimation/styles.ts
FabricExample/src/screens/Examples/AwareScrollView/index.tsx
FabricExample/src/screens/Examples/Events/index.tsx
example/src/components/KeyboardAnimation/index.tsx
example/src/components/KeyboardAnimation/styles.ts
example/src/screens/Examples/AwareScrollView/index.tsx
example/src/screens/Examples/Events/index.tsx

Updated example project with some small fixes.
I decided to rework `KeyboardAnimation` example because of several reasons:
- now two circles stick to the bottom of the screen <- it will be easier to detect any insets changes (these circles will be cut);
- progress value is shown at the top of the screen (it will never be overlapped by the keyboard);
- text input field will be always covered by keyboard;
- reworked KeyboardAnimation example;
- added `useResizeMode` where it was needed to assure, that everything works on API < 30 too;
- set `adjustPan` for FabricExample on Android (to assure that native module actually changes necessary values);
Tested manually on Android (API 32, API 28) and iPhone (iOS 15.5).
|Before|After|
|------|-----|
|<img width="284" alt="image" …

[RNKC-076] - various small updates for example

---

FabricExample/src/constants/screenNames.ts
FabricExample/src/navigation/ExamplesStack/index.tsx
FabricExample/src/screens/Examples/Main/constants.ts
FabricExample/src/screens/Examples/NonUIProps/index.tsx
TODO
android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManagerImpl.kt
android/src/main/java/com/reactnativekeyboardcontroller/events/KeyboardTransitionEvent.kt
example/src/constants/screenNames.ts
example/src/navigation/ExamplesStack/index.tsx
example/src/screens/Examples/Lottie/index.tsx
example/src/screens/Examples/Main/constants.ts
example/src/screens/Examples/NonUIProps/index.tsx
ios/.swiftlint.yml
ios/KeyboardControllerView.mm
ios/KeyboardControllerViewManager.mm
ios/KeyboardControllerViewManager.swift
ios/KeyboardMoveEvent.h
ios/KeyboardMoveEvent.m
ios/KeyboardMovementObserver.swift
src/animated.tsx
src/context.ts
src/hooks.ts
src/internal.ts
src/specs/KeyboardControllerViewNativeComponent.ts
src/types.ts
src/utils.ts

Added new hook `useKeyboardHandler` that has gradual `height`/`progress` values on iOS. Also it has a little bit different API than already existing hooks. See **Motivation and Context** section to get more insights of why this approach was chosen.
- https://github.com/kirillzyusko/react-native-keyboard-controller/issues/85
- https://github.com/kirillzyusko/react-native-keyboard-controller/discussions/56
The current limitation of this library on iOS was the fact, that `height` and `progress` values didn't have intermediate values. So if you are trying to animate NonUiProps, such as `height`, `width` etc. - you get instant transitions, that looks not well. That's where `useKeyboardHandler` comes into play.
This hook allows you to get intermediate values. Unfortunately values in `onMove` …

[RNKC-061] - introduce low-level `useKeyboardHandler` hook

---

FabricExample/src/navigation/ExamplesStack/index.tsx
FabricExample/src/screens/Examples/ReanimatedChat/hooks.ts
FabricExample/src/screens/Examples/ReanimatedChat/index.tsx
FabricExample/src/screens/Examples/ReanimatedChat/styles.ts
example/src/navigation/ExamplesStack/index.tsx
example/src/screens/Examples/ReanimatedChat/hooks.ts
example/src/screens/Examples/ReanimatedChat/index.tsx
example/src/screens/Examples/ReanimatedChat/styles.ts

Added example of custom keyboard animation that actively used in Telegram app.
I always was impressed of keyboard animation smoothness on my Android 9 device. So I dig into Android implementation and ported it to react-native 😄 
- added toggler for switching keyboard interpolator (platform, telegram)
- Pixel 2 (emulator, API 28);
- Pixel 3 (emulator, API 32);
- Xiaomi Redmi note 5 Pro (real device, API 28);
- iPhone 11 Pro (simulator, iOS 15.5).
https://user-images.githubusercontent.com/22820318/195857524-d7a966b9-6b24-43cc-8f82-59d3589dcc12.mov

[RNKC-080] - telegram keyboard transition

---

ios/KeyboardMovementObserver.swift

Added optional chaining instead of forced unwrapping. Fixes crash described in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/93
In fact it's not a fix and is more avoiding NPE rather than a full fix. But anyway, missing animation is better, than a crash of application 🤷‍♂️ 
- avoid usage of forced unwrapping
Tested locally on:
- iPhone 13 Pro (iOS 15.0);

fix: avoid usage of forced unwrapping

---

src/animated.tsx
src/internal.ts

Added `useAnimatedValue` hook for storing `Animated.Value`. For internal usage only.
Variant with:
```ts
const value = useRef(new Animated.Value(0)).current;
```
Is not good, since `new Animated.Value(0)` will be recreated on every re-render (it will not have direct pointers so it will be collected by GC, but it's additional job for memory allocation and further deallocation which is not needed in the fact).
Variant with:
```ts
const [value] = useState(() => new Animated.Value(0));
```
May also be a not good alternative, since the function inside of `useState` will be re-created on every re-render.
So the variant with `useAnimatedValue` hook seems a best candidate for that, since it will create a value only once (on initial render).
- added `useAnimatedValue` hook for internal usage; …

refactor: added `useAnimatedValue` hook for internal usage

---

ios/.swiftlint.yml

Fixed failed SwiftLint on CI.
Don't know why it didn't fail before. Seems like new version of `swiftlint` has been released (`0.50.0`) where the rule has been rewritten. I think it's a cause of the issue.
I've tried to downgrade version of `swiftlint` in CI and lock it there, but I didn't find a way how to manage it 🤷‍♂️ 
- ignore `for_where` rule for `swiftlint`;
Tested on GitHub actions (CI).

refactor: ignore `for_where` rule for swiftlint

---

.github/workflows/build-android-fabric.yml
.github/workflows/build-android.yml
.github/workflows/build-ios-fabric.yml
.github/workflows/build-ios.yml
.github/workflows/deploy-docs.yml
.github/workflows/verify-android.yml
.github/workflows/verify-cpp.yml
.github/workflows/verify-ios.yml
.github/workflows/verify-js.yml

Switch to `actions/checkout@v3` instead of `actions/checkout@v2`.
Since checkout@v2 is using NodeJS v12 and the usage of v12 soon will be deprecated on GitHub actions I decided to update checkout actions to latest v3 version which is using NodeJS v16 by default.
- switch to `actions/checkout@v3` instead of `actions/checkout@v2`.
Tested on GitHub actions. Everything seems to be working fine 😁

chore: switch to `actions/checkout@v3` instead of `actions/checkout@v2`

---

android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardControllerViewManagerImpl.kt

Use context provided by `createViewInstance` for view creation.
Partially fixes the problem described in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/113
We need to use actual context provided by `createViewInstance`. Otherwise after hot reloading context may be invalid and keyboard events will not be send to JS thread (since UIManager will be invalid).
- use `reactContext` from params instead of constructor value;
Tested manually on Pixel 7 Pro and Xiaomi Redmi Note 5 Pro (real devices).

fix: create view using context provided by `createViewInstance` method

---

FabricExample/android/app/src/main/java/com/keyboardcontrollerfabricexample/MainActivity.java
example/android/app/src/main/java/com/example/reactnativekeyboardcontroller/MainActivity.java

Don't persist activity state and always restart it.
I don't know why I didn't make it before, but it needs to be added in order to reduce amount of occasional crashes. You can read a great explanation [here](https://github.com/software-mansion/react-native-screens#android) on why it's needed.
- added `super.onCreate(null)` in `MainActivity` for example apps;
Tested manually on emulators.

fix: restart activity to avoid crashes

---

android/src/main/java/com/reactnativekeyboardcontroller/extensions/View.kt
android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardControllerViewManagerImpl.kt

Call `requestApplyInsetsWhenAttached` when `onApplyWindowInsets` listener is added.
It's needed in order to fix a situation, when after reloading JS bundle first keyboard events are not coming. The problem is reproducible only in bare project (i. e. no other 3rd party libraries), since if you add navigation to your app, then `react-native-screens` will "fix" the problem. But of course it's not reliable to rely on 3rd party libraries behaviour and the library should work in bare project too.
Fixes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/113#issuecomment-1424217269
- `requestApplyInsets` when the view is attached to the hierarchy;
- Pixel 3 (API 28, emulator);
- Pixel 7 Pro (API 33, real device)

fix: request apply insets when the view is attached to the hierarchy

---

android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardControllerViewManagerImpl.kt
android/src/paper/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
src/animated.tsx
src/specs/KeyboardControllerViewNativeComponent.ts
src/types.ts

Added new `navigationBarTranslucent` prop on `KeyboardProvider`.
To make it more customizable and support translucent navigation bar I decided to add a new prop called `navigationBarTranslucent`. This prop follows the same pattern as `statusBarTranslucent`.
Fixes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/119
- updated specs for fabric codegen;
- added handling of new property (if property is set to `true`, then we are setting 0 bottom padding - the same logic is already used for controling status bar transparency);
Manually tested on:
- Pixel 3a (API 33, emulator);
- Pixel 6 Pro (API 28, emulator)
|Before|After|
|-------|---------------|
|<img width="226" alt="image" src="https://user-images.githubusercontent.com/22820318/221593460-a65f9136-ae60-40e0-8243-154c …

feat: add `navigationBarTranslucent` prop

---

FabricExample/src/screens/Examples/ReanimatedChat/styles.ts
example/src/screens/Examples/ReanimatedChat/styles.ts

Changed a way of achieving inverted `ScrollView`. Old way could cause significant FPS drop if app has long running animation.
Originally fix/improvement was made in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/76
But it seems like any animation + `scaleY: -1` may lead to significant FPS drop.
The suggested way from comments is the usage of `rotate: '180deg'` instead of `scaleY: -1`. I verified and it works much better and I didn't encounter any issues, so let's rework the approach a little bit and use `rotate: '180deg'` for now.
- changed `scaleY: -1` to `rotate: '180deg'`;
Tested manually (only example app) on:
- Google Pixel 7 Pro (Android 13, real device);
- iPhone 14 Pro (iOS 16.2, simulator).
|Before|After|
|<video …

refactor: rotate on `180deg` instead of `scaleY: -1` to eliminate freezes of ScrollView on Android

---

android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt

Added `@reactProp` annotation to make view property setters working.
It seems for RN 0.70 and for fabric we still need to use `@ReactProp` annotation. See an example: https://reactnative.dev/docs/0.70/the-new-architecture/pillars-fabric-components#rtncenteredtextmanagerjava
- added `@ReactProp` annotation for view props (`statusBarTranslucent`, `navigationBarTranslucent`) for fabric view manager;
Tested on Pixel 7 Pro (API 33, real device).

fix: view props setters on Fabric

---

FabricExample/android/app/src/main/res/values/styles.xml

Make `StatusBar` translucent on Fabric, since it's also translucent in Paper example.
Both examples app should have the same codebase (including styles).
- `android:statusBarColor=@android:color/transparent`
Tested manually on Pixel 7 Pro (API 33, real device).

chore: sync android styles between example apps (paper & fabric)

---

FabricExample/src/screens/Examples/ReanimatedChat/styles.ts
example/src/screens/Examples/ReanimatedChat/styles.ts

Specified color for text in right header (chat example).
If dark theme is turned on on Android devices, then Android may change colors automatically. To assure it looks the same across all themes we need to specify color.
- added `color: 'black'` for `header` style in chat example screen;
Tested on Pixel 7 Pro (Android 13).
|Before|After|
|------|------|
|![telegram-cloud-photo-size-2-5221974934337734638-y](https://user-images.githubusercontent.com/22820318/224700833-9d2fa00e-43fc-4210-8305-cefcf904b1f2.jpg)|![telegram-cloud-photo-size-2-5221974934337734639-y](https://user-images.githubusercontent.com/22820318/224700882-6db85f0e-a213-42b0-ad68-17e9cd3e355b.jpg)|

chore: add color for right header in Chat example

---

android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/events/KeyboardTransitionEvent.kt
android/src/main/java/com/reactnativekeyboardcontroller/extensions/Float.kt
ios/KeyboardControllerView.mm
src/specs/KeyboardControllerViewNativeComponent.ts

Return `height` value as `double` instead of `integer`.
Rounded values can create an effect of "laggy" animations. It's hard to notice when keyboard simply opens and closes, but it's easy to notice when keyboard becomes interactive (i. e. position can be controlled via gesture). To fix this effect we need to send as precise as possible values.
- changed spec of `KeyboardViewController` (now both `progress` and `double` are returned as `double`);
- send `height` as double on Fabric architecture;
- send `height` as double;
- fixed Android studio warnings;
Tested both (fabric & paper) on:
- Pixel 7 Pro (real device, Android 13);
- iPhone 14 Pro (emulator, iOS 16.2).
|Before|After|
|<video src="https://user-images.githubusercontent.com/22820318/227630300-98ca4ac9-6c15-4d3c-b705 …

refactor: send `height` as `double` value

---

docs/docusaurus.config.js
docs/package.json
docs/yarn.lock

Upgraded `docusaurus` to `2.4.0`.
To keep project up-to-date 🙂 
- update `docusaurus` to `2.4.0`;
- changed `type` to `docSidebar` and `docId: 'installation',` -> `sidebarId: 'tutorialSidebar',`;
Tested on localhost:3000.

docs: docusaurus v2.4.0

---

FabricExample/src/screens/Examples/AwareScrollView/KeyboardAwareScrollView.tsx
FabricExample/src/screens/Examples/AwareScrollView/index.tsx
FabricExample/src/screens/Examples/AwareScrollView/styles.ts
FabricExample/src/screens/Examples/Main/constants.ts
example/src/screens/Examples/AwareScrollView/KeyboardAwareScrollView.tsx
example/src/screens/Examples/AwareScrollView/index.tsx
example/src/screens/Examples/AwareScrollView/styles.ts
example/src/screens/Examples/Main/constants.ts

Improved `AwareScrollView` example. Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/99
I've decided to improve AwareScrollView example. First of all I extracted the component into reusable component. In second turn I improved scrolling interpolation. In previous example it wasn't perfectly synchronised with keyboard movement. Also in previous example when keyboard disappeared the transition was instant. In new component everything works buttery-smoothly 😊 
- extracted `KeyboardAwareScrollView` into separate component;
- make a better interpolation for scrolling;
Tested manually:
- Redmi Note 5 Pro;
- Pixel 7 Pro;
- iPhone 6s;
- iPhone 14 Pro (simulator);
|Before|After|
|------|-----|
|<video src="https://user-images.githubusercontent.com/22820318/230711186-68 …

refactor: better KeyboardAwareScrollView example

---

FabricExample/src/screens/Examples/InteractiveKeyboard/index.tsx
android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardGestureAreaViewManager.kt
android/src/paper/java/com/reactnativekeyboardcontroller/KeyboardGestureAreaViewManager.kt
docs/docs/api/keyboard-gesture-area.md
docs/versioned_docs/version-1.5.0/api/keyboard-gesture-area.md
example/src/screens/Examples/InteractiveKeyboard/index.tsx
src/specs/KeyboardGestureAreaNativeComponent.ts
src/types.ts

Use shorter name for `KeyboardGestureArea` props.
- `allowToShowKeyboardFromHiddenStateBySwipeUp` -> `showOnSwipeUp`
- `allowToDragKeyboardFromShownStateBySwipes` -> `enableSwipeToDismiss`
Short names are better. Honestly I also didn't like such big names, but at the time of the implementation I decided not to think about correct names 😅 
By gathering a feedback I've decided to rename it (I've decided not to mark old props as deprecated because it would bring more confusions). I highly doubt there are any people who just started to use this new feature and already shipped it to theirs applications, so I'm going to do a small `1.5.1` release after merging this PR.
- renamed props;
- renamed props;
- renamed props and corresponding setters;
Tested on emulator.

refactor: short names for `KeyboardGestureArea` component props

---

ios/KeyboardMovementObserver.swift

Remove KVO when keyboard disappears.
It seems like we can not attach a single listener to the keyboard when it appeared for the first time. iOS may throw `KVO_IS_RETAINING_ALL_OBSERVERS_OF_THIS_OBJECT_IF_IT_CRASHES_AN_OBSERVER_WAS_OVERRELEASED_OR_SMASHED`, which means, that the memory for the listener was released and thus a handler is corrupted (KVO was released while still observing the key path).
To overcome the problem I've decided to remove observation when keyboard becomes hidden. To detect the moment when keyboard got hidden I used `UIWindow.didBecomeHiddenNotification` (since for attaching a KVO listener I've used `UIWindow.didBecomeVisibleNotification` - the motivation behind "why I've used these lifecycles" is the fact, that these lifecycle methods will be triggered only one …

fix: cleanup kvo

---

android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardControllerViewManagerImpl.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
android/src/paper/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt

Moved logic from manager to `EdgeToEdgeReactViewGroup`.
To align with standard approaches and unify codebase.
When I've added `KeyboardGestureView` I incapsulated all logic inside this view and delegated only method calls to manager. In this PR I've decided to stick with this approach and rework `EdgeToEdgeReactViewGroup`.
Just theoretically setting up of callbacks could be moved to `onAttachedToWindow` method, but I've decided to keep changes as minimal as possible, so I left it as it is.
- move logic away from manager to `EdgeToEdgeReactViewGroup`
Tested on Pixel 6 (API 28). Both fabric & paper.

refactor: move logic away from manager to `EdgeToEdgeReactViewGroup`

---

android/build.gradle
android/gradle.properties

Use minSdkVersion from root project.
If you try to assemble test build you'll get next error:
```
Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-android:0.71.3] /Users/kirylziusko/.gradle/caches/transforms-3/8b07754142de06fa88289354ebe36ee0/transformed/jetified-react-android-0.71.3-debug/AndroidManifest.xml as the library might be using APIs not available in 16
Suggestion: use a compatible library with a minSdk of at most 16,
or increase this project's minSdk version to at least 21,
or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)
```
It happens because `16` is hardcoded in `minSdkVersion` of this project. Proper solution would be to try to take …

fix: use minSdkVersion from root project

---

ios/KeyboardMovementObserver.swift

Use memoized `keyboardView` reference for removing observer.
Since `keyboardView` is a getter there are some chances that it may return a new reference to a view when we access it.
In some cases it may be a problem, because it can return a reference to a view which doesn't contain an observer yet. As a result when we'll try to remove an observer from a view which doesn't have it -> we'll get a crash.
To prevent a crash in `removeKVObserver` we start to use `_keyboardView` instead of `keyboardView`. It'll give us an access to old view and we can safely remove the observer.
Fixes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/155
Potentially also fixes: https://github.com/kirillzyusko/react-native-keyboard-controller/issues/152
- use `_keyboardView` instead of …

fix: use old `keyboardView` reference for removing observer

---

README.md
docs/src/components/HomepageFeatures/index.tsx

Changed `appearance` word to `movement`.
Better to use `movement` since it better describes what this package does.
- appearance -> movement in README;
- appearance -> movement in docs;
Tested manually via .md preview.

docs: appearance -> movement

---

ios/KeyboardControllerView.mm
ios/KeyboardControllerViewManager.swift

Added a check for `_jsThread==null` before sending event. Should prevent crash on startup in certain conditions.
- check `_jsThread` to exist before sending event;
Will be tested in live 🙃

fix: check if `jsThread` is not null

---

ios/Extensions.swift
ios/KeyboardController.xcodeproj/project.pbxproj
ios/KeyboardMovementObserver.swift

Moved `interpolate` function to Extensions.
To follow SOLID principles -> each file should have own responsibility. From my point of view it's not correct to keep `interpolate` function in `KeyboardMovementObserver`, so in this PR I've created a new file and moved `interpolate` implementation to this file.
In future I'll create more extensions 🙂 
- added `Extensions.swift` file;
- move `interpolate` function to `Extensions.swift`.
Tested manually on simulator.

refactor: move `interpolate` function to Extensions

---

src/animated.tsx

On native ios navigation, tabBarController does not add blur unless scrollView is first in the component hierarchy. 
It is necessary that an empty view is declared only after children.
Wrong behavior:
Right behavior:
This fix adds maximum compatibility with native iOS navigation.
changed an order of the "view" component
To test the change, I use my native navigation library for ios. In this case, we just need to test that the change didn't break keyboard behavior.

fix: Add compatibility with native iOS navigation

---

android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt

Added support for upcoming non-transitive R-classes.
For upcoming Android Studio Flamingo release and Android Gradle Plugin (AGP) 8.0 it's important to support transitive R-classes. Otherwise the build will fail.
In this PR I've changed `R.id.action_bar_root,` to `androidx.appcompat.R.id.action_bar_root`. Initially Android Studio offers to use `com.facebook.react` prefix, but I believe `androidx.appcompat` is more appropriate prefix, since `R.id.action_bar_root` is available for all android apps even built without react-native.
- changed`R.id.action_bar_root` -> `androidx.appcompat.R.id.action_bar_root`;
Tested manually on example app.
I've added `android.nonTransitiveRClass=true` to `gradle.properties` - build is successful:

refactor: support for non-transitive R-classes

---

ios/KeyboardMovementObserver.swift

Fixed a crash on iOS 16.5 when native alert is getting shown.
The original exception occurred because of this error:
```bash
libc++abi: terminating due to uncaught exception of type folly::json::print_error: folly::toJson: JSON object value was an INF when serializing value at "progress"
```
`progress` was `inf` because in:
```swift
onEvent("onKeyboardMove", keyboardPosition as NSNumber, keyboardPosition / CGFloat(keyboardHeight) as NSNumber)
```
`keyboardHeight` variable was `0`. When we were trying to divide any number by `0` in swfit we get `Inf` value, and this value can not be serialised to JS equivalent.
The reason why this value becomes `0` is the fact that we have next chain of calls:
```
keyboardWillHide
keyboardDidHide <- here we are setting keyboardHeight=0
keyboardWillHide <- …
```

fix: native alert crash

---

ios/KeyboardMovementObserver.swift

The line `result = hostView as? UIView` will not give any error but it is superfluous.
You're traversing a hierarchy of subviews, which are all UIView objects. In Swift, subviews is an array of UIView.
Just housekeeping a bit :)
- 
- 
- 
- 
- 
- 
iOS Device and Simulator

fix: casting UIView to UIView always succeeds

---

ios/KeyboardMovementObserver.swift

Ignore values from KVO when they're considered as invalid.
There was a problem, that on some devices when you complete interaction with the keyboard KVO may submit two random events, for example (below I include last valid event + 2 subsequent invalid events):
- 52/160/108;
- 15/123/108;
- 103/211/108;
- 56/164/108.
It's values for `keyboardPosition` variable which is calculated in next way:
```swift
let keyboardFrameY = (change?[.newKey] as! NSValue).cgPointValue.y
let keyboardWindowH = keyboardView?.window?.bounds.size.height ?? 0
let keyboardPosition = keyboardWindowH - keyboardFrameY
```
As you can see there is a pattern:
- we take last event and sum it up with 2 random event -> we get first random event (52+108=160);
- we submit last event as constant (it never changes over time - …

fix: ignore invalid values from KVO

---

TODO
android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationController.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/KeyboardGestureAreaReactViewGroup.kt

Don't hide keyboard if gesture didn't affect its position.
Initially I fixed this problem by excluding a call to `animateToFinish`. However it brought more problems:
- since `InteractiveKeyboard.isInteractive` value couldn't be reset in some cases (when interaction with keyboard was completed), it could lead to unpredictable results (for example `onInteractive` event will be emitted instead of `onMove` for plain keyboard events);
- when you hide a keyboard by pressing hide button when interactive gestures were finished - `onMove` events were not coming (because `progress` was `Infinity` and couldn't be serialised via bridge - it happened because in `onEnd` callback we were updating `persistentKeyboardHeight` value, but `getCurrentKeyboardHeight()` was returning `0` - it happened because …

fix: pass `velocityY=null` if keyboard didn't change its height

---

FabricExample/src/screens/Examples/Events/index.tsx
android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/events/KeyboardTransitionEvent.kt
example/__tests__/keyboard-handler.spec.tsx
example/src/screens/Examples/Events/index.tsx
ios/KeyboardControllerView.mm
ios/KeyboardControllerViewManager.swift
ios/KeyboardMoveEvent.h
ios/KeyboardMoveEvent.m
ios/KeyboardMovementObserver.swift
src/specs/KeyboardControllerViewNativeComponent.ts
src/types.ts

Added `duration` to plain and worklet events.
As part of enhancement events metadata it would be good to have `duration` prop. It may allow to create kind of parallax effect (when animation duration is equal, but easing functions are different).
- added `duration` to spec file;
- updated example app;
- extract duration and send it in eventemitter and in view events;
- extract duration and send it in eventemitter and in view events;
- Pixel 7 Pro (Android 13);
- Xiaomi Redmi Note 5 Pro (Android 9);
- iPhone 14 Pro (iOS 16.5);

feat: duration

---

FabricExample/src/screens/Examples/Events/index.tsx
android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
example/src/screens/Examples/Events/index.tsx
ios/Extensions.swift
ios/KeyboardMovementObserver.swift
src/types.ts

Added `timestamp` property to events that are delivered via EventEmitter.
Since these events arrive asynchronously it's important to understand the delay. Below is a table with typical delay across different devices:
|Device|AVG delay|
|--------------------------|-----------|
|Xiaomi Redmi Note 5 Pro  |       2-5ms|
|iPhone 6s                            |       4-8ms|
|Pixel 7 Pro                           |        0-1ms|
- added new property to `KeyboardEvents` module.
- added new property to `KeyboardEvents` module.
- added new property to `KeyboardEvents` module.
- Pixel 7 Pro (Android 13);
- iPhone 6s (iOS 15.5);
- iPhone 11 (iOS 16.5);
- Xiaomi Redmi Note 5 Pro (Android 9).

feat: timestamp

---

FabricExample/ios/Podfile.lock
android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/events/KeyboardTransitionEvent.kt
ios/Extensions.swift
ios/KeyboardController-Bridging-Header.h
ios/KeyboardControllerView.mm
ios/KeyboardControllerViewManager.swift
ios/KeyboardMoveEvent.h
ios/KeyboardMoveEvent.m
ios/KeyboardMovementObserver.swift
react-native-keyboard-controller.podspec
src/specs/KeyboardControllerViewNativeComponent.ts
src/types.ts

Added `target` field which represent a `viewTag` of focused `TextInput` field.
If we know tag of focused field we can apply advanced techniques and require additional information on demand (for example measure layout and calculate the scroll amount).
I had a lot of designs on how to implement this feature. The main tradeoff was about whether this information should be provided as **separate hook** or should it be included as **part of keyboard event metadata**.
For simplicity purpose I've decided to deliver this information as part of keyboard events (because there appears a lot of problems with synchronization values between various hooks - you'll need to assure that one variables are updated before other or run something in effects/reactions and it can make your code more difficult for …

feat: target

---

docs/docs/api/hooks/use-keyboard-handler/index.mdx
docs/docs/api/keyboard-events.md

Added a documentation about new fields:
- duration;
- timestamp;
- target;
Without documentation it'll be hard to know, that these fields exist 😅 
- added info about `duration`, `timestamp` and `target` fields;
Tested on localhost:3000

docs: info about new fields

---

scripts/size.js

Added `size.js` script which creates a package and prints zipped size.
This is related to this https://github.com/kirillzyusko/react-native-keyboard-controller/pull/201 PR. The reason why it handled in separate PR is because script in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/201 switches to target branch (`main`), but since the script is not available in this branch - I can not verify that script works as expected.
- added `scripts/size.js` file;
Was tested in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/201

feat: size script

---

android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/extensions/ThemedReactContext.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt

Setup `onApplyWindowInsetsListener` that manages `systemBars` and `navigationBar` on `rootView` to get correct and constant insets.
If we setup `onApplyWindowInsetsListener` on `EdgeToEdgeReactViewGroup`, then sometimes insets are including keyboard size (it's is `0, 1225` (top, bottom) instead of expected `144, 84`).
I discovered that if we setup `onApplyWindowInsetsListener` on `rootVIew` - in this case insets are always stable. So I reworked this part (worth to note that `onApplyWindowInsetsListener` that detects keyboard size changes still should listen to `EdgeToEdgeReactViewGroup` because otherwise it's not working).
It fixes a problem with content jump, however the old approach (setting `padding` for `action_bar_root`) is not working anymore - instead we should apply margin. Last, …

refactor: new way for handling insets

---

example/__tests__/keyboard-handler.spec.tsx

Added `target: 123` to mock data in unit tests.
Seems like I forgot to do that in original PR (https://github.com/kirillzyusko/react-native-keyboard-controller/pull/191) - so I'm adding it here 🙂 
- added missing `target` filed in tests;
Tested via running a test 🙂

refactor: added `target` property to mock in unit tests

---

docs/docs/guides/building-own-hook.md
src/context.ts
src/hooks.ts

Added a warning if `defaultContext` is consumed.
Fixes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/213
- added `useKeyboardContext` hook;
- added a check in `useKeyboardContext` that `defaultContext` is consumed and showing a warning;
- replaced `useContext(KeyboardContext)` with `useKeyboardContext`;
Tested on iPhone 14 Pro (iOS 16.4).
|Minimized|Full screen|
|----------|-----------|
|![image](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/ae6ffc57-8ca3-4304-9059-a805c312f056)|![image](https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/2e0ee8c6-afd6-4a56-bdf3-6ebf89f47b41)|

feat: added warning if default context is consumed

---

example/src/screens/Examples/AwareScrollView/KeyboardAwareScrollView.tsx

Improved `KeyboardAwareScrollView` example - now it react on `TextInput` focus changes 🙂 
I highlighted key changes below:
Before it was a fixed number (0). But since the size of the keyboard can be different per different `TextInput` types - we have to interpolate value from previous keyboard size to the new one. Otherwise the animation when keyboard changes its size looks slightly ugly (will have a jump in beginning).
Just as an example let's imagine, that the keyboard is changing size from `200` to `300` and you need to scroll from `100` to `200`. The current scroll position is `100` and you interpolate as before from 0 to 300. In this case, when keyboard size grows from 200 to 300 first scrollTo will scroll to ~160. So 60% of the smooth transition will be missed 😔 
If we interpolate …

refactor: react on tag changes

---

FabricExample/src/screens/Examples/AwareScrollView/KeyboardAwareScrollView.tsx
FabricExample/src/screens/Examples/AwareScrollView/TextInput.tsx
FabricExample/src/screens/Examples/AwareScrollView/context.tsx
FabricExample/src/screens/Examples/AwareScrollView/index.tsx
example/src/screens/Examples/AwareScrollView/KeyboardAwareScrollView.tsx

Ported `KeyboardAwareScrollView` example to `FabricExample` app.
Basically I ported paper example to fabric. However there is two main differences between implementations.
You can not call `measure(() => tag)` as in paper, because it expects to see an associated instance of `ShadowNode`. There was two ways how to achieve that:
- use `findShadowNodeByTag_DEPRECATED` - but it's deprecated and it's obviously that better not to use (basically this method go through all views until it finds a view for a given `tag` - I think it may hit performance issues as well);
- take `ShadowNode` from a `ref` of `TextInput`.
I've decided to stick with 2nd approach (just because it's not deprecated). For that purposes I added context where I store a map like:
```ts
{
[tag]: () => shadowNodeOrTag
}
```
In …

chore: port `KeyboardAwareScrollView` to Fabric

---

ios/Extensions.swift
ios/KeyboardController-Bridging-Header.h

Cast `UIResponder.current` to `UIView` instead of `RCTUITextField`.
It seems like casting to `RCTUITextField` may not always succeed because internal layout may be different per different TextInput types (multiline vs not-multiline), see table below:
|Single input|Multiline input|
|------------|--------------|
|<img width="194" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/b55a76f4-6103-4081-853b-807bb985bbe8">|<img width="195" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/c4d94f54-7612-492a-8460-cdf06e97e1a1">|
To overcome this problem I've decided to cast `UIResponder.current` to `UIView`. This casting is successful in both cases (multiline and not-multiline) and give expected …

fix: cast `UIResponder.current` to `UIView` instead of `RCTUITextField`

---

README.md
android/src/main/java/com/reactnativekeyboardcontroller/extensions/ViewGroup.kt
android/src/main/java/com/reactnativekeyboardcontroller/modules/KeyboardControllerModuleImpl.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt

Fixed an integration with `react-native-navigation` without hacks.
To overcome the initial problem I've decided to re-create callback between `onAttachedToWindow`/`onDetachFromWindow` lifecycles. It improves the situation, but at some point of time you still may inconsistent values returned by hook and actual keyboard position.
For me it seems like if the `WindowInsetsAnimationCompat.Callback` is attached to any parent view of the current screen (i. e. `decorView`, `rootView`, etc.), then it can be broken after some navigation cycles.
This solution was inspired by https://github.com/Omelyan/RNNKeyboardController-Test/commit/d5ee7eaf90e0ef90fcf9ed6d71dd1f44803e5e62. If we send events through overlay, then it's never broken. I had a look on a view hierarchy and realised, that overlays are …

fix: react-native-navigation integration

---

android/src/main/java/com/reactnativekeyboardcontroller/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/events/KeyboardTransitionEvent.kt
docs/docs/guides/compatibility.md

Re-worked deprecated API for `RCTEventEmitter ` on Android. Minimal supported RN version is 0.65.
Updated compatibility page in docs.
Deprecated API sooner or earlier will be removed, so there is no sense to keep the usage of deprecated API.
In this PR I've decided to drop a support of really old RN versions and remove usage of deprecated APIs. For that I reworked event dispatching API 🙂 
- added info about minimal supported version of RN for paper architecture;
- added `surfaceId` to the event;
- removed `dispatch` method;
- override `getEventData` method.
Tested on Pixel 7 Pro (both fabric & paper). Works as before.

refactor: migrate from deprecated `RCTEventEmitter`

---

FabricExample/src/screens/Examples/KeyboardAvoidingView/index.tsx
FabricExample/src/screens/Examples/KeyboardAvoidingView/styles.ts
example/src/screens/Examples/KeyboardAvoidingView/index.tsx
example/src/screens/Examples/KeyboardAvoidingView/styles.ts
src/components/KeyboardAvoidingView/hooks.ts
src/components/KeyboardAvoidingView/index.tsx

Return `KeyboardAvoidingView` to its initial size when keyboard gets closed.
Usage of `if (bottomHeight > 0) {` is incorrect, because in this case we are not returning a view to its original size. Let's imagine that `frame.value.height = 500`. And `bottomHeight` goes from `300` to `0`. Last two values could be `1.33` and `0`. In this case we will set `height` to `500 - 1.33` as final frame, but it's incorrect, because we should return it back to `500` when keyboard is getting closed.
So in this PR I'm adding new `isClosed` variable, that will be `true` only when keyboard is fully closed. When keyboard begin the movement - value will be `false`. And instead of relying on `if (bottomHeight > 0) {` I'm relying now on `isClosed` variable: `if (!keyboard.isClosed.value) {`.
Such approach will …

fix: return `KeyboardAvoidingView` to its initial size after keyboard closing

---

FabricExample/android/app/src/main/AndroidManifest.xml
FabricExample/src/App.tsx
android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
example/android/app/src/main/AndroidManifest.xml
example/src/App.tsx

Remove `eventView` asynchronously.
It seems that before opening a universal link and before `onDetachedFromWindow` Android takes a snapshot of view hierarchy. Then in `onDetachedFromWindow` we are removing a View and later Android calls `dispatchDetachedFromWindow` for each view from snapshot. But since we've already removed a view it tries to call a method on `null` object reference and we are getting an expected NPE.
In this PR I've reworked an approach (to one that was suggested in the thread of the issue). And I remove a view asynchronously. It shouldn't add more new issues, but it'll prevent NPE in the case described above, because we'll remove a view after `dispatchDetachedFromWindow` has been called.
Also I've added deep links/universal links to both examples app (paper, fabric). …

fix: async view removal from `onDetachedFromWindow`

---

.github/workflows/size-diff.yml

Allow contributors to run `check-diff` job.
Specified `permission` as `pull-requests: write` to fix **Error: Resource not accessible by integration**.
A sample of error: https://github.com/kirillzyusko/react-native-keyboard-controller/actions/runs/6406320042/job/17390681956?pr=252
- specify `permission` as `pull-requests: write`.
I'll merge it and will test later in another PR.

fix: allow contributors to run `check-diff` job

---

.eslintrc.cjs
package.json
src/animated.tsx
src/bindings.native.ts
src/bindings.ts
src/components/KeyboardAvoidingView/hooks.ts
src/components/KeyboardAvoidingView/index.tsx
src/constants.ts
src/context.ts
src/hooks.ts
src/internal.ts
src/replicas.ts
src/specs/KeyboardControllerViewNativeComponent.ts
src/specs/KeyboardGestureAreaNativeComponent.ts
src/specs/NativeKeyboardController.ts
src/specs/NativeStatusBarManagerCompat.ts
yarn.lock

added @typescript-eslint/eslint-plugin to support importing and exporting types with eslint to avoid adding some types file in the final build. Also, it would be useful to have a more strict eslint in the project 🙂 . 
code base improvement
- Created .eslintrc.cjs with eslint configuration.
- Added @typescript-eslint/eslint-plugin, @typescript-eslint/parser and eslint-plugin-jest
Tested with the `yarn lint` command 🙂 .

refactor: integrate `typescript-eslint-plugin`

---

FabricExample/src/screens/Examples/AwareScrollView/useSmoothKeyboardHandler.ts
example/src/screens/Examples/AwareScrollView/useSmoothKeyboardHandler.ts

this is more or less a stylistic change, the `useAnimatedReaction` hook is better suited for this than `useDerivedValue` which is supposed to derive a value, but not have side effects
not needed I guess?
I ran this on an Android 10 device (huawei) and it works the same as before. 
I used the 'Aware scroll view' example to test this out and I have to say that, unfortuantely, on my device the animation is not (and was not) smooth. That's a different problem though, I might try to open a PR for that later.

fix: use animated reaction instead of derivation

---

FabricExample/android/build.gradle
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties

Updated `gradle` to `6.9.4` and `kotlin` to `1.8.22`.
It was needed to fix compilation issues in https://github.com/kirillzyusko/react-native-keyboard-controller/actions/runs/6580087395/job/17877337926?pr=257
```bash
...
e: /home/runner/work/react-native-keyboard-controller/react-native-keyboard-controller/android/src/paper/java/com/reactnativekeyboardcontroller/StatusBarManagerCompatModule.kt: (24, 12): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
The class is loaded from /home/runner/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/kotlin/Unit.class
e: …
```

chore: update gradle & kotlin versions

---

docs/docs/api/components/keyboard-sticky-view/index.mdx
docs/src/components/ComparisonTable/index.tsx
docs/src/components/KeyboardAvoidingViewComparison/index.tsx

Added `KeyboardAvoidingView` and `KeyboardStickyView` comparison.
To make people aware about when and how to use these two components.
- added `KeyboardAvoidingView` and `KeyboardStickyView` comparison (as lottie animation)l
Tested on `localhost:3000`.

docs: added `KeyboardAvoidingView` and `KeyboardStickyView` comparison

---

.github/workflows/argos.yml
.github/workflows/docs-e2e.yml
docs/__tests__/screenshot.css
docs/__tests__/screenshot.spec.ts
docs/__tests__/utils.ts
docs/blog/2022-06-22-welcome/index.mdx
docs/blog/2023-04-10-interactive-keyboard/index.mdx
docs/blog/2023-08-25-enhanced-metadata/index.mdx
docs/package.json
docs/playwright.config.ts
docs/src/components/ComparisonTable/index.tsx
docs/src/components/HomepageFeatures/index.tsx
docs/yarn.lock

Added playwright + agros for detection of UI regressions.
I'm going to update docusaurus to 3.0 in the near future. However I've discovered some UI regressions which are quite important. So I want to be sure the migration will be smooth and will not introduce any problems.
- added a new scrip that detects UI regressions;
- added integration with argos;
- added e2e tests for docs;
Tested locally.

docs: detect UI regressions

---

android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt

Compare size of keyboard in `onApplyWindowInsets` callback.
When you have an opened keyboard and you trigger a navigation from screen A to screen B, then you'll have a race condition between `onApplyWindowInsets` and `onStart`/`onProgress`/`onEnd` callbacks.
For this particular case `onApplyWindowInsets` shouldn't emit events, because in this method I'm simply detecting keyboard resize. With old condition if-statement:
```kt
if (isKeyboardShown && !isMoving && Build.VERSION.SDK_INT >= Build.VERSION_CODES.R)
```
is evaluated as `true` and because of that we're dispatching unnecessary events.
Since this method was designed to detect keyboard layout changes/resizing I thought that it would be good to add additional condition that compares previous and current height. With this fix the race …

fix: compare size in `onApplyWindowInsets`

---

README.md
docs/docs/installation.mdx
docs/versioned_docs/version-1.9.0/installation.mdx

Removed `#` to make installation instructions more explicit.
Commented out code hard to read and notice.
Also added tabs for selection package manager in documentation.
- removed `#` to make installation instructions more explicit in README;
- added npm/yarn tabs.
Tested via preview on `localhost:3000` and github preview.

fix: typo on README.md

---

android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt

Fixed race condition in `onApplyWindowInsets`.
A rare case. I've reproduced it when I used `Microsoft SwiftKey Keyboard`.
I had a full cycle of `onStart`/`onProgress`/`onEnd` events (keyboard height was 283). And then two events were dispatched to `onApplyWindowInsets` (changing height to 213 and then to 283).
With a previous implementation we were running an animation from 283 -> 213 and in parallel from 213 to 283. As a result an animated view was jumpy.
With new implementation we're cancelling our previous animations, so we have monotonic values.
- added `onKeyboardResized` method (copied part of body of `onApplyWindowInsets`);
- save current `ValueAnimator` when animation starts;
- clean (set to `null`) current animation in `doOnEnd`;
- cancel animation if previous one is in progress …

fix: race condition in `onApplyWindowInsets`

---

docs/docs/guides/building-own-hook.md
docs/versioned_docs/version-1.9.0/guides/building-own-hook.md

Currently algolia search returns nothing about `useResizeMode` hook.
This hook is not documented anywhere in the code, so I decided to add a reference why it's needed. I thought that `Building own hook` guide is a perfect place for that.
- add a note about `useResizeMode` hook
Tested on `localhost:3000`.

docs: add a note about `useResizeMode` hook

---

android/src/main/java/com/reactnativekeyboardcontroller/listeners/FocusedInputObserver.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
ios/KeyboardController.xcodeproj/project.pbxproj
ios/observers/FocusedInputObserver.swift
ios/views/KeyboardControllerView.mm
ios/views/KeyboardControllerViewManager.swift

Renamed `FocusedInputLayoutObserver` to `FocusedInputObserver`.
I'm planning to extend library functionality. Soon apart of observing layout of focused input I'll also do other things (such as observing the text that user is typing).
Creating another class is kind of very expensive thing, because the functionality of these two classes will be toughly bound to each other (for example when observing text-value we'll need to sync-up layout - and it's a part of current `FocusedInputLayoutObserver`).
So taking it into consideration I decided to rename `FocusedInputLayoutObserver` class to make it more generic.
- renamed `FocusedInputLayoutObserver.swift` file to `FocusedInputObserver.swift`;
- renamed all references of `FocusedInputLayoutObserver` to `FocusedInputObserver`.
- renamed …

refactor: rename `FocusedInputLayoutObserver` -> `FocusedInputObserver`

---

FabricExample/src/components/AwareScrollView/useSmoothKeyboardHandler.ts
example/src/components/AwareScrollView/useSmoothKeyboardHandler.ts

Use `evt` instead of `animatedKeyboardHeight` before dispatching `onEnd` event in `useSmoothKeyboardHandler` hook.
It turns out, that sometimes this code:
```ts
(evt) => {
if (!evt) {
return;
}
handler.onMove?.(evt);
console.log("reaction", evt, animatedKeyboardHeight.value, persistedHeight.value);
// dispatch `onEnd`
if (animatedKeyboardHeight.value === persistedHeight.value) {
```
is evaluated as:
```
'reaction', { 
duration: 250,
target: 397,
height: 294.95096567560637,
progress: 0.9990274545503124 }, 295.23809814453125, 295.23809814453125
```
It seems like `prepare` and `react` functions can be executed asynchronously and shared value from a closure can have a different value. In this PR I'm using `evt` in comparison statement because it'll have a correct value and correct events will …

fix: race condition in `useSmoothKeyboardHandler`

---

android/build.gradle

Enabled `buildFeatures.buildConfig` for Android Gradle Plugin 8+.
In new react-native version 0.73 FB team switched to AGP 8. For AGP 8+ it's crucial to add `buildConfig true` under `buildFeatures` if you are using `BuildConfig` with custom configuration (this package is using it for distinguishing 2 different architectures - paper and fabric).
I decided to add it under `AGP >= 7` condition because it will not break anything and such condition will be evaluated as `true` for AGP 8.
- added  `buildFeature { buildConfig true }` if AGP is 7+;
Tested manually and via CI builds.

fix: enable `buildFeatures.buildConfig` for AGP 8+

---

.github/workflows/android-e2e-test.yml
.github/workflows/ios-e2e-test.yml

Specify `paths` on `push` for `e2e` tests.
Without these paths we'll run e2e every time on push to main branch. It's not consistent behavior across other CI scripts (and actually there is no sense not to run e2e pipeline on pull_request and run it on push).
So in this PR I'm adding these paths to have a consistent behavior across all CI scripts.
- added `paths` on push for e2e tests (the same as on pull_request);
There is no way to test it 😅

chore: specify paths on push for e2e tests

---

.github/workflows/android-e2e-test.yml
.github/workflows/build-android-fabric.yml
.github/workflows/build-android.yml
.github/workflows/build-ios-fabric.yml
.github/workflows/build-ios.yml
.github/workflows/ios-e2e-test.yml

Migrate off from `set-output`.
This command is deprecated and will be disabled in near future, so it's better to migrate to the variant that will not produce this warning.
- used modern syntax instead of `::set-output`;
- synchronized code between `e2e` actions;
Tested via GH actions.

refactor: migrate off from `set-output`

---

android/src/main/java/com/reactnativekeyboardcontroller/extensions/WindowInsetsAnimationCompat.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt

Check that current animation is a keyboard one. If not, then do not send any events to JS.
Since we add generic `WindowInsetsAnimationCompat.Callback` -> its callbacks (`onStart`/`onProgress`/`onEnd`) can be called even when keyboard is not performing an animation. Thus it's important to filter out which events are keyboard-related and which one are not.
Initially I copied an example from [Google samples](https://github.com/android/platform-samples/tree/main/samples/user-interface/window-insets), but their example code didn't have these checks. I assume it's because they had only one screen and it wasn't possible to run other insets animation.
However in [Android documentation](https://developer.android.com/develop/ui/views/layout/sw-keyboard#synchronize-animation) in code sample they …

fix: ignore non-keyboard animations

---

.github/workflows/build-ios-fabric.yml
.github/workflows/build-ios.yml

Build iOS projects when main .podspec file is changed.
Was discovered in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/304
- added `'react-native-keyboard-controller.podspec'` to `paths`;
Tested on CI.

fix: build iOS projects when main .podspec file is changed

---

.github/workflows/build-ios-fabric.yml
.github/workflows/build-ios.yml
FabricExample/ios/Podfile.lock
example/ios/Podfile.lock
react-native-keyboard-controller.podspec

Updating Pod to add Yoga style to HEADER_SEARCH_PATHS for new architecture
For react native (0.73.X) build failing when new architecture is enabled on iOS.
Fix:  `yoga/style/Style.h` not found  when new arch is enabled on iOS
- `yoga/style/Style.h` header has added to `HEADER_SEARCH_PATHS` on iOS Pods.

fix: react native 0.73.x build failing when new arch is enabled on iOS

---

src/components/KeyboardAvoidingView/hooks.ts
src/components/KeyboardAvoidingView/index.tsx
src/components/KeyboardStickyView/index.tsx
src/components/hooks/useKeyboardInterpolation.ts

Fixed incorrect first frame (when keyboard was resized).
If we use `progress` directly for interpolation we may encounter a situation when animation looks junky.
It happens because first frame is not calculated properly when we interpolate value.
First of all let's define how `progress` value is calculated across platforms when keyboard is resized:
- on iOS it'll be always `1` because keyboard changes size immediately;
- on Android prior to Android 11 we'll have intermediate values;
- on Android 11+ we don't have intermediate values, but to make it more consistent across platforms I added a transition;
So to sum it up: on iOS `progress` is always `1` when keyboard gets resized. On Android it will change the value, and the calculation algorithm looks like: take latest keyboard frame and …

fix: incorrect first frame when keyboard was resized

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/label-sponsors.yml
FabricExample/__tests__/__snapshots__/components-rendering.spec.tsx.snap
FabricExample/__tests__/components-rendering.spec.tsx
FabricExample/__tests__/module-hook.spec.tsx
example/__tests__/__snapshots__/components-rendering.spec.tsx.snap
example/__tests__/components-rendering.spec.tsx
example/__tests__/module-hook.spec.tsx
jest/index.js
src/components/KeyboardAvoidingView/hooks.ts
src/components/KeyboardStickyView/index.tsx
src/components/hooks/useKeyboardInterpolation.ts

Added mocks for exported components, such as `KeyboardAvoidingView`, `KeyboardAwareScrollView`, `KeyboardStickyView`.
The library should support mocks for exported components out of the box.
In an ideal world I'd like to mock dependencies that depends on native implementation and use a real implementation for components. However since we mock entire module (`react-native-keyboard-controller`) it becomes impossible to mock it partially. 
Even with `jest.requireActual()` for components import from `react-native-keyboard-controller` produced `{}` and as a result `useKeyboardHandler` and other native dependencies were undefined and it causes errors during component rendering.
Also a controversial topic was how to mock these components - as `View`/`ScrollView` from RN or as strings. I had at …

fix: missing components mocks

---

ios/views/KeyboardControllerViewManager.swift

Fixed memory leak on iOS in paper architecture.
I used strong references when specified methods as callbacks. I had to use `[weak self]` in order to create a weak reference and object can be deallocated properly.
I also tested Fabric, but when I keep view as simple as possible - view still doesn't call `deinit`.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/317
- added `[weak self]` for callbacks in `KeyboardMovementObserver` and `FocusedInputObserver`;
Tested in XCode.
|Before|After|
|------|------|
|<video src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/4e7bffa8-b226-4948-905d-cd5c8ab01a0f">|<video src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/c29fec82-69ab-43b4-a87a-d3cf2fae493 …

fix: memory leak on iOS

---

ios/observers/FocusedInputObserver.swift

Set `currentInput` to `nil` to fix a memory leak.
If we store a reference as `currentInput = UIResponder.current`, then even if view is removed from the screen the view will not be deallocated (because we have a strong reference) and it'll be kind of memory leak (because view should be deallocated and free up a memory).
To fix this problem we need to remove a reference so ARC (automatic reference counter) will work properly and will deallocate view.
Actually it's not a very big problem, because users are switching between inputs frequently (and we overwrite a reference every time) so we have kind of have a constant memory allocation and it is not growing over time. Also we don't interact with this input anymore (don't call `becomeFirstResponder` and other methods), so it's kind of "safe". …

fix: set `currentInput` to `nil` to fix a memory leak

---

src/components/KeyboardAwareScrollView/index.tsx

Synchronized bottom padding with keyboard frame in `KeyboardAwareScrollView`.
Original regression was introduced in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/257 ([these](https://github.com/kirillzyusko/react-native-keyboard-controller/pull/257/files#diff-b4493213c8dc470b5ba251af896d133130cc8996cee1118525e4eba1f3aa993bL87-L88) code lines). I decided not animated bottom padding to potentially fix the issue described in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/255#issuecomment-1751177540
However such approach is causing unsynchronized animations in certain conditions and I'm not sure, that it actually fixes the problem described in comment above.
So in this PR I'm reworking it again and bringing back animated transitions 👀 
Closes …

fix: synchronize bottom padding with keyboard frame in `KeyboardAwareScrollView`

---

src/components/KeyboardAwareScrollView/index.tsx

Fire `onScroll` from props in `KeyboardAwareScrollView`.
Initially I wanted to achieve that as `runOnJS(props.onScroll)({ nativeEvent: e })`. But in this case I'm getting:
```bash
Argument of type '{ nativeEvent: ReanimatedScrollEvent; }' is not assignable to parameter of type 'NativeSyntheticEvent<NativeScrollEvent>'.
Type '{ nativeEvent: ReanimatedScrollEvent; }' is missing the following properties from type 'NativeSyntheticEvent<NativeScrollEvent>': currentTarget, target, bubbles, cancelable, and 10 more.ts(2345)
```
And it's really incorrect, because several properties will be missing and js-based handler (not based on `Animated.event`) may not read expected properties (such as `target` etc.).
So I wanted to pass `onScroll` handler from reanimated as `onScrollReanimated` property. In …

fix: fire `onScroll` from props in `KeyboardAwareScrollView`

---

src/components/KeyboardAwareScrollView/index.tsx
src/components/KeyboardAwareScrollView/useSmoothKeyboardHandler.ts

Improved FPS for `KeyboardAwareScrollView` when keyboard gets closed (and scroll position is the end of the scroll view).
The fix consist of several stages. Below they are:
When we reset `persistentHeight` in `onEnd` we:
- produce potential race condition (`persistentHeight` can be set to `0` after timing animation completion and because of that `onEnd` handler may not be fired at all)
- calculate `progress` incorrectly (it can be `Infinity` or `NaN` in last frames of animation
If we reset `persistentHeight` to `0` in `useAnimatedReaction` (where we dispatch `onEnd`) -> we run animation effect again, and it may produce additional `onMove`/`onEnd` events after `onEnd` event. So I added `if (persistentHeight.value === 0)` check.
When we scroll to the end of ScrollView and change padding, it …

fix: slow back transitions on Android < 11 in `KeyboardAwareScrollView`

---

src/components/KeyboardAwareScrollView/index.tsx

Right now it's impossible to assign `ref` on `KeyboardAwareScrollView` and access `ScrollView` methods. This PR fixes this problem.
It's important to have `ref` in many cases - so I think motivation why it's needed is pretty clear 😅 
The technical aspect is a little bit tricky, since internally we also use `ref` (from REA hook) and we need to propagate it from inside the component. To achieve this I added `onRef` callback that manages everything 😎  It uses single ref and derives a reanimated ref + assigns plain `ref` for typical RN usage.
This PR has a lot of changes, but it's because of prettier. Main changes are `onRef` + `forwardRef` component wrap.
- `forwardRef` on `KeyboardAwareScrollView`;
- manage (clone) refs inside `KeyboardAwareScrollView` for reanimated usage + assign it to …

fix: forward ref to `KeyboardAwareScrollView`

---

.github/workflows/android-e2e-test.yml
android/src/main/java/com/reactnativekeyboardcontroller/interactive/InteractiveKeyboardProvider.kt
android/src/main/java/com/reactnativekeyboardcontroller/interactive/KeyboardAnimationController.kt
android/src/main/java/com/reactnativekeyboardcontroller/interactive/interpolators/Interpolator.kt
android/src/main/java/com/reactnativekeyboardcontroller/interactive/interpolators/IosInterpolator.kt
android/src/main/java/com/reactnativekeyboardcontroller/interactive/interpolators/LinearInterpolator.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/KeyboardGestureAreaReactViewGroup.kt

Move all interactive keyboard code to dedicated `interactive` folder/package in kotlin/Android.
Ideally in root android folder I'd like to keep a single `package` file and all other code should be placed in folders.
Initially I created generic purpose folders, like `events`/`listeners`/`views` etc. However sometimes it may be hard to create generic purpose folders for specific files. Theoretically I could create folders `controllers`/`providers`, but they would contain only single files.
So I took an inspiration from https://github.com/kirillzyusko/react-native-keyboard-controller/pull/346 PR, where I created `traversal` folder for keeping functionality related to view traversal/keyboard toolbar. And in this PR I moved all interactive-keyboard related code into `interactive` folder - it …

refactor: move all interactive keyboard code to dedicated `interactive` folder (Android)

---

ios/views/KeyboardControllerView.mm

Use library name as prefix and absolute import if static frameworks are enabled.
I added conditional imports with `__has_include` check. When static frameworks are enabled we have to specify a prefix which is equivalent of library name. For more information you can see answer here: https://stackoverflow.com/a/47106911/9272042
So this import:
```objc
#import "react_native_keyboard_controller-Swift.h"
```
gets transformed into this one
```objc
#if __has_include("react_native_keyboard_controller-Swift.h")
#import "react_native_keyboard_controller-Swift.h"
#else
#import <react_native_keyboard_controller/react_native_keyboard_controller-Swift.h>
#endif
```
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/354
- use conditional import;
Tested manually in …

fix: use conditional import for supporting frameworks

---

docs/docs/guides/interactive-keyboard.mdx
docs/versioned_docs/version-1.10.0/guides/interactive-keyboard.mdx
docs/versioned_docs/version-1.5.0/guides/interactive-keyboard.mdx
docs/versioned_docs/version-1.6.0/guides/interactive-keyboard.mdx
docs/versioned_docs/version-1.7.0/guides/interactive-keyboard.mdx
docs/versioned_docs/version-1.8.0/guides/interactive-keyboard.mdx
docs/versioned_docs/version-1.9.0/guides/interactive-keyboard.mdx

Added "Interactive keyboard" lottie animation from main page to "Interactive keyboard" guide.
It's easier to see how it works in action and what we're trying to achieve before reading a lot of text 😊 
- added lottie animation to interactive keyboard guide
Tested on `localhost:3000`

docs: added lottie animation to interactive keyboard guide

---

ios/observers/FocusedInputObserver.swift
ios/observers/KeyboardMovementObserver.swift

Do not use force casting in swift - replaced with optional casting and guard statements.
In sentry one of library user seen this:
```bash
Thread 0 - (TH_STATE_WAITING)
0  Trusted +0x5746c0        Swift runtime failure: Unexpectedly found nil while unwrapping an Optional value (KeyboardMovementObserver.swift:109:65)
1  Trusted +0x5705cc        KeyboardMovementObserver.observeValue(forKeyPath:of:change:context:) (<compiler-generated>)
2  Foundation +0x99e54      _NSKeyValueNotifyObserver
3  Foundation +0x99cf0      _NSKeyValueDidChange
4  Foundation +0x99b20      -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:]
5  Foundation +0x99850      -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:]
6 …
```

fix: do not force cast KVO values

---

FabricExample/__tests__/focused-input.spec.tsx
FabricExample/src/screens/Examples/AwareScrollViewStickyFooter/index.tsx
FabricExample/src/screens/Examples/AwareScrollViewStickyFooter/styles.ts
android/src/main/java/com/reactnativekeyboardcontroller/events/FocusedInputLayoutChangedEvent.kt
android/src/main/java/com/reactnativekeyboardcontroller/extensions/EditText.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/FocusedInputObserver.kt
docs/docs/api/hooks/input/use-reanimated-focused-input.md
example/__tests__/focused-input.spec.tsx
example/src/screens/Examples/AwareScrollViewStickyFooter/index.tsx
example/src/screens/Examples/AwareScrollViewStickyFooter/styles.ts
ios/Extensions.swift
ios/events/FocusedInputLayoutChangedEvent.m
ios/observers/FocusedInputObserver.swift
ios/views/KeyboardControllerView.mm
jest/index.js
src/components/KeyboardAwareScrollView/index.tsx
src/specs/KeyboardControllerViewNativeComponent.ts
src/types.ts

Added `parentScrollViewTarget` filed to `useReanimatedFocusedInput`.
The motivation behind this field is described in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/336
Here I'd like to focus on implementation details. The implementation is quite straighforward - we add new field to types/specs/events and we're ready to go. And this is true, but I'd like to give some implementation details:
- all search of ScrollView parent I moved to extension (added new property `parentScrollViewTarget` on iOS/Android to focused input);
- on iOS I need to check whether new arch is enabled (the same as in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/191) to get correct tag of the view;
Also this PR optimizes performance in case if you have a lot of …

feat: `parentScrollViewTarget` detection

---

src/components/KeyboardToolbar/Arrow.tsx
src/components/KeyboardToolbar/Button.tsx
src/components/KeyboardToolbar/colors.native.ts
src/components/KeyboardToolbar/colors.ts
src/components/KeyboardToolbar/index.tsx
src/components/KeyboardToolbar/types.ts

Fixed a crash on web.
It was a regression since `1.10.0` version. `PlatformColor` is not available on `web` and it will throw exception, because `KeyboardToolbar` is exported from `index` file and will be evaluated as soon as something gets imported from the package (i. e. `KeyboardProvider`).
To fix the problem I created two files: `colors.ts` (all platforms excluding mobile) and `colors.native.ts` (for mobile).
- created two files: `colors.ts` (all platforms excluding mobile) and `colors.native.ts` (for mobile)
- moved types to common `types` file;
- restructed imports to look into `types` file instead `colors`;
Tested on web project.

fix: crash on web

---

android/src/main/java/com/reactnativekeyboardcontroller/extensions/EditText.kt
android/src/main/java/com/reactnativekeyboardcontroller/modules/KeyboardControllerModuleImpl.kt
android/src/main/java/com/reactnativekeyboardcontroller/traversal/FocusedInputHolder.kt
android/src/main/java/com/reactnativekeyboardcontroller/traversal/ViewHierarchyNavigator.kt
android/src/test/java/com/reactnativekeyboardcontroller/traversal/FocusedInputHolderTest.kt
android/src/test/java/com/reactnativekeyboardcontroller/traversal/ViewHierarchyNavigatorTest.kt
ios/traversal/FocusedInputHolder.swift
ios/traversal/TextInput.swift
ios/traversal/ViewHierarchyNavigator.swift

Added tests to `FocusedInputHolder`. Refactored code, reduced duplications, aligned to JS-based namings.
I decided to fully cover a new functionality with unit tests. The `ViewHierarchyTraversal` was already covered, so I decided to cover other classes. The next one `FocusedInputHolder`. This is a very simple class, so it contains two unit tests:
- check that weak references implemented correctly;
- check that `focus` actually calls expected methods.
Along with that I did some refactoring: reduced code fragmentation, reduced code duplication, aligned API to look similar to RN JS API (and hide internals).
- use `focus` instead of `requestFocus`;
- `FocusedInputHolder.shared.requestFocus()` -> `FocusedInputHolder.shared.focus()`;
- added `FocusedInputHolderTests`
- added `focus` extension …

tests: FocusedInputHolder (Android)

---

FabricExample/Gemfile
FabricExample/ios/KeyboardControllerFabricExample.xcodeproj/project.pbxproj
FabricExample/ios/Podfile.lock
FabricExample/package.json
FabricExample/yarn.lock
example/Gemfile
example/ios/KeyboardControllerExample.xcodeproj/project.pbxproj
example/ios/Podfile.lock
example/package.json
example/yarn.lock
package.json
react-native-keyboard-controller.podspec
yarn.lock

Started to use `install_modules_dependencies` in `.podspec`.
It's vital to use `install_modules_dependencies` because it simplifies integration process (this function is shipped in RN, so RN team cares about internal deps that could be provided to the project).
So it means that we don't need to specify it manually anymore and instead we can rely on the implementation provided by the package.
However we need to keep in mind, that this function is available only from RN 0.71, so if we support RN < 0.71 we need to have fallback code.
The other aspect that was discovered during the implementation is the fact that this function was broken on RN 0.72 + Swift + New Arch combination, but with latest RN release it's not broken anymore (that's the reason why I updated a RN dependency in this PR - …

fix: use `install_modules_dependencies` to fix compilation issues on RN 0.73 with Fabric

---

.gitignore
src/components/index.ts
src/index.ts
src/monkey-patch.android.ts

Fixed build issues when using `@rnx-kit`.
When using tools like @rnx-kit from microsoft, which uses esbuild to handle bundling and also enables treeShaking, the build fails
- instead of direct export of type Ex: export { KeyboardToolbarProps } we export using "type": export { type KeyboardToolbarProps }

fix: android build fail with rnx kit & treeShaking enabled

---

src/components/KeyboardAwareScrollView/index.tsx

Do not use `target` property from `onLayout`.
In continuation of https://github.com/facebook/react-native/pull/42785 it seems like `target` property is not documented and thus can be removed at any point of time so it's simply not reliable to use it since the code can be easily broken in newest RN versions.
So in this PR I started to use `findNodeHandle` and pass a `ref` to get a view target. Initially I thought that it'll throw a warning in strict mode, but it looks like this method will throw a warning only if `findNodeHandle(component)` statement is used. And since I'm passing a `ref` - it's safe to use such code.
Also I'm still getting `target` property in `onLayout`. Maybe more optimized version would be to derive a `target` property in `onRef` handler, but it's further …

fix: do not use `target` property from `onLayout`

---

docs/docs/api/components/keyboard-toolbar/index.mdx
docs/versioned_docs/version-1.11.0/api/components/keyboard-toolbar/index.mdx
src/components/KeyboardToolbar/index.tsx

Added `showArrows` property.
Sometimes we just want to hide buttons. With current API we have to override button component (and it's actually very complex process and it's not reasonable to create such complex solution for such simple purpose).
So in this PR I added `showArrows` property. It doesn't change current behavior of the component, but gives an ability to hide these arrows 🙂 
- added a note about `showArrows` property;
- added new `showArrows` property;
Tested manually on iPhone 15 Pro (iOS 17.2).

feat: `showArrows` property

---

ios/KeyboardController.xcodeproj/project.pbxproj
ios/observers/KeyboardMovementObserver.swift
ios/traversal/KeyboardView.swift

Moved `findKeyboardView` in separate file.
`KeyboardMovementObserver` is already pretty big file (250+ lines of the code). When we add new code then we get a lint warning telling, that files shouldn't be bigger than 250 lines of the code (excluding comments).
So in this PR I'm moving `findKeyboardView` function into separate file - this is a pure function with a clearly defined functionality, so it's an ideal candidate for splitting the code.
Initially I wanted to add it as extensions, but since we already have `traversal` folder - I decided to put it there, because in order to find a `keyboardView` we need to traverse through windows 🙂 
- added new `KeyboardView` file in `traversal` folder;
- moved `findKeyboardView` function as static function of `KeyboardView` class;
- removed …

refactor: move `findKeyboardView` in separate file

---

src/components/KeyboardAvoidingView/index.tsx

Update `initialFrame` on first render.
The problem with the old condition is the case when screen that uses `KeyboardAvoidingView` is pushed/gets mounted and the keyboard is already in open state. In this case we don't update `initialFrame` (because we update it only when `onLayout` is fired and keyboard is closed - to avoid concurrent re-calculations) and it remains always `null`. As a result `relativeKeyboardHeight` returns `0` and we interpolate from `[0, 1]` to `[0, 0]`, so our `padding` will be always `0`.
In this PR I'm fixing this problem by adding `initialFrame.value === null` condition. Such check will be executed only on initial mount. And since `relativeKeyboardHeight` returns `0` when `initialFrame.value === null` -> we will not have concurrent calculations that can interfere …

fix: `KeyboardAvoidingView` is not reacting on keyboard movements if was mounted when keyboard is open

---

FabricExample/src/screens/Examples/ReanimatedChat/hooks.ts
example/src/screens/Examples/ReanimatedChat/hooks.ts
src/animated.tsx

Avoid deep worletization of `react-native` package.
It looks like in specific project setup babel plugin may try to serialize entire `react-native` package (see https://github.com/kirillzyusko/react-native-keyboard-controller/issues/393 for more context).
To avoid that in this PR I'm extracting `Platform.OS` into separate `OS` variable, so that babel plugin will capture only value of `OS` (and not entire `Platform` object).
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/393 and https://github.com/kirillzyusko/react-native-keyboard-controller/issues/294 
- extract `Platform.OS` into separate `OS` variable
Tested in the project where this error occurs.

fix: avoid deep workletization

---

src/components/KeyboardAvoidingView/hooks.ts

Consume context values (as default values).
When we navigate between screens, sometimes there can be a situation, where keyboard is not moving. If we initialize values as a default one - we'll have incorrect layout, because keyboard is actually shown (and wasn't moved) so we will continue to use default values (keyboard closed) while keyboard is actually open.
To fix this problem I specify default values from the context - context always holds a current values. It fixes the problem 🙂 
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/398
- consume context values as a default one
Tested on Android 10.
|Before|After|
|-------|----|
|<img width="346" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/a28befcd-c52b-4db …

fix: consume context values as a default one

---

.prettierignore
src/components/KeyboardAwareScrollView/index.tsx
tea.yaml

Fixed firing of `onScroll` in `KeyboardAwareScrollView`
Initially it was fixed in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/339 and I'm sure it was working 😅 
However it looks like in current setup (RN 0.73, REA 3.8.0) such way is not working and `onScroll` property still gets ignored 😔
So in this PR I followed a different path: initially I wanted to fire this handler via `runOnJS`, but we can not follow a full signature of the method, since REA has only `nativeEvent` property (and indeed in this case some properties would be simply missing).
The different path was to update a shared value from JS thread and call a callback as usually - it fixes a problem in old code and in a new, so for now this approach looks decent 👍
Let's see how it works in a wild life 👀 …

fix: missing `onScroll` event in `KeyboardAwareScrollView`

---

.github/workflows/size-diff.yml
scripts/size.js

Fixed "0 bytes" diff from size-diff job report.
It was incorrect metric. Such metric is totally useless.
The original problem was the fact that in new node `18.20.1` prints output gathered from `react-native-builder-bob`:
```bash
> react-native-keyboard-controller@1.11.6 prepare
> bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 32 files in src with babel
✔ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 32 files in src with babel
✔ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
```
And such output can not be parsed.
The interesting thing is that `18.19.0` version produced expected result. So …

fix: size diff job

---

src/components/KeyboardAwareScrollView/index.tsx

React on `enabled` property toggle when keyboard open in `KeyboardAwareScrollView` component.
Initially me and @IvanIhnatsiuk were thinking that in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/350 it will be better to not handle keyboard appearance if `enabled=false`. But it turns out that it will produce issues like https://github.com/kirillzyusko/react-native-keyboard-controller/issues/414
So in this PR I'm always keeping a handler in `useKeyboardHandler` hook and instead I don't render additional padding if view is disabled (we are not making any scrolling because we already handle `enabled` property value in `maybeScroll`).
Fixes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/414
- don't put keyboard handlers conditionally;
- make …

fix: react on `enabled` property toggle when keyboard open (`KeyboardAwareScrollView`)

---

FabricExample/ios/Podfile.lock
android/src/main/java/com/reactnativekeyboardcontroller/events/FocusedInputLayoutChangedEvent.kt
android/src/main/java/com/reactnativekeyboardcontroller/events/FocusedInputTextChangedEvent.kt
example/ios/Podfile.lock
package.json

Version 1.11.7
Also in this PR I fixed incorrect event in generic params on Android.
Most likely last release for 1.11.x version.

chore: release 1.11.7

---

docs/__tests__/screenshot.css
docs/blog/2022-09-22-fabric/index.md
docs/docusaurus.config.js
package.json

Added `avoid keyboard` to keywords + updated SEO keywords.
When I do search for `avoid keyboard react native` on `npm` the `react-native-keyboard-controller` is not showing up in the search results:
So this PR fixes this 🙃 
- added `avoid keyboard` to `keywords` in `package.json`;
- updated SEO keywords;
- fixed flaky e2e test (exclude a picture from blogpost);
There is no way to test these changes - can be verified only after merge + publishing.
🤷‍♂️

docs: add `avoid keyboard` keyword, update SEO keywords, fix flaky docs e2e tests

---

src/components/KeyboardAvoidingView/index.tsx
src/components/KeyboardAwareScrollView/index.tsx
src/components/KeyboardStickyView/index.tsx
src/components/index.ts
src/index.ts

Exported props for all components, including:
- `KeyboardAvoidingView`;
- `KeyboardStcikyView`;
- `KeyboardAwareScrollView`;
- `KeyboardToolbar`.
Sometimes people need to wrap components into additional methods (for example `createBottomSheetScrollableComponent`) and it requires to know which props component is consuming.
Before devs had to copy/paste the props, but this is not a good from code duplication and consistency perspective.
So in this PR I'm exporting props for remaining components (`KeyboardToolbarProps` were already exported).
- export props for `KeyboardAvoidingView`;
- export props for `KeyboardStickyView`;
- export props for `KeyboardAwareScrollView`;
Tested via CI 😁

fix: export component props

---

FabricExample/ios/Podfile.lock
FabricExample/package.json
FabricExample/src/screens/Examples/Toolbar/index.tsx
FabricExample/yarn.lock
docs/docs/api/components/keyboard-toolbar/index.mdx
example/ios/Podfile.lock
example/package.json
example/src/screens/Examples/Toolbar/index.tsx
example/yarn.lock
src/components/KeyboardToolbar/index.tsx

Added `onDoneCallback`/`onNextCallback`/`onPrevCallback` functions to `KeyboardToolbar`.
It's often needed to customize behavior when buttons are pressed, for example do a haptic feedback or even play a sound.
Before this PR it wasn't possible to add an action that will be called whenever user presses a particular button along with the default action. But in this PR I added it.
Initially I wanted to provide `onNextPress` functions that would redefine an entire handler. But in this case users will have to go into source code and understand how `KeyboardToolbar` works under the hood. Even though it's not difficult it's better to keep such things internally (and in most cases users will rely on defult behavior - in case if we need to re-define a behavior I'll add new functions later).
- …

feat: `KeyboardToolbar` callbacks

---

ios/core/KeyboardAnimation.swift
ios/core/SpringAnimation.swift
ios/observers/KeyboardMovementObserver.swift

Added `KeyboardAnimation` class (as common interface) which drives an animation of the keyboard.
Follow up for https://github.com/kirillzyusko/react-native-keyboard-controller/pull/412
Keyboard animation can be driven not only by `CASpringAnimation` class. What we want to achieve is to have a **single interface** that gives us all necessary properties (value for a particular timing, etc.), but will incapsulate calculations of these values internally.
So in this PR I added `KeyboardAnimation` abstract class that uses some common properties for all animations (from/to value, speed, init time), has universal method for finding a particular timing for a given value (since we use a binary search) and defines other publicly available functions.
And in this PR I also started to use this …

refactor: use `KeyboardAnimation` as common interface for an animation driver

---

FabricExample/src/components/KeyboardAnimation/index.tsx
FabricExample/src/constants/screenNames.ts
FabricExample/src/navigation/ExamplesStack/index.tsx
FabricExample/src/screens/Examples/Main/constants.ts
FabricExample/src/screens/Examples/Modal/index.tsx
example/src/components/KeyboardAnimation/index.tsx
example/src/constants/screenNames.ts
example/src/navigation/ExamplesStack/index.tsx
example/src/screens/Examples/Main/constants.ts
example/src/screens/Examples/Modal/index.tsx

Added an example with `Modal` usage.
Right now `Modal` usage will lead to default behavior on Android (i. e. window is automatically resized + keyboard movement is not tracked).
I'm planning to fix it later, but right now I just want to have a reproducible demo in example app (I used similar approach when fixed a native-stack integration).
- added an example with modal usage;
Tested on iPhone 15 Pro and Pixel 3a.

feat: modal example

---

android/src/main/java/com/reactnativekeyboardcontroller/extensions/EditText.kt

Use `dp` for selection events.
If we pass values directly, then we will have incorrect positioning, because we are passing `px` while RN relies on `dp`. So in this PR we are converting all selection coordinates in `dp` and only then pass them.
- convert all selection coordinates to `dp`;
Tested manually on Pixel 3a (API 33, emulator).
|Before|After|
|<img width="436" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/de8890e6-ee18-4104-bb50-2c36c4be0d96">|<img width="432" alt="image" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/65f6ebd6-444b-4fde-beba-119bfdd3ede6">|
> Pay an attention to `x` coordinates 👀

fix: use `dp` for selection events

---

ios/observers/FocusedInputObserver.swift

Prevent crash when no first responder in `keyboardWillShow`.
It happens because we can not find first responder when `keyboardWillShow` is triggerred:
Then we get NPE here (read `absoluteY` of `nil`):
And finally app crashes:
To fix this problem I've decided to add `guard` statement - there is no sense to execute code further if we don't have a reference to `TextInput` - no sense to store it in holder, no sense to add listeners/observers, substitute delegates etc.
- check that first responder is actually present before executing the code that relies on its presence;
Tested manually on iPhone 15.
https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/83ecde49-69de-483e-8403-92c4dd41c4c7

fix: prevent crash when no first responder

---

cspell.json
docs/docs/api/components/keyboard-aware-scroll-view.mdx
docs/versioned_docs/version-1.12.0/api/components/keyboard-aware-scroll-view.mdx

Added docs explaining how to integrate `KeyboardAwareScrollView` and `@gorhom/bottom-sheet`.
It may be no very obvious that you'll need to wrap it in additional HOCs.
Inspired by https://github.com/kirillzyusko/react-native-keyboard-controller/discussions/309#discussioncomment-9215288
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/343
- added a section about integration `KeyboardAwareScrollView` with `@gorhom/bottom-sheet`;
Tested via preview and `localhost:3000`.

docs: integration with `@gorhom/bottom-sheet`

---

ios/Extensions.swift

Improved conditions for detecting horizontal `ScrollView` on iOS.
If we compare `height` properties, then we may have a false positive case if `ScrollView` is not big enough and can not be actually scrolled because of its small size:
To fix the problem I decided to compare `width` property to properly detect horizontal `ScrollView`.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/453
- compare `width` property to detect horizontal `ScrollView`s;
Tested manually on iPhone 15 Pro (iOS 17.4).
https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/fde50481-b481-47ab-b23e-7417740ebed8

fix: better horizontal `UIScrollView` detection

---

ios/delegates/KCTextInputCompositeDelegate.swift

Fixed iOS 13 compatibility.
For projects that are targeting iOS 12.4 (for example react-native 0.72) `textFieldDidChangeSelection` method doesn't exist for `UITextFieldDelegate`.
To fix it I added `@available` annotation that takes the method into compilation only for `iOS 13+`.
Technically it's not very correct solution, because `onSelectionChange` will not be fired from my handler on iOS 12 - if we want to have this event we have to capture events from setter and forward it, but without subclassing it's pretty hard to achieve (only method swizzling as a last resort). But I don't want to spend too much time right now - if I get request that this functionality must be implemented for iOS 12, then I'll add it (otherwise I don't see a lot of sense in that right now, because RN already …

fix: iOS 13 compilation issues

---

docs/docs/api/components/keyboard-aware-scroll-view.mdx
docs/versioned_docs/version-1.10.0/api/components/keyboard-aware-scroll-view.mdx
docs/versioned_docs/version-1.11.0/api/components/keyboard-aware-scroll-view.mdx
docs/versioned_docs/version-1.12.0/api/components/keyboard-aware-scroll-view.mdx

Added tips and info badges to `KeyboardAwareScrollView`.
To simplify search and migration.
- added reference to original props names;
- added a tip when to use `extraKeyboardSpace`
Tested locally and on CI.

docs: added tips and info badges for `KeyboardAwareScrollView` page

---

example/src/screens/Examples/AwareScrollView/index.tsx
example/src/screens/Examples/AwareScrollView/styles.ts
example/src/utils/index.ts
src/components/KeyboardAwareScrollView/index.tsx
src/components/KeyboardAwareScrollView/utils.ts

When dealing with Scrollviews that are snapping to a specific point, if the keyboard is creating a scroll, we in some cases want the scrollview to scroll to at least the first snapToOffsets
It fixes layouts being stuck between 2 states, please see the following issue for more info: https://github.com/kirillzyusko/react-native-keyboard-controller/issues/450
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/450
- Added `clampLower` utility function
- Use this `clampLower` function to ensure a minimum scroll to the first snapToOffset if any
Tested really briefly, going to point my own project to this PR for further testing
To be added

feat: scroll to at least the first snapToOffset value if any

---

FabricExample/src/screens/Examples/AwareScrollView/index.tsx
FabricExample/src/screens/Examples/AwareScrollView/styles.ts
docs/docs/api/components/keyboard-aware-scroll-view.mdx
docs/versioned_docs/version-1.12.0/api/components/keyboard-aware-scroll-view.mdx
example/src/screens/Examples/AwareScrollView/index.tsx
src/__tests__/index.test.tsx
src/components/KeyboardAwareScrollView/__tests__/scrollDistanceWithRespectToSnapPoints.spec.ts
src/components/KeyboardAwareScrollView/index.tsx
src/components/KeyboardAwareScrollView/utils.ts

Fixed corner cases for `scrollOutput` function, added tests, updated docs and example apps.
This is a slight revision of https://github.com/kirillzyusko/react-native-keyboard-controller/pull/452
In this PR I fixed some bugs, unified some functions, updated docs, etc.
- fixed an issue with returning absolute value from `scrollOutput` from `snapPoints`;
- renamed `scrollOutput` -> `scrollDistanceWithRespectToSnapPoints`;
- refactored function `scrollDistanceWithRespectToSnapPoints` to make less computations in cycle and make a signature of function simpler (now this function always returns absolute scroll position);
- added unit-tests;
- ported example to FabricExample;
- added info about `snapToOffsets` and how `KeyboardAwareScrollView` handles that;
Tested locally on iPhone 15 Pro.
Tested …

fix: snap points scroll calculations

---

docs/docs/api/keyboard-controller.md
docs/versioned_docs/version-1.10.0/api/keyboard-controller.md
docs/versioned_docs/version-1.11.0/api/keyboard-controller.md
docs/versioned_docs/version-1.12.0/api/keyboard-controller.md

Added `softwareKeyboardLayoutMode` word to documentation.
People are searching this keyword:
But turns out that it's an expo specific word (though functionality to control that property is present in this library).
So in this PR I updated some pages where `windowSoftInputMode` occurs and added corresponding Expo wording to make people aware about that + improve searching experience.
- added `softwareKeyboardLayoutMode` mention;
Tested on localhost + preview.

docs: mention `softwareKeyboardLayoutMode` in docs

---

android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt

Keyboard size is incorrectly reported if we draw behind navigation status bar (i. e. it's translucent). This PR fixes this by omitting the `-navigationBarHeight` if `navigationBar` is translucent.
It's incorrect behavior in the core of the library and should be fixed 👀 
Originally discussed in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/259#issuecomment-1848966075
Maybe there is better solution which don't directly depends on `navigationBarTrasnlucent` property, but to fix this bug right now let's use this code. Later on we can always improve/refactor the code.
- added `hasTranslucentNavigationBar` to `KeyboardAnimationCallback`;
- conditionally subtract `navigationBar` insets;
Tested manually on Pixel 7 Pro and on CI (via e2e tests).
Tested on Pixel 7 Pro …

fix: missing `navigationBar` height in keyboard size if `navigationBar` is `translucent`

---

TODO
android/src/main/java/com/reactnativekeyboardcontroller/extensions/ThemedReactContext.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/WindowDimensionListener.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
jest/index.js
src/bindings.native.ts
src/bindings.ts
src/components/KeyboardAvoidingView/index.tsx
src/components/KeyboardAwareScrollView/index.tsx
src/hooks/index.ts
src/hooks/useWindowDimensions/index.android.ts
src/hooks/useWindowDimensions/index.ts
src/types.ts

Implemented own `useWindowDimensions` hook for Android.
The problem with default implementation of `useWindowDimensions` on Android is that it doesn't work well with `edge-to-edge` mode and you can not retrieve an actual size of the screen. Here is a brief comparison of values captured on my device (Pixel 7 Pro).
Translucent `StatusBar`:
```sh
height: 867.4285888671875 <- own hook
height: 867.4285888671875, y: 0 <- useSafeAreaFrame
height: 891.4285714285714 <- Dimensions.get('screen')
height: 826.2857142857143 <- Dimensions.get('window')
```
Non translucent `StatusBar`:
```sh
height: 867.4285888671875 <- own hook
height: 826.2857055664062, y: 41.14285659790039 <- useSafeAreaFrame
height: 891.4285714285714 <- Dimensions.get('screen')
height: 826.2857142857143 <- Dimensions.get('window') …
```

feat: own `useWindowDimensions` hook

---

.github/workflows/build-ios-fabric.yml
.github/workflows/build-ios.yml
.github/workflows/ios-e2e-test.yml
.github/workflows/verify-ios.yml
e2e/.detoxrc.js
ios/KeyboardControllerNative/KeyboardControllerNativeUITests/KeyboardControllerNativeUITestsLaunchTests.swift

Pinned iOS to 17.5 and XCode to latest stable 15.4 for all iOS jobs.
Recently GH updated images and now iOS e2e tests are running on iOS 18. iOS 18 is incompatible with current Detox (`typeText` crashes the app).
So in this PR I decided to lock everything to the same versions that I'm using locally (i. e. XCode 15.4 and iOS 17.5).
- pin iOS simulator to iOS 17.5 to pass job on CI.
- pin XCode version to 15.4;
Verified that CI is green.

chore: pin iOS/XCode versions to a local env

---

ios/traversal/KeyboardView.swift

Ignore non visible keyboard in `KeyboardView.find()` method.
Sometimes we may have two keyboards:
And the current algorithm for a search returns an invalid keyboard (not a one that is actually shown on the screen):
or
But when actual keyboard is tracked, then the frame of this keyboard has non-zero height:
So to fix the problem with invalid keyboard view being found I decided to modify a condition and add additional condition to check that `frame.height != 0`.
Follow up for https://github.com/kirillzyusko/react-native-keyboard-controller/pull/471 and https://github.com/kirillzyusko/react-native-keyboard-controller/issues/338#issuecomment-2163904827
- ignore keyboard view if its `height == 0`;
Tested on CI (e2e tests).

fix: ignore non-visible keyboard

---

android/src/main/java/com/reactnativekeyboardcontroller/extensions/ThemedReactContext.kt

Fixed compilation errors on RN 0.71 and `keyboard-controller` 1.12.
`emitDeviceEvent` is available only in RN 0.72 and we don't want to support RN 0.72 as the minimal version (because it's still quite new):
The original change was introduced in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/410 - it was needed because old implementation threw errors (crashes) in bridgeless mode on Fabric.
In this Pr I made it compatible with bridgeless + it doesn't use newly introduced methods, so it should have a support until RN 0.65 again.
- don't use `emitDeviceEvent` as it's available only in RN 0.72;
- revert to previous code variant, but send an event from `ReactApplicationContext` class instance;
Tested on Pixel 7 Pro (Android 14), Fabric + RN 0.74

fix: don't throw compilation errors for `emitEvent` function for RN < 0.72

---

FabricExample/src/screens/Examples/AwareScrollView/index.tsx
example/src/screens/Examples/AwareScrollView/index.tsx
src/components/KeyboardAwareScrollView/useSmoothKeyboardHandler.ts

Fixed random `KeyboardAwareScrollView` scrolls when user types a message on Android < 11.
The problem happens when you update a state/props and `KeyboardAwareScrollView` gets re-rendered. In this case `handler` object gets re-created and `useAnimatedReaction` produce a new `onMove`/`onEnd` events.
Since we didn't call `onStart` -> we have out-of-date variables and because of that scroll happens to undesired position. The fix should be simple - `onMove` shouldn't be fired. So to fix that I changed `[handler] -> deps` (actually handler will be rebuild and new version will be used only when deps were updated -> otherwise new handler will not be used - this is how `useKeyboardHandler` hook works).
Additionally I cast `deps` to `unknown` to avoid types mismatches between `REA` and `React`. …

fix: random scrolls of `KeyboardAwareScrollView` during re-render (when keyboard is open)

---

android/src/main/java/com/reactnativekeyboardcontroller/extensions/ThemedReactContext.kt

Fixed compilation error:
```bash
> Task :compileReleaseKotlin FAILED
e: file:///Users/kirylziusko/IdeaProjects/react-native-keyboard-controller/android/src/main/java/com/reactnativekeyboardcontroller/extensions/ThemedReactContext.kt:28:51 Type mismatch: inferred type is ThemedReactContext? but ReactContext was expected
```
Before we passed `ThemedReactContext` directly to `UIManagerHelper.getEventDispatcherForReactTag` method. It actually works, because `ThemedReactContext extends ReactContext` and kotlin could cast types automatically.
But it looks like in RN 0.75 something has changed and CI jobs such as `gradlew lint` and `gradlew build` (which consumes latest artifacts from maven) started to fail. I've tried to cast it to `ReactContext` using `as ReactContext` construction (which is …

fix: RN 0.75 compilation error

---

.github/workflows/verify-android.yml

Rename "Run Gradle Lint" -> "Run Gradle Assemble" for Android Build job.
Looks like I copied/pasted "Gralde Lint" job and modified necessary lines in the code, but I forgot to rename one of the step 🙈 
In this PR I'm fixing this 😎 
- rename "Run Gradle Lint" -> "Run Gradle Assemble" for Android Build job
Tested on CI.

ci: rename "Run Gradle Lint" -> "Run Gradle Assemble" for Android Build job

---

e2e/kit/003-input-handlers.e2e.ts
ios/delegates/KCTextInputCompositeDelegate.swift
ios/observers/FocusedInputObserver.swift

Update selection when focused has changed on iOS.
That problem was present since the first version when the `onSelectionChange` handler was available (`1.12.0`). But I ignored it, since it wasn't so important 🙈 
In this PR I'm fixing the problem by manual event dispatching (when we add a delegate, i. e. focus was received). The problem is specific only for iOS (on Android it doesn't exist). But I had a plan to revisit Android implementation and make it more optimal, so keeping it in mind I decided to add e2e test to be sure such important functionality will not be broken in future releases.
Also in this PR I removed unnecessary class/structure instance creation and simplified code a little bit 👀 
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/482
- added …

fix: update selection on focus

---

src/components/KeyboardAwareScrollView/index.tsx

Fixed an issue where `scrollPosition.value` is updated with out-of-date value.
The problem happens, because without animation `onMove`/`onEnd` dispatched almost simultaneously. But js handler can not update `position.value` and in `onEnd` handler in `scrollPosition.value = position.value;` code we set `scrollPosition.value = 0`.
When text input grows:
```tsx
layout.value = input.value;
scrollPosition.value += maybeScroll(keyboardHeight.value, true);
```
We call `maybeScroll`, but `scrollPosition.value === 0` and because of that we scroll by 16px (though we had to scroll for `actualScroll (170) + 16` but we do `0 + 16`, and because of that position is incorrect.
To fix the problem `onEnd` should actually update `scrollPosition` to the expected value, and to achieve that we need to update a …

fix: race condition between js and worklet

---

ios/Extensions.swift
ios/delegates/KCTextInputCompositeDelegate.swift

Fixed incorrect selection coordinates when text gets moved to a new line and text input grows.
The problem happens because our text is bigger and can not fit into current layout. If we read coordinates we get `+Inf` and of course it's not reasonable to send such events to JS.
To fix this problem we need to wait for layout update (next frame) and send event only after that. This is exactly what i did in this PR:
```swift
if textView.canSelectionFitIntoLayout {
updateSelectionPosition(textInput: textView, sendEvent: onSelectionChange)
} else {
// when multiline input grows we need to wait for layout to be updated
// otherwise start/end positions will be incorrect (0/-1)
DispatchQueue.main.asyncAfter(deadline: .now() + UIUtils.nextFrame) {
updateSelectionPosition(textInput: textView, …
```

fix: incorrect selection coordinates when input grows

---

android/src/main/java/com/reactnativekeyboardcontroller/listeners/WindowDimensionListener.kt

Re-create `WindowDimensionListener` if context gets changed.
We need to memoize `WindowDimensionListener` and have a single listener across the app to avoid potential and unnecessary multiple events (many listeners will produce many events at the same time and it will just hit performance and will consume more memory, resources etc. so it's highly undesirable).
However, when you reload the RN app (double `R` press) -> you will re-create all internal variables and you will not attach a new listener. And the problem is in the fact that old listener will be destroyed (and even if not destroyed -> then it will not propagate events because the context was destroyed). And we'll always have `height=0`.
Of course such behavior is not correct and the proper solution would be to re-attach listener …

fix: memoize `WindowDimensionListener` on per context base (instead of global memoization)

---

src/components/KeyboardAwareScrollView/index.tsx

Added `height` to deps of `maybeScroll` function.
When we mount component and height is updated later (`windowDidResize` is emitted after component mount), then we receive `height=0` in `maybeScroll`. This PR fixes this.
Also I removed `height` from `useSmoothKeyboardHandler` because we don't use this value in the hook and we have `maybeScroll` in dependencies. 
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/499
- added `height` to deps of `maybeScroll` function.
Tested manually on Pixel 3A (API 33, emulator).
|Before|After|
|<img width="384" alt="Screenshot 2024-07-09 at 10 51 38" src="https://github.com/kirillzyusko/react-native-keyboard-controller/assets/22820318/d3d68393-b285-46bb-9900-0ae6b3b9475d">|<img width="379" alt="Screenshot …

fix: missing `height` deps in `KeyboardAwareScrollView` component

---

docs/docs/guides/compatibility.md
docs/versioned_docs/version-1.0.0/guides/compatibility.md
docs/versioned_docs/version-1.10.0/guides/compatibility.md
docs/versioned_docs/version-1.11.0/guides/compatibility.md
docs/versioned_docs/version-1.12.0/guides/compatibility.md
docs/versioned_docs/version-1.4.0/guides/compatibility.md
docs/versioned_docs/version-1.5.0/guides/compatibility.md
docs/versioned_docs/version-1.6.0/guides/compatibility.md
docs/versioned_docs/version-1.7.0/guides/compatibility.md
docs/versioned_docs/version-1.8.0/guides/compatibility.md
docs/versioned_docs/version-1.9.0/guides/compatibility.md
package.json
src/components/KeyboardAwareScrollView/index.tsx

Use `useScrollViewOffset` hook to get a scrolled distance.
`useScrollViewOffset` hook doesn't substitute `onScroll` handlers with `dummyListener` and thus it allows you to define your custom `onScroll` handler (and at the same time it can be plain js handler or reanimated one).
The new approach gives us next advantages:
- `position.value` is still calculating on UI;
- you can pass both worklet/js-handler as `onScroll` and it will work out of the box without additional manipulations 😎
- we don't use `@ts-expect-error` and don't ship the code with potential errors;
- we can support reanimated up to `2.11.0` (the first release that added `useScrollViewOffset`).
The disadvantage is that we need to bump REA from `2.3.0` to `2.11.0` (I described that in documentation). Theoretically we can …

feat: allow js and reanimated scroll handlers for `KeyboardAwareScrollView`

---

cspell.json
ios/core/KeyboardAnimation.swift
ios/core/TimingAnimation.swift
ios/observers/KeyboardMovementObserver.swift

A follow up PR for https://github.com/kirillzyusko/react-native-keyboard-controller/pull/412 - follow keyboard frame-in-frame if keyboard animation is **not** spring animation.
On iOS keyboard animation can be not only spring animation. It can be also `CABasicAnimation` (when keyboard goes up after interactive dismissal, for example).
Before we were relying on `CADisplayLink` and coordinates pooling, but such approach doesn't give a good precision. Even after implementing custom `SpringAnimation` we still relied on this approach (we used this approach as a fallback if the animation is not `CASpringAnimation`).
In this PR I implemented custom `TimingAnimation` class and if the animation is `CABasicAnimation` then we also can assure frame precision. All these math calculations were based on …

feat: timing animation

---

.github/workflows/publish.yml

Fixing:
```bash
npm error code EUSAGE
npm error Provenance generation in GitHub Actions requires "write" access to the "id-token" permission
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-07-24T10_31_43_348Z-debug-0.log
```
According to documentation and tutorials these permissions are necessary: https://tsmx.net/npmjs-built-and-signed-on-github-actions/
- grant `contents` and `id-token` corresponding permission for publishing npm package;
Can be tested only after merge 🤷‍♂️

ci: missing permissions for publishing

---

.github/workflows/publish.yml

Allow manual run for publishing to npm action.
I wanted to have "verified" badge, but forgot to run proper permissions to the job. As a result the job failed and I can not publish a package with new permission (https://github.com/kirillzyusko/react-native-keyboard-controller/pull/520), because the job is heavily depends on the fact that **new** tag must be published. In oreder not to create a new tag I decided to allow manual run for the job (as a last resort) 🙃 
- allow manual runs for `publish.yml` job;
- rename `build` -> `publish` job;
Can be tested only after merge 🙈

ci: allow manual publishing

---

e2e/kit/helpers/actions/index.ts
e2e/package.json
e2e/yarn.lock

Updated detox.
Mainly because I want to test iOS 18 compatibility + keed deps up-to-date.
- update detox;
- remove unnecessary `@ts-expect-ignore` errors;
Tested on CI.

e2e: update detox

---

src/components/KeyboardAwareScrollView/index.tsx

Fixed `ref` deallocation when you assign ref to `FlatList` and render `KeyboardAwareScrollView` via `renderScrollComponent` prop.
It looks like if we use `rest.snapToOffset`, then REA will try to copy all variables from `rest` properties to worklet runtime and then may fail to cleanup something.
Obviously we don't need to copy an entire object, because we only want to know one property, so in this PR I changed the approach and now we memoize only `snapToOffset` property (not entire `rest` object).
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/525
- capture only one variable (`snapToOffset`) instead of entire `rest` object into worklet closure;
tested on Pixel 2 (API 30).
https://github.com/user-attachments/assets/77e427b4-02ca-4775-81db-78450ae790aa

fix: ref deallocation with `FlatList` -> `KeyboardAwareScrollView` usage

---

FabricExample/src/screens/Examples/InteractiveKeyboard/index.tsx
android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardGestureAreaViewManager.kt
android/src/main/java/com/reactnativekeyboardcontroller/interactive/interpolators/Interpolator.kt
android/src/main/java/com/reactnativekeyboardcontroller/interactive/interpolators/IosInterpolator.kt
android/src/main/java/com/reactnativekeyboardcontroller/interactive/interpolators/LinearInterpolator.kt
android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardGestureAreaViewManagerImpl.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/KeyboardGestureAreaReactViewGroup.kt
android/src/paper/java/com/reactnativekeyboardcontroller/KeyboardGestureAreaViewManager.kt
docs/docs/api/keyboard-gesture-area.md
example/src/screens/Examples/InteractiveKeyboard/index.tsx
src/specs/KeyboardGestureAreaNativeComponent.ts
src/types.ts

Added `offset` property for `KeyboardGestureArea` component.
Add requested changes in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/250 only on Android (for now). Later on I'll try to add similar functionality to iOS.
On Android such functionality can be easily implemented, because we have a full control over the keyboard position - so we just need to take an additional variable in math calculations and that's all 😎 
I am still not sure if adding negative number to the linear interpolator should change the behavior of linear interpolator - it's open question and I can fix it later on. Right now I'm happy to have such changes, because it definitely improves UX so :shipit: 
- added info about `offset` property;
- update `KeyboardGestureArea` spec;
- update …

feat: new `offset` prop for `KeyboardGestureArea` on Android

---

src/components/KeyboardToolbar/index.tsx

Corrected wording for `accessibilityHint`. Move from "future simple" to "present simple" tense.
I missed "the" article and decided to add it. But then I asked ChatGPT what else can be improved and ChatGPT suggested to write everything in present simple tense. I kind of agree, because we describe what button does, not what it will do.
- changed `accessibilityHint`;
Tested on iPhone 15 Pro and e2e tests.

fix: `KeyboardToolbar` a11y wording

---

ios/extensions/UIView.swift
ios/observers/KeyboardMovementObserver.swift
src/components/KeyboardAvoidingView/hooks.ts

Fixed a case when `KeyboardAvoidingView` is not getting resized back when keyboard is hidden instantly.
The condition:
```tsx
if (e.duration === 0) {
progress.value = e.progress;
height.value = e.height;
}
```
prevented view to restore its initial position when keyboard is hidden instantly. When such thing happens we have next events:
```bash
LOG  onStart {"duration": 250, "eventName": "onKeyboardMoveStart", "height": 0, "progress": 0, "target": 7054} 1723043957135
LOG  onEnd {"duration": 250, "eventName": "onKeyboardMoveEnd", "height": 0, "progress": 0, "target": -1} 1723043957142
```
So technically we had to set our `height`/`progress` to `0`. But we skip it, because `event` actually has non-zero duration (it's 250ms).
We can't simply remove the code that I added before because it'll …

fix: instant keyboard hide causes `KeyboardAvoidingView` keeping bottom space

---

.prettierignore
docs/docs/guides/compatibility.md
package.json
src/animated.tsx
src/context.ts
src/event-handler.js
src/event-handler.ts
src/event-mappings.ts
src/hooks/index.ts
src/hooks/useSyncEffect/__tests__/index.spec.ts
src/hooks/useSyncEffect/index.ts
src/internal.ts
src/reanimated.native.ts
src/reanimated.ts
src/types.ts
src/utils.ts
yarn.lock

Mount workletized handlers synchronously 😎 
Previously we were storing all worklet handlers in a global object and broadcasted events through all of them. However such approach had one big downside: updating shared value from JS is asynchronous (and if JS thread becomes busy, then mounting can take significant time).
In most of the cases it's not a big problem, **but** if keyboard moves when handler is not attached yet, then such keyboard movement is not getting tracked and as a result an actual keyboard position is not synchronized with shared values (if we are using components, such as `KeyboardAvoidingView` then they will not handle keyboard appearance properly).
I've considered two approaches how to fix it:
That was the first idea and I thought it's quite perspective, but when I …

feat: synchronous handler mount

---

src/event-handler.web.js

Fixed web compilation.
Since I added new `event-handler` file - on web it'll try to import that, but it'll lead to errors, because this file depends on native module which is available on Android and iOS.
To fix that I'm exporting a mock function to make sure this library is still compilable on web.
- added `event-handler.web.js` file.
Tested manually on web project - the compilation error has gone.

fix: web compilation

---

package.json

Minimal supported version of `react-native-reanimated` is `3.0.0`.
These changes were introduced in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/538
In this PR I'm just changing version in `package.josn`.
Follow up for https://github.com/kirillzyusko/react-native-keyboard-controller/pull/538
- bump `react-native-reanimated` to `3.0.0`;
There is no way to test it 😀

chore: bump minimal `react-native-reanimated` version in `package.json` peer dependencies

---

docs/src/css/custom.css

Added `word-break` rule for menu items.
`useReanimatedKeyboardAnimation` is a long name and can't fit into one line. As a result part of the name was truncated and it's not good. So in this PR I'm fixing this.
Originally I wanted to increase sidebar width, but then realized that I need to handle cases for small devices (smartphones) and bigger sidebar doesn't look well there.
- added `word-break` to `menu__link` class;
Tested manually on `localhost:3000`.

docs: hook names truncated in menu bar

---

e2e/.detoxrc.js

Fixed flaky iOS 18 tests.
Problem because of the fact, that on GitHub we may be running on different runners and these runners have different XCode beta versions (16.0 and 16.1 with iOS 18.0 and iOS 18.1).
If we lock OS to iOS 18.1 then test can crash immediately if simulator is not found. So in this PR I temporarily unlock OS version until stable XCode will be rolled out to all runners.
- don't lock OS version for iOS 18;
Tested on CI (with XCode 16.1).

fix: e2e iOS 18 tests

---

ios/observers/KeyboardMovementObserver.swift

Fixed a case when `onEnd`/`keyboardDidShow` reports incorrect (previous frame) keyboard height.
Fixes regressions introduced in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/539
Initially I thought it's safe to read current keyboard frame in `didAppear` lifecycle (I thought it'll be always dispatched after animation finish, so why not to read it). But it was a fatal mistake because:
- when keyboard changes its size it changes it immediately and in `didAppear` we'll read old (previous) value ⛔ 
- on iOS 15 when modal gets hidden, then keyboard appears instantly and iOS 15 dispatches only one event, so we'll read old frame (i. e. `0`); 🔴 
- when iOS 17 with `secureTextEntry` randomly attaches/detaches `inputAccessoryView`, then we may also encounter a situation, when …

fix: properly report height for `didShow` event happening during animation

---

ios/views/KeyboardControllerView.mm

We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)
or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)
---
PR adding `load` method needed …

feat: add load method

---

android/src/main/java/com/reactnativekeyboardcontroller/extensions/EditText.kt
ios/extensions/UIResponder.swift

Ignore disabled (explicitly non-scrollable) `ScrollView`s for `parentScrollViewTarget` property.
If people disabled `ScrollView` (via `scrollEnabled=false`) then we shouldn't consider this `ScrollView` as parent and should continue a search.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/565
- added `isScrollEnabled` check;
- change casting from `ScrollView` to `ReactScrollView` and verify that `scrollEnabled` equals `true`;
Tested manually on paper architecture (both iOS and Android).

fix: ignore non scrollable ScrollView's for `parentScrollViewTarget`

---

e2e/kit/010-bottom-tab-bar-rotation.e2e.ts

Added `waitFor` to exclude case when we start execution of the test without opening a screen:
To keep e2e more stable. Flakiness can break tests in pretty near future.
- added `await waitForElementById("keyboard_animation_text_input");` check.
Tested on CI.

e2e: better stability of `BottomTabBarRotation` test

---

src/internal.ts

Defer attaching workelt handlers if ref is not initialized yet.
When we use `KeyboardAwareScrollView` next to `KeyboardProvider` we end up in situation when ref is not initialized yet and in this case we can not attach our handler.
This is a common scenario because documentation page tells is's a valid code but developers can be confused by that fact that sample code is not working and may not want to integrate the library in the code.
To fix this problem I'm deferring attaching till `ref` is initialized (`setImmediate` does the job).
Also I added meaningful warning that will spot potential problems in future:
<p align="center">
</p>
With all these changes I think a new code gets a better revision and handles more edge-cases.
Closes …

fix: mount handlers when view is not mounted yet

---

android/src/main/java/com/reactnativekeyboardcontroller/extensions/EditText.kt
android/src/main/java/com/reactnativekeyboardcontroller/extensions/ThemedReactContext.kt
android/src/main/java/com/reactnativekeyboardcontroller/extensions/View.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/log/Logger.kt
android/src/main/java/com/reactnativekeyboardcontroller/modal/ModalAttachedWatcher.kt
android/src/main/java/com/reactnativekeyboardcontroller/modules/StatusBarManagerCompatModuleImpl.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt

Use own `Logger` class in Android.
Using own logger instance has many advantages:
- we can implement internal implementation (like turn on/turn off logger depending on certain conditions);
- we can change internals and forward logs to react-native js side if needed;
- since it's our implementation we can change internals as we want and don't change the functionality in every piece of the code;
- we can apply various optimization technique later on (such as inline functions etc.).
So in this PR I'm introducing own `Logger` class and use it everywhere in the code. The main advantage of this class is that it's active only in debug mode and in release mode it will not send any logs (thus it'll slightly improve performance) and will not reveal details about the libraries that are used …

perf: use custom logger class

---

android/src/main/java/com/reactnativekeyboardcontroller/modules/KeyboardControllerModuleImpl.kt

Fixed a problem of non-working `KeyboardToolbar` functionality inside of `Modal` on Android.
The problem comes from the fact, that `Modal` on Android lives in their own `window` hierarchy and as a result `activity?.currentFocus` is always `null` (`currentFocus` is `null`).
A similar fix was added to iOS in this [commit](https://github.com/kirillzyusko/react-native-keyboard-controller/pull/346/commits/22babd2cd0c63936c812d6e48db94b0235a9974b). On iOS the problem was in fact that we can not retrieve focused input if keyboard is dismissed (unlike Android, because on Android the view still in focus and carret is blinking after even keyboard dismissal). So on Android it was harder to notice that bug (especially when `Modal`s weren't officially supported).
So the fix with replacing …

fix: `KeyboardToolbar` in `Modal` on Android

---

cspell.json
ios/.swiftlint.yml
ios/extensions/UIResponder.swift
package.json

Updated `swiftlint` to latest version.
Updated `swiftlint` to latest version.
Unfortunately I got a conflict between `swiftformat` and `opening_brace` rule from `swiftlint`. So I disabled a specific rule-case `ignore_multiline_statement_conditions` because `swiftformat` handles that.
Additionally I realized that some lint-related configs are included in final npm-bundle, so I added them to ignore list.
- removed lint-related files from npm package;
- removed ridiculous lint disabling approach in `UIResponder.swift`;
Tested on CI.

chore: update swiftlint

---

src/views/OverKeyboardView/index.tsx

Fixed a problem when content of `ScrollView` becomes invisible when `OverKeyboardView` is used.
The problem happens because we stretch inner view to full screen size and if we mount it directly to the children, then it takes all the space and growing containers can not be stretched.
The ideal fix would be to get rid off these hacks with setting `width` + `height`, but I've tried to do that in the past and iOS layout is broken without this workaround. To fix the problem I added `position: "absolute"` - it'll not affect the layout of other elements, because it has a different positioning. For now it works, but in future it would be good place to re-visit and to re-work and come up with a better solution.
Code for reproduction can be found at …

fix: invisible `ScrollView` when `OverKeyboardView` is used

---

src/views/OverKeyboardView/index.tsx

Fixed integration of `GestureDetector` inside `OverKeyboardView`.
The problem came to the fact that `TouchableWithoutFeedback` kind of intercepted touches and `GestureDetector` didn't receive it. I added `TouchableWithoutFeedback` in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/589 - in that PR it was reasonable to keep it there as it prevented crashes when touch gets handled by `rootView`. However in most cases developers will wrap area in `OverKeyboardView` in `Touchable*` to handle closing of their views, so now for me it seems to be safe to remove it.
The second thing is that if we apply styles to stretch inner view in JS then `GestureDetector` becomes broken again. I added this fix as iOS only and back to the time I haven't discovered any issues on Android. …

fix: non working `GestureDetector` inside `OverKeyboardView`

---

docs/docs/api/components/keyboard-avoiding-view.mdx
docs/versioned_docs/version-1.10.0/api/components/keyboard-avoiding-view.mdx
docs/versioned_docs/version-1.11.0/api/components/keyboard-avoiding-view.mdx
docs/versioned_docs/version-1.12.0/api/components/keyboard-avoiding-view.mdx
docs/versioned_docs/version-1.13.0/api/components/keyboard-avoiding-view.mdx
docs/versioned_docs/version-1.7.0/api/components/keyboard-avoiding-view.mdx
docs/versioned_docs/version-1.8.0/api/components/keyboard-avoiding-view.mdx
docs/versioned_docs/version-1.9.0/api/components/keyboard-avoiding-view.mdx

Add info about view props inheritance for `KeyboardAvoidingView` component.
It may be useful for people to know that `KeyboardAvoidingView` accepts `ViewProps` (to add `testID` for example).
- add info about view props inheritance for `KeyboardAvoidingView` component.
Tested on localhost:3000

docs: add info about view props inheritance to `KeyboardAvoidingView` page

---

docs/docs/api/components/keyboard-toolbar/index.mdx
src/components/KeyboardToolbar/index.tsx

Minor tweaks to `KeyboardToolbar` view props inheritance coming from this PR https://github.com/kirillzyusko/react-native-keyboard-controller/pull/603
I wanted to unify documentation style.
On JS side we should do spreading first, because otherwise unspecified props can overwrite our props and it may lead to unpredictable behavior.
- spread `rest` before specifying other props (because in props declaration we omit props that we use);
- unify props inheritance style across documentation style.
Tested manually on localhost:3000.

fix: `KeyboardToolbar` view props inheritance

---

android/src/fabric/java/com/reactnativekeyboardcontroller/OverKeyboardViewManager.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardHostShadowNode.kt

Refactored `OverKeyboardView`. Changed managers interfaces, variable names.
Key points:
- use `displaySize` when we use `getDisplaySize` function;
- inherit from `ViewGroupManager` instead of `ReactViewManager` (same as we do in paper arch).
- `modalSize` -> `displaySize`;
- `ReactViewManager` -> `ViewGroupManager`.
Tested on Pixel 3A.

refactor: `OverKeyboardView` (variable names, manager interfaces)

---

src/views/OverKeyboardView/index.tsx

Fixed a problem when `OverKeyboardView` is not stretched to the full screen (it's a workaround while I'm working on a proper fix).
The problem comes form the fact, that an approach (setting up layout from `ShadowNode`) doesn't work on Fabric, because `ShadowNode`s lives in C++ code now.
It's a pretty big task to add C++ code, an actual fix, make file, set up everything etc., so to workaround this problem I simply add height/width style from JS. This approach doesn't break `GestureDetector` on Fabric (the fix and problem was described in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/602), so as a temporary workaround it can be used.
The downsides of this fix are:
- we rely on `_IS_FABRIC` variable injected by REA (this part is not documented anywhere in the code);
- …

fix: `OverKeyboardView` stretching on Android (fabric)

---

.github/workflows/ios-e2e-test.yml

Stabilized e2e tests on iOS 18.
Improved stability of e2e tests on CI (iOS 18) by increasing timeout and locking XCode version.
For me it looks like iOS 18 and detox still doesn't work well together, but we can't do anything here at the moment, so I'm just increasing timeout to increase a probability of passing e2e tests.
- increased timeout to 90 minutes;
- locked XCode to stable `16.0` version;
Tested on CI.

e2e: stabilise iOS 18 tests

---

ios/extensions/UIApplication.swift
ios/extensions/UIWindow.swift

This PR updates the top window retrieval method:
Old: `UIApplication.shared.windows.last` (deprecated in iOS 15+)
New: `UIWindowScene`-based approach
Differences:
- `UIApplication.shared.windows.last`:
- It accesses all windows associated with the application.
- The last window in this array isn't always the topmost or key window, especially in more complex app setups.
- This approach is deprecated as of iOS 15, though it still works in many cases.
- `UIWindowScene`:
- Iterates through all connected scenes to find the active foreground scene
- Ensures selection of the correct key window in multi-window environments (e.g., Split View in iPadOS)
- Provides more reliable behaviour in complex app configurations that utilize multiple `UIWindowScenes`
Closes #618
In our case, this change was …

fix: make `getTopWindow` more robust

---

android/src/main/java/com/reactnativekeyboardcontroller/modules/StatusBarManagerCompatModuleImpl.kt

I suggest keeping track of the last activity and if it changes we should update the controller with the current window
StatusBar is not responding when the activity changes - see [issue](https://github.com/Expensify/App/issues/48782#issue-2513801944).
The problem is located [here](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/bb5e9e1d1e00278ce800b9558b75e56ff799abda/android/src/main/java/com/reactnativekeyboardcontroller/modules/StatusBarManagerCompatModuleImpl.kt#L74) in `getController` method.
We check if the controller is not `null` but if the activity changes (is closed and reopened) the controller is initialized and points to a non-existent window (taken from the previous activity), so we won't update the controller.
Outdated controller can't control the …

fix: broken `StatusBar` when `Activity` changes

---

.github/workflows/ios-e2e-test.yml

Don't use `macos-12` in CI anymore.
Handling https://github.com/actions/runner-images/issues/10721 in advance
Key points:
- run all tests on `macos-14` runner;
- installation may fail or [hang](https://github.com/kirillzyusko/react-native-keyboard-controller/actions/runs/11271787357/job/31345659022) a process, so I added a retry;
- using cache seams unreasonable, because with and without cache installation takes [the same](https://github.com/kirillzyusko/react-native-keyboard-controller/actions/runs/11271787357/job/31345659344) amount of time;
- install additional runtime only if `runtime` value is provided (otherwise skip operation to execute tests faster).
- added new `Install additional iOS runtimes` step for iOS e2e tests;
Tested on CI.

fix: install additional iOS runtimes

---

src/components/KeyboardAvoidingView/hooks.ts

Make `KeyboardAvoidingView` resizable when keyboard moved in an interactive way.
Even though adding `onInteractive` doesn't fully solve the problem, it's still better to move layout even though scrolling speed will be 2x.
At least it'll give a feeling, that it works but not very properly rather than not working at all.
Later on I may revisit this problem and try to find a way how to resize it in a correct way 👀 
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/594
- added `onInteractive` handler to `KeyboardAvoidingView`;
Tested manually on iPhone 15 Pro.
|Before|After|
|<video src="https://github.com/user-attachments/assets/05c9c812-7e2c-4969-aee0-64edf49ae584">|<video src="https://github.com/user-attachments/assets/acbbf7c6-586d-40ff-910f-396 …

fix: interactive `KeyboardAvoidingView`

---

ios/extensions/UIApplication.swift
ios/extensions/UIView.swift

Replaced the usage of deprecated `keyWindow` with our `activeWindow` extension (which is not depecated).
We shouldn't rely on deprecated syntax.
In https://github.com/kirillzyusko/react-native-keyboard-controller/pull/621 we added `.activeWindow` extension which represents a better alternative to `.keyWindow`.
So I thought it would be better to not use deprecated syntax anymore and use new extension.
- replace `.keyWindow` with `.activeWindow`;
Tested manually on CI (e2e tests).
|Before|After|
|------|------|
|<img width="1709" alt="image" src="https://github.com/user-attachments/assets/5e7bfe97-ad64-4871-8d0e-3405034f1eb6">|<img width="1741" alt="image" src="https://github.com/user-attachments/assets/298c1e4e-d499-48a3-990d-2c1c0e21b699">|

fix: deprecated `keyWindow` usage

---

ios/views/OverKeyboardViewManager.mm

Fixed `OverKeyboardView` unmount if view is attached to `.lastWindow`.
The key problem here is the fact that we unmount a view in JS, but `visible` property remains `true`, as a result view keeps mounted.
It doesn't happen when keyboard is visible, because in this case keyboard window gets destroyed and view gets destroyed as well. But when we attache a view to `.lastWindow` then we catch a bug.
This bug doesn't happen in Android, because on Android we've implemented `onDetachedFromWindow` where we call `hide`. I thought it would be reasonable to implement the same approach, so I added `didMoveToSuperview` method where I'm checking that unmount happened (i. e. `superview` is `nil`) and if so then I call `hide`.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/ …

fix: unmount `OverKeyboardView` from native side

---

ios/extensions/UIView.swift
ios/extensions/UIWindow.swift

Attach `OverKeyboardView` to `keyboardWindow` only if keyboard is visible.
The problem was because of the fact, that when we open a `WebBrowser` then `UIRemoteKeyboardWindow` from browser gets registered. And the problem is that when we close browser the window is not getting deregistered and we are attaching a view to invisible `keyboardWindow`. And view is not visible.
To fix this problem initially I decided to check if the `keyboardView` instance is retrievable. And first testing showed that it fixes a problem. I. e. we:
- open browser;
- close browser;
- show `OverKeyboardView` (it works);
But if we add more scenarios, like opening a keyboard, closing keyboard, opening a browser, opening/closing keyboard, showing `OverKeyboardView` the check can be broken, because we have invalid …

fix: check keyboard presence for `OverKeyboardView`

---

android/src/main/java/com/reactnativekeyboardcontroller/events/FocusedInputLayoutChangedEvent.kt
android/src/main/java/com/reactnativekeyboardcontroller/events/FocusedInputSelectionChangedEvent.kt
android/src/main/java/com/reactnativekeyboardcontroller/events/FocusedInputTextChangedEvent.kt
android/src/main/java/com/reactnativekeyboardcontroller/events/KeyboardTransitionEvent.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardControllerViewManagerImpl.kt

Do not use magic values as event names.
The "magic value" is an anti-pattern. This PR fixes code duplication and creates reusable strings/enums.
I created corresponding `EVENT_NAME` constant for events that are associated with one event. Events that have may have different names but the same structure I created an enum and shortened alias.
This issue was spotted by @IvanIhnatsiukso let's make him happy 😊 
- create corresponding `EVENT_NAME` constant as companion object for certain events;
- re-use `EVENT_NAME` in `getName` method and in event mapping;
- create enum for events that may have multiple events;
- re-use enum values in the rest of the code.
Tested in CI.

refactor: do not use event names as magic values

---

ios/observers/FocusedInputObserver.swift

Fixes a problem when all events such as `onFocus`/`onBlur`/etc. will stop working after keyboard dismissal.
It looks like a delegate in original `TextInput` can be somehow substituted and we are loosing a pointer to original delegate. If on keyboard-hide event we'll substitute delegate with `nil` - we will make all events, such as `onFocus`, `onBlur` etc. not coming to JS.
So the most obvious decision is to check, if we actually have a delegate and do a substitution only in this case.
Of course a rhetorical question arises - if we had original delegate, then injected our delegate, then it was substituted with a new one -> turns out that our events will not come, right? Right. But:
- I don't know how it's possible - I checked RN sources and I don't see a way how delegate can be injected …

fix: do not substitute delegate back if it's `nil`

---

docs/docs/installation.mdx
docs/docs/troubleshooting.md
docs/versioned_docs/version-1.14.0/installation.mdx
docs/versioned_docs/version-1.14.0/troubleshooting.md

Added new `Troubleshooting` page.
The installation section seems to contain the information that may be not used directly on this page. So I decided to move the content of this page to separate page + add a new use-case with sentry@v5.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/641
- added dedicated `Troubleshooting` page;
- added a reference to `Troubleshooting` page on `Installation` page.
- added a new use-case with Sentry@v5.

docs: troubleshooting page

---

android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/RootViewCompat.kt

Added `RootViewCompat` interface to prevent build issues on RN < 0.72. 
Prior to RN 0.73 `RootView` marked `onChildStartedNativeGesture(ev: MotionEvent?)` as deprecated, but without default implementation, so if you use `RootView` you had to override two methods:
- `onChildStartedNativeGesture(ev: MotionEvent?)`
- `override fun onChildStartedNativeGesture(childView: View, ev: MotionEvent)`;
To fix this problem I decided to introduce common `RootViewCompat` interface that will have a stub for deprecated method.
The reason why I moved it to separate file was mostly following SOLID principles - potentially this interface can be re-used in other parts of application, and I can not implement method directly in `OverKeyboardRootViewGroup` because I'll exceed maximum methods amount (11+).
Closes …

fix: `OverKeyboardView` compatibility with RN 0.72

---

FabricExample/yarn.lock
example/android/app/src/main/res/values/styles.xml
example/yarn.lock
package.json
src/animated.tsx
yarn.lock

This PR brings `react-native-edge-to-edge` detection to `react-native-keyboard-controller`.
The future of Android is [edge-to-edge](https://developer.android.com/about/versions/15/behavior-changes-15#edge-to-edge), and to make the React Native developer experience seamless in this regard, the ecosystem needs to transition from “opaque system bars by default” to “edge-to-edge by default.”
To prevent library authors from implementing their own edge-to-edge solutions—which could interfere with other libraries—and because it’s not possible to reliably detect if edge-to-edge is already enabled on Android, we have collaborated with [Expo](https://expo.dev/) to create a library that handles this functionality and is detectable using a simple helper: …

Detect react-native-edge-to-edge and bypass statusBarTranslucent / navigationBarTranslucent

---

FabricExample/yarn.lock
example/yarn.lock
package.json
yarn.lock

This PR update react-native-is-edge-to-edge to 1.1.3.
There's an issue with module resolution when new architecture is enabled: platforms extensions (`index.android.js`) are not resolved for dependencies. I had to switch the package implementation to use `index.js` + `index.web.js` instead.
- Update react-native-is-edge-to-edge to 1.1.3
- Tested on old and new architecture

Update react-native-is-edge-to-edge to 1.1.3

---

src/components/KeyboardAvoidingView/hooks.ts

Fixed popping up warnings when re-render happens if `KeyboardAvoidingView` is used.
Reading `.value` during render is a bad approach because it violates rules of react, so we shouldn't use it anymore.
Fortunately we have only one place in the codebase - it's `KeyboardAvoidingView`. Technically I don't violate rules of 
Initially I had 3 approaches in my head:
The first approach I was thinking of was this:
```tsx
const {height, progress} = useMemo(() => ({
height: context.reanimated.height,
progress: context.reanimated.progress,
}), []);
const heightWhenOpened = useSharedValue(-height);
const height = useSharedValue(-height);
const progress = useSharedValue(progress);
const isClosed = useSharedValue(progress === 0);
```
However later on in react docs I found this:
So I thought that in …

fix: avoid shared value reads during render

---

FabricExample/yarn.lock
example/yarn.lock
package.json
yarn.lock

Bump `react-native-is-edge-to-edge` as it breaks web (webpack) compatibility.
There was a problem because `web` was resolving `index.mjs`, which had a reference ti TurboModule and crashed the app:
It was fixed in `1.1.6` - all extensions were removed and files were named correspondingly. So now all files can be properly resolved 😊 
- bump `react-native-is-edge-to-edge` to `1.1.6`;
Tested manually on webpack app.

fix: web compatibility

---

src/components/KeyboardAwareScrollView/index.tsx

Fixed input hiding when google password manager pops up.
The native code worked correctly, however when Google Password manager popup appears, then we have next events:
```bash
onStart -> 0
onMove -> 289.66
onMove -> 289.44
onEnd -> 0
```
So because of this fact we kept bottom area (fake view). When keyboard appear again, then we were animating this bottom view again from 0 to 290. But since in the beginning of the keyboard movement focused input was above the keyboard - we don't perform `scrollTo` operation. But when bottom padding collapses to `0` an then input moves behind the keyboard. And since we don't call `scrollTo` it keeps its present there.
To fix the problem and don't break the state machine we need to synchronize keyboardFrame (currentKeybaordFrame) in `onEnd` handler. Thus …

fix: google password manager breaks `KeyboardAwareScrollView`

---

example/ios/Podfile.lock
src/animated.tsx

Added check if we are on web platform to avoid warning in the console about using native driver since on web we haven't access to native driver.
In [Expensify](https://github.com/Expensify/App) we are trying to remove all console errors and warnings in that [issue](https://github.com/Expensify/App/issues/51099). This fix will  help to achieve the goal.
- do not use `useNativeDriver` on `web`;
Tested in Expensify project.

Omit useNativeDriver warning on web

---

.github/workflows/ios-e2e-test.yml
FabricExample/ios/Podfile.lock
FabricExample/package.json
FabricExample/src/screens/Examples/Toolbar/index.tsx
FabricExample/yarn.lock
example/ios/Podfile.lock
example/package.json
example/yarn.lock

Updated `react-native-haptic-feedback` to the latest version.
Stopped to use `xcode@14.x` on CI as it has been removed. 
Before `react-native-haptic-feedback` was removed from `FabricExample` because it wasn't compatible with latest RN versions. Later on all issues were fixed and latest `2.3.3` version is fully compatible with all RN versions.
So in this PR I started to use `react-native-haptic-feedback@2.3.3` in both projects.
Additionally I fixed failing CI (xcode 14 was removed from macos-14 runners).
Fixes: https://github.com/kirillzyusko/react-native-keyboard-controller/issues/678
- don't use xcode 14 on CI and install iOS 16.4 for e2e test;
- update `react-native-haptic-feedback` to `2.3.3`.
Tested on CI.

fix: `react-native-haptic-feedback` in fabric example app

---

ios/extensions/Notification.swift
ios/observers/KeyboardMovementObserver.swift

Moved notification data extraction to separate extension.
`keyboardMovementObserver` class is pretty big and I'd like to keep it smaller. So the first action is to extract all pure functions into own separate files with specific area of responsibility/functionality.
- create `Notification` extension;
- create `keyboardMetaData` function-extension.
Tested on CI.

refactor: move data extraction from notification to extensions layer

---

android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/JSPointerDispatcherCompat.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt

To add a compatibility layer for `JSPointerDispatcher`, ensure that the method functions correctly regardless of whether it is called with two or three parameters.
Related:
https://github.com/facebook/react-native/commit/1e53f88b72e24ae2654b31f5c8bfbf8a07d51e09#diff-e874545c1f508ac02d63d67356fe0519f6c0dd5f380afeb900cf1de4fce6835aL202-R203
With the change, the number of parameters has increased from two to three. Since React Native 0.71.14 only uses two parameters, this causes a build error on Android.
- add `JSPointerDispatcherCompat` class
- I've tried compiling from 0.71
- I've tried compiling from 0.76
- **I would like to test the compatibility layer to ensure it functions smoothly. Could you help me with a plan for testing this code?**

feat(android): add JSPointerDispatcherCompat for RN < 0.72

---

android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/JSPointerDispatcherCompat.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt

In https://github.com/kirillzyusko/react-native-keyboard-controller/pull/681 we started to use reflection for detection the amount of params. But reflection is a slow mechanism, so in this PR I'm optimizing lookup stage by calculating a correct method only one time.
Lookup can be up to 10-100 times slower comparing to the direct function call. If we call this method too frequently, we can encounter a bottleneck. To make this code faster I decided to cache the method (thus we do a lookup only one time).
This approach should almost neglect performance impact for a lookup stage. The call stage (method invocation) still will add an overhead, but it should have a small impact.
- cache method (make it lazy calculated);
- move constants to companion object.
Tested on CI.

perf: lookup method only once

---

FabricExample/src/components/KeyboardAnimation/index.tsx
FabricExample/src/screens/Examples/Close/index.tsx
example/src/components/KeyboardAnimation/index.tsx
example/src/screens/Examples/Close/index.tsx
src/bindings.native.ts
src/bindings.ts
src/components/KeyboardToolbar/index.tsx
src/types.ts

Allow to pass additional params to `KeyboardController.dismiss()` method unintentionally.
When we pass params unintentionally like `onPress={KeyboardController.dismiss}` then we will try to serialize big JS object to the native side, which eventually crash the application.
To avoid this I decided to wrap `dismiss` in additional function and always send empty params to a native function.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/684
- removed undocumented `addListener`/`removeListener` methods from `KeyboardController`;
- allow to pass any params to `dismiss`;
- removed unnecessary functions nesting in `KeyboardToolbar`;
Tested on CI.

fix: allow to pass additional params to `.dismiss()` unintentionally

---

.github/actions/retry-sudo-with-timeout/action.yml
.github/actions/retry-with-timeout/action.yml
.github/workflows/ios-e2e-test.yml

Fixed an issue when additional runtime installation can not be terminated after 10 minutes.
When using [nick-fields/retry](https://github.com/nick-fields/retry) and we interrupt sudo command then we are getting errors like this https://github.com/nick-fields/retry/issues/114 or https://github.com/nick-fields/retry/issues/124
To overcome this problem I decided to create own script for retrying a command. This PR delivers that. 
- replace `nick-fields/retry` with own action;
Reduced timeout to 2 minutes and verified that action was repeated 3 times with 1 minute delay between attempts.

ci: interrupt sudo command in runtime installation

---

android/react-native-helpers.gradle

I updated `resolveReactNativeDirectory` in  `android/react-native-helpers.gradle` to handle custom directory structures in a more generic way.
As in the previous version, I followed how [software-mansion resolved this problem](https://github.com/software-mansion/react-native-reanimated/blob/36c291a15880c78a94dd125c51484630546ceb7c/packages/react-native-reanimated/android/build.gradle#L73).
I am working on a monorepo that's follow this structure
```plaintext
apps
├── react-native-app
│   ├── node_modules
│   │   └── react-native-keyboard-controller
packages
node_modules
├── react-native
package.json
```
The previous monorepo workaround was limited to two hardcoded paths.
My monorepo is build with Turborepo. Referring to [their docs](https://turbo.build/repo/docs/crafting-your-repository/man …

fix: resolve react native dir in monorepo in android build

---

cspell.json
docs/docs/troubleshooting.md
docs/versioned_docs/version-1.14.0/troubleshooting.md

Added info about `MutexLockWithTimeout` exception and the way to resolve it.
This is the best thing I can do at the moment - just mention that the problem exist and recommend to enable feature flag.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/687 https://github.com/kirillzyusko/react-native-keyboard-controller/issues/683 https://github.com/kirillzyusko/react-native-keyboard-controller/issues/640
- added new section in troubleshoot page;

docs: add info about `MutexLockWithTimeout` exception

---

docs/docs/api/keyboard-controller.md
jest/index.js
src/module.ts
src/types.ts

Added `KeyboardController.isVisible()` method.
I decided to match `Keyboard` API from `react-native` more closely, and I thought that `isVisible()` method can be useful in many places.
So in this PR I'm adding `isVisible` method.
- added API spec for new method.
- added `isVisible` method to `KeyboardController` API.
Tested manually.

feat: new `KeyboardController.isVisible()` method

---

src/hooks/useWindowDimensions/index.android.ts

Fixed broken layout of `KeyboardAvoidingView` when `KeyboardAvoidingView` mounted on app start.
The problem was in fact, that event arrived after `useState` initalization, but before adding a new listener. So we had a missing event and as a result `screenHeight` was `0`.
To fix this I applied a very similar logic to what `useWindowDimensions` hook does from `react-native`. When `useEffect` callback gets executed we update state with `initialDimensions`. The value of `initialDimensions` will be always actual, because it's located outside of the hook.
- force update state inside `useEffect` with `initialDimensions`;
Tested manually on `Medium_Phone_API_35`.

fix: missing update in `useWindowDimensions`

---

FabricExample/src/screens/Examples/Close/index.tsx
android/src/main/java/com/reactnativekeyboardcontroller/modules/KeyboardControllerModuleImpl.kt
e2e/kit/005-keyboard-toolbar.e2e.ts
e2e/kit/helpers/awaitable/index.ts
example/src/screens/Examples/Close/index.tsx

Unfocus `TextInput` and trigger `onBlur` when `.dismiss` is called on Android.
It was an inconsistency if we compare it to iOS or to `Keyboard.dismiss()` implementation, so I decided to fix it. Before we just hide a keyboard, but we also need to unfocus the field.
I think about changing the signature of `dismiss` or adding a new method `.hide` that will allow to hide a keyboard and keep a focus on the field (however it's only plans at the moment).
I also fixed e2e tests - before `tap` on AutoFill could be triggered too early and because of that test could fail, so I added `waitForCompletion` utility function and now this test is much more stable.
- wrap `FocusedInputHolder.focus()` into `UiThreadUtil.runOnUiThread`;
- call `clearFocus` when we dismiss a keyboard.
- …

fix: `.dismiss()` should trigger a blur on Android

---

src/animated.tsx

Fixed broken `KeyboardStickyView` position if keyboard dismissing has been interrupted (by showing a native sheet, for example).
This problem was discovered in https://github.com/bluesky-social/social-app/pull/6739
However I discovered such issue even earlier in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/667 - there I found out that progress can be interrupted (keyboard can start its movement, but then will be interrupted and will be instantly hidden) and `onEnd` event will be triggered.
Back to the times I fixed a problem by calling `maybeScroll` in `onEnd` handler. in this PR I want to do a similar thing - the only difference is that I want to add `onEnd` event to mapping for Animated/Reanimated values (`useKeyboardAnimation`/`useReanimatedKeyboardAnimation` …

fix: incorrect `KeyboardStickyView` state when keyboard animation interrupted

---

.github/workflows/verify-android.yml
android/build.gradle
android/gradle.properties

These 3 checks may constantly fail due to various reasons - one of them is new releases from RN (0.77.0-rc.0 triggered failures last time). In this PR I'm locking the version for CI jobs for these checks.
I'm tired of random CI failures not related to actual changes that I made in PR. The solution with locking RN version on CI is the most obvious one.
I made my changes in a backward compatible way - unless you specify `reactNativeVersion` everything should work as before (and I highly doubt anyone is using such variable name - if needed I can rename it to `keyboardControllerRNVersion` but I don't think it's required).
- specify RN version in `verify-android` in env;
- use env RN version for build, lint and unit-tests jobs.
- added new `reactNativeVersion` gradle variable with default `+` …

fix: Android specific CI checks

---

src/components/KeyboardAvoidingView/index.tsx

`contentContainerStyle` can be used only when `behavior="position"`.
To eep people aware about that additionally I decided to specify conditional TS types. Now people will get a warning if they specify this property and don't specify behavior as `position`.
- add conditional types to `KeyboardAvoidingView`;
Tested in example project.

refactor: conditional types for `KeyboardAvoidingView`

---

docs/docs/api/components/keyboard-sticky-view/index.mdx
src/components/KeyboardStickyView/index.tsx
src/components/KeyboardToolbar/index.tsx

Added `enabled` property for `KeyboardStickyView` component. Also added this property to `KeyboardToolbar`.
On top of what I remember this is iOS itself moves `KeyboardToolbar` (i. e. it's not interactive keyboard dismissal). So to fix the problem I decided to add `enabled` property. Using this property you can assure that views on previous screens are not animating/don't require additional style/layout computation.
A similar approach was used by `KeyboardAvoidingView`/`KeyboardAwareScrollView` components.
> Even though if we fixed the problem of keeping `KeyboardToolbar` toughly bind to keyboard frame - on interactive gesture we would still see a `KeyboardToolbar` without a keyboard. So `enabled` property is the way to go at the moment.
Closes …

feat: `enabled` prop for `KeyboardStickyView`

---

android/src/main/java/com/reactnativekeyboardcontroller/modal/ModalAttachedWatcher.kt

Fixed a crash when `progress` value becomes `Infinity` and can not be serialized to JS.
It happens when we try to divide any double/float number (except `0`) by `0.0`. In our case we were trying to divide `height / persistentKeyboardHeight`. To shed more light on the issue I modified condition `it.isNan()` to `it.isNaN() || it.isInfinite()`, and we get:
```bash
LOG  {"duration": 160, "eventName": "onKeyboardMoveStart", "height": 0, "progress": 0, "target": -1}
LOG  {"duration": 160, "eventName": "onKeyboardMove", "height": 47.71428680419922, "progress": 0, "target": -1}
LOG  {"duration": 160, "eventName": "onKeyboardMove", "height": 47.71428680419922, "progress": 0, "target": -1}
LOG  {"duration": 160, "eventName": "onKeyboardMove", "height": 47.71428680419922, "progress": 0, "target": …
```

fix: crash when Modal gets shown on Android < 9

---

src/internal.ts

Fixes a crash when `setImmediate` is not defined.
It looks like on web `setImmediate` is polyfilled by `webpack`. However in certain cases we may try to use `setImmediate` but it may be not polyfilled yet.
To fix this problem I had two options:
It also fixes a problem, but:
- specifying `0` always feels like a hacky solution;
- it will schedule a macrotask, which eventually will add more delay than required.
I selected this approach because:
- it seems like both `queueMicrotasks` and `setImmediate` acts similarly in terms of task scheduling and adding it to a queue;
- the same solution was chosen by Reanimated team.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/712
- use `queueMicrotask` instead of `setImmediate`;
Tested on example when `setImmediate` was …

fix: replace `setImmediate` with `queueMicrotask`

---

docs/docs/api/keyboard-controller.md
jest/index.js
src/module.ts
src/types.ts

Added `KeyboardController.state()` method.
To achieve a parity with `Keyboard` API from `react-native` I decided to add `KeyboardController.state()` method. By design it should act as `Keyboard.metrics()` method. The reason why I choose `state` name instead of `metrics` is because our data structure returns more like state rather than a metrics - instead of `height` and layout information we also return additional data, such as `duration` of last animation, `timestamp` when last open happened, `target` of focused input and in future potentially `type`, `appearance` and maybe other properties.
- added `KeyboardController.state()` method;
- added a reference about `KeyboardController.state()` method;
Tested manually in example app.

feat: state

---

android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt

Add a numerical safety test to keyboard animation progress
It solves a random crash in production where progress is infinite
Fixes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/739 https://github.com/kirillzyusko/react-native-keyboard-controller/issues/737 https://github.com/kirillzyusko/react-native-keyboard-controller/issues/735
- added `isInfinite` check along with `isNaN`;
Releasing it to production via a patch package the error report disappeared

fix: handle progress being infinite

---

cspell.json
docs/__tests__/screenshot.spec.ts
docs/src/pages/index.tsx

Drakula also trusts us, so let's add it to the "Trusted by" section.
I got a consent to add this app to landing page from @hirbod 🙂 
- added Drakula app on landing page;
- wait for hydration before taking screenshots.
Tested on localhost:3000.

docs: add Drakula app to Trusted By section

---

src/animated.tsx

Execute monkey-patch applying earlier than `StatusBar` modifications.
It happens when `KeyboardProvider` had direct child as `StatusBar` - and such thing can happen in `expo-router`, for example: https://github.com/expo/expo/blob/5f40a80019bb6b892eda94dd244fdc0df8880ccb/packages/expo-router/src/ExpoRoot.tsx#L57
To prevent this problem I'm executing monkey patch applying in "layout effect" instead of plain "effect". This gives me a precious time and an ability to apply patch earlier and thus re-direct a call to my module.
And if we dig a little bit deeper. When `KeyboardProvider` gets mounted the `useLayoutEffect` will be fired after component mount. On contrast `StatusBar` will try to change its properties in `componentDidMount`. And technically `componentDidMount` will be executed first …

fix: apply monkey patch before `StatusBar` updates

---

e2e/kit/helpers/actions/index.ts
e2e/kit/helpers/env/devicePreferences.ts

Improve speed of `scrollUpUntilElementIsBarelyVisible` + reduce its flakiness.
Before execution of this method was ~14s. Now it's 7s.
Also a new version reduces flakiness.
The approach is quite simple - knowing keyboard height, device screen height and element position we can easily calculate the necessary distance for scroll to place element straight above the keyboard.
Using this approach we don't need to use infinite for-loop and we can scroll only one time 😎 
It's not possible to get keyboard height using Detox, so I calculated these values myself (we kind of making a process of adding a new device a little bit more complicated, but e2e tests become more reliable, so I think it's okay to have these changes).
- added `keyboardHeight` property to device preferences;
- use math …

e2e: faster selection test

---

docs/src/pages/index.tsx

Added "Follow" app to trusted by section.
More apps more trust 😊 
- added new app to trusted by section;
Tested locally and via preview.

docs: added Follow app to trusted by section

---

.github/workflows/verify-ios.yml

Fixed failing iOS unit tests.
Seems like moving to latest runner fixes the problem.
- change macos runner t 15 for iOS unit tests;
Tested in this PR.

fix: ios unit tests (CI)

---

ios/delegates/KCTextInputCompositeDelegate.swift
ios/observers/FocusedInputObserver.swift

Make `useFocusedInputHandler` compatible with iOS < 13.
The library was always compatible with really old iOS versions. However there was a one handler (`onSelectionChange`) which was a stub on iOS < 13.
In this PR I'm adding support for old iOS versions for this handler via `KVO` approach + dispatching events on text changes.
The new algorithm can be breaking into next steps:
- on saving a new reference to delegate we remove old KVO;
- on saving a new reference to delegate we add KVO for UITextField (iOS < 13 only);
- we dispatch selection event from KVO/change text events (to be fully backward comaptible with iOS 13+, because single KVO don't emit events for text changes - only selection);
- when text editing has been completed - we remove KVO.
One thing I potentially don't really like …

feat: iOS 12 compatibility

---

ios/observers/FocusedInputObserver.swift

Potential fix for `NSRangeException` in `FocusedInputObserver`.
We don't have a reproduction example, so this fix is kind of blind. To fix this problem I decided to use block-scoped KVO. It has several advantages:
- we always assure that we can remove only a valid listener (and will not try to remove unexisting listener);
- we don't ignore `swiftlint` rules;
- we reduce number of lines in the code;
- we simplify KVO management and don't introduce additional boolean fields for its management.
So I think these changes should fix a problem 🤞
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/767
- use scope-based KVO instead of old style with `observeValue` class member;
Tested on CI to confirm that functionality of the library is not broken.

fix: `NSRangeException` in `FocusedInputObserver`

---

android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardControllerViewManagerImpl.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
android/src/paper/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
docs/docs/api/keyboard-controller-view.md
docs/docs/api/keyboard-provider.md
src/animated.tsx
src/specs/KeyboardControllerViewNativeComponent.ts
src/types.ts

Currently, even when `react-native-edge-to-edge` is installed, RNKC is able to disable `edge-to-edge`. For example, if we set `enable={false}` on `KeyboardProvider`, `disable` will be called on `EdgeToEdgeReactViewGroup`, and `WindowCompat.setDecorFitsSystemWindows` too.
This change detect if `react-native-edge-to-edge` is installed. If it is, edge-to-edge is forced and cannot be disabled.
It fixes an issue that breaks edge-to-edge (not only when enabled with `react-native-edge-to-edge`, but in general).
Fixes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/592 (_Toggle enabled to false, observe that the NavigationBar reappears and lifts the content._)
- Fixes issue with edge-to-edge when `KeyboardProvider` is used with `enabled={false}`.
- Using the example app …

Add preserveEdgeToEdge prop

---

android/src/main/java/com/reactnativekeyboardcontroller/extensions/EditText.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/FocusedInputObserver.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt

Cast to base `EditText` class whenever it's possible.
If you deal with native SDKs (i. e. Stripe), then in such SDKs they may inherit their component from native `EditText` and simply expose them to JS layer. Casting to `ReactEditText` will eventually fail and part of this library will not be working (everything about tracking focused input).
So in this PR I decided to cast everything to `EditText`. Conditional casting will be only in two places `focus` method and in reflection in `addTextChangedListener`. But in the last method I still can get a crash: `Expected receiver of type com.facebook.react.views.textinput.ReactEditText, but got com.stripe.android.view.CardNumberEditText`, so to overcome this problem I decided to handle that exception and call original method.
Resolves android …

fix: do not overcast to `ReactEditText`

---

ios/KeyboardControllerNative/KeyboardControllerNative.xcodeproj/xcshareddata/xcbaselines/0873ED612BB6B7390004F3A4.xcbaseline/AE1417BE-2A84-4C63-BD95-0B7DE93E2975.plist
ios/KeyboardControllerNative/KeyboardControllerNative.xcodeproj/xcshareddata/xcbaselines/0873ED612BB6B7390004F3A4.xcbaseline/Info.plist
ios/animations/KeyboardAnimation.swift
ios/animations/SpringAnimation.swift
ios/animations/TimingAnimation.swift

Slightly optimized performance of `SpringAnimation` and `TimingAnimation`.
I didn't change any implementation details. Just re-factored the code and found places that can be optimized, for example:
- pre-compute re-usable variables;
- pre-compute conditions;
- avoid unnecessary types conversion
As a result it gave ~5% boost for `TimingAnimation` and about 10-20% (depend on metric) for `SpringAnimation`.
Pretty cool to have performance tests in the project to see which change gives you which boost.
> On CI turns out after runner re-deploy (in the past) it has a different CPU than my laptop, so it seems like it always create its own baseline (so there is no ability to run perf benchmarks there).
- convert `speed` to `Double` in `KeyboardAnimation` and avoid additional conversions in …

perf: optimize animations (~5-20% win)

---

ios/KeyboardControllerNative/KeyboardControllerNative.xcodeproj/xcshareddata/xcbaselines/0873ED612BB6B7390004F3A4.xcbaseline/AE1417BE-2A84-4C63-BD95-0B7DE93E2975.plist
ios/KeyboardControllerNative/KeyboardControllerNativeTests/TimingAnimationPerformanceTest.swift
ios/animations/TimingAnimation.swift

Optimized `TimingAnimation.timingAt` method by `10x`.
The key optimization here is that instead of `bisection` -> (`findTForX`/`bezierY`) pipeline we simply use `findTForY`/`bezierX`. Thus we get rid off outer loop and as a result performance got improved by 10x: from 2.57s to 0.26s!
> Technically performance was improved from _log(n) ^ log(n)_ to _log(n)_, but concrete benchmarks shows `x10` boost 🔥 
Other performance optimization was made for `valueAt` - I removed unneeded math operations + casting and it gave a little bit boost (like 5%).
To keep follow DRY principles I created common `findT` function. Initially I wanted to pass a closure (for `findTForX`/`findTForY`), but turned out it makes perf worse by ~30%:
```swift
private func findTForX(xTarget: CGFloat, epsilon: CGFloat = …
```

perf: improve `TimingAnimation` performance

---

ios/extensions/UIResponder.swift

Fixed a crash when you tap on search input inside a header (native stack).
When accessing `nativeId` property in classes where it's not available (for example `UISearchBarSearchContainerView`, but I assume other UIKit classes as well), we will get a crash:
> *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<_UISearchBarSearchContainerView 0x15ac1d880> valueForUndefinedKey:]: this class is not key value coding-compliant for the key nativeId.'***
To overcome this problem I added a check whether this property is defined, and if it is defined, only then we query an actual value.
Tested in `FabricExample` and it resolves a crash 🤞 
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/784
- check if view responds to `nativeId` selector …

fix: crash accessing `nativeId` when it's not available

---

ios/observers/KeyboardMovementObserver.swift

Fixed a crash in `KeyboardMovementObserver` due to incorrect KVO removal.
Similar to https://github.com/kirillzyusko/react-native-keyboard-controller/pull/768
Instead of using plain KVO we are using block-scoped KVO, mainly to prevent random crashes, when we try to remove a KVO from a view that doesn't have it.
I can not 100% gurantee, that crash will not happen again, because a crash was very random and we can not reproduce it ourself (we just see it in Sentry) - so basically I can not test it.
But I'm pretty confident, that a new approach will fix the issue, since we will not accidentally remove KVO where it doesn't exist (because of block-scoped approach) 🤞 
Also new approach reduces code duplication (such as `if keyPath == "center"`) and reduces a number of code lines 👀 
Fixes …

fix: crash in `KeyboardMovementObserver` due to incorrect KVO removal

---

.github/workflows/android-e2e-test.yml

Fixed Android e2e tests.
Fixes this problem https://github.com/ReactiveCircus/android-emulator-runner/issues/400
- bump `android-emulator-runner` action version;
Tested via CI.

ci: fix android e2e tests

---

FabricExample/ios/Podfile.lock
example/ios/Podfile.lock
package.json

chore: release 1.16.1

---

package.json

Exclude `tests` folder on `android` on `npm`.
The original size of this folder is about ~7kb and may be bigger in the future:
But in a reality those files are not used when devs add the package to their projects. So for sake of the optimization let's exclude those files from publishing to npm 🤞 
- exclude `android/src/test` path;
There is no way to test that everything will work, but `size-diff` shows that folder was excluded (because size has been decreased).

fix: exclude android unit tests from being published to npm

---

ios/observers/FocusedInputObserver.swift

Fixed a problem when input looses a focus, but `FocusedInputObserver` doesn't send `noFocusedInputEvent` to JS.
The problem was introduced in this PR https://github.com/kirillzyusko/react-native-keyboard-controller/pull/760 before we were relying on keyboard evens, but in #760 I re-worked the approach and started to use blur/focus events. However I couldn't use only input events, because on iOS 15 keyboard event (`keyboardWillShow`) was arriving earlier than focus event, and for us it's crucial to know the layout of focused input inside `onStart` (i. e. before keyboard movement starts).
I decided to keep backward compatibility and keep keyboard events in place. However it comes with own set of challenges. For example:
This check works well for Paper, but doesn't work for Fabric. And for …

fix: missing `unfocus` event on iOS Fabric

---

android/src/main/java/com/reactnativekeyboardcontroller/modal/ModalAttachedWatcher.kt

Changed `onEventDispatch` signature and made it universal for kotlin/java codebase (should be compatible with RN 0.77 and RN 0.78).
Resolves one compilation error mentioned in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/806
- change `onEventDispatch` signature;
Tested on CI 🤞

fix: universal kotlin/java `onEventDispatch` method signature

---

android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/RootViewCompat.kt

Fixed incompatible function signatures after migration some classes in RN 0.78 to kotlin variant.
It should be backward compatible changes, because I test them on RN 0.77 (and I believe native android build still uses RN 0.77). So we've covered 0.76-0.78 versions, and from what I remember there was no breaking changes between 0.72-0.76 in that class, so it should be fully backward compatible.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/806
- changed `MotionEvent?` to `MotionEvent` in `onChildStartedNativeGesture` method;
- changed `View` to `View` in `onChildStartedNativeGesture` method.
Tested with RN `0.78.0-rc5` version.
Only RNS fails a compilation.

fix: `RootView` compatibility with RN 0.78

---

.github/workflows/android-e2e-test.yml

For our E2E testing, we don’t need to generate a universal APK that includes all architectures. Since the tests are executed on an x86_64 emulator, there is no practical advantage in bundling support for other architectures like arm64-v8a or armeabi-v7a. Given that the testing environment is stable and unlikely to change in the foreseeable future, maintaining a universal APK only adds unnecessary complexity.
By limiting the build to x86_64 only, we achieve a significant reduction in build time since we no longer need to compile the app for multiple architectures. This optimization not only speeds up our CI.
Before: 6m 10s
After: 3m 28s
it speeds up the build for CI
tested on CI

feat: set only one active arch for CI android e2e build

---

android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
android/src/main/java/com/reactnativekeyboardcontroller/modal/ModalAttachedWatcher.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt

Get rid off undesired config memoization.
When `navigationBarTranslucent` prop is set we may already mount a view and keep default `navigationBarTranslucent` value in `KeyboardAnimationCallback`.
The new approach assures that we have a shared config + we update `hasTranslucentNavigationBar` property when props are updated.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/818
- don't use getter for `config`;
- update `hasTranslucentNavigationBar` when prop gets changed;
Tested in reproduction repository.

fix: remove undesired prop memoization

---

android/src/main/java/com/reactnativekeyboardcontroller/listeners/FocusedInputObserver.kt

Fixes a crash after entering date expiry in stripe input on Android.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/807 https://github.com/stripe/stripe-android/issues/10178
The detailed explanation of the problem can be found here: https://github.com/stripe/stripe-android/issues/10178#issuecomment-2667270028
We decided that both frameworks (stripe and keyboard-controller) should implement a fix, so I'm adding asynchronous removal in this PR. Screenshots proving that it works as expected:
- remove text watcher asynchronously (via `.post`) with capturing `TextWatcher` into a closure (to remove correct watcher);
Tested manually in example app (with added Stripe SDK).
https://github.com/user-attachments/assets/123b72c4-ad48-41ae-88ed-d94645bf2c7d

fix: stripe crash on Android

---

android/src/main/java/com/reactnativekeyboardcontroller/interactive/InteractiveKeyboardProvider.kt
android/src/main/java/com/reactnativekeyboardcontroller/interactive/KeyboardAnimationController.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt

Fixed incorrect `end` event after cancelling predictive back gesture.
The problem was in fact that when keyboard gets shown in `onEnd` callback we get keyboard height as `0`, because insets were not applied yet.
I had this problem two years ago (when I implemented interactive keyboard dismissal), but back to the times I solved it via adding `InteractiveProvider.isShown` and it was working well, because the only one class could control keyboard position and it was my class. However starting from Android 15 keyboard position can be controlled by OS itself, so the trick with `InteractiveProvider.isShown` is not working anymore.
After discovering various approaches how to handle it I found only two ways:
While it seems preferable option, I still don't understand how it can be utilized in that …

fix: predictive back gesture handler (correct end event)

---

.github/workflows/android-e2e-test.yml

Removed "Clean up disk" step.
The "Clean up disk" step takes up to 2.5-3 minutes to complete, but in reality this step is needed only for running e2e tests (because there we run emulator which quickly occupies a lot of storage space). For plain builds we don't use this step and most of the time they can be completed successfully, so I decided to try to remove it.
- remove "Clean up disk" step from android e2e build job;
Tested via CI.

ci: do not clear disk space for build

---

.github/workflows/build-android-fabric.yml
.github/workflows/build-android.yml
.github/workflows/build-ios-fabric.yml
.github/workflows/build-ios.yml
FabricExample/patches/react-native-reanimated+3.16.7.patch

Patch reanimated lib to avoid double events.
I get many requests, so while we are waiting for a new release let's temporary patch the underlying lib to show how to overcome with this problem.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/822 https://github.com/kirillzyusko/react-native-keyboard-controller/issues/753
- patched reanimated in fabric example app;
- build example apps if patches were changed
Tested locally.
https://github.com/user-attachments/assets/c7de4c02-e970-4e6c-a8da-7a13da11fdcf

fix: duplicated events on Fabric

---

android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardGestureAreaViewManager.kt
android/src/fabric/java/com/reactnativekeyboardcontroller/OverKeyboardViewManager.kt

Removed nullability of delegates.
It was auto generated code by Android studio when original classes (from react-native) had java classes.
Now they are defined in Kotlin and explicitly are marked as non-nullable, so it conflicts with the code.
So in this PR I remove "nullability" of delegates - it still will be compatible with older RN versions and new RN 0.78 will be supported too 🤞 
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/826
- removed nullability of delegates;
Tested in RN 0.78 branch.

fix: build errors for Fabric on RN 78

---

android/src/turbo/java/com/reactnativekeyboardcontroller/KeyboardControllerPackage.kt

remove unnecessary @Nullable Annotation in kotlin
```log
Error: Do not use @Nullable in Kotlin; the nullability is already implied by the Kotlin type NativeModule? ending with ? [KotlinNullnessAnnotation]
@Nullable
~~~~~~~~~
Explanation for issues of type "KotlinNullnessAnnotation":
In Kotlin, nullness is part of the type system; s: String is never null and
s: String? is sometimes null, whether or not you add in additional
annotations stating @NonNull or @Nullable. These are likely copy/paste
mistakes, and are misleading.
```
This problem will cause warning. Because warning as error, it will cause build failed
remove unnecessary @Nullable annotation KeyboardControllerPackage.getModule
This commit not include any code logic change, so this is unlikely to be a problem.

fix: `KotlinNullnessAnnotation` warning

---

FabricExample/package.json
FabricExample/src/screens/Examples/ReanimatedChatFlatList/index.tsx
FabricExample/yarn.lock
docs/docs/api/components/keyboard-avoiding-view.mdx
docs/versioned_docs/version-1.16.0/api/components/keyboard-avoiding-view.mdx
example/package.json
example/src/screens/Examples/ReanimatedChatFlatList/index.tsx
example/yarn.lock
src/components/KeyboardAvoidingView/hooks.ts
src/components/KeyboardAvoidingView/index.tsx

Added new `behavior="translate-with-padding"` for `KeyboardAvoidingView`.
The new mode ideally fits for chat-like applications and has very good performance.
The implementation was mostly inspired by [WindowInsetsAnimation](https://github.com/android/user-interface-samples/tree/main/WindowInsetsAnimation) sample app. However when I tried to replace `translateY` to `0` and apply `paddingBottom` which is equal to previous `translateY` I had flashes on Android (mostly because of nature of Android - transform properties (e.g., `translateY`) only trigger a **repaint** (no _reflow_) and are applied **immediately**. Changes to **layout** properties like **padding** force the Android rendering system to recalculate layout (**reflow**), which can take an extra frame to resolve). So instead of …

feat: new `behavior="translate-with-padding"` for `KeyboardAvoidingView`

---

src/architecture.ts
src/views/OverKeyboardView/index.tsx

Replace `global._IS_FABRIC` check with `global.nativeFabricUIManager` check.
`_IS_FABRIC` is injected by reanimated, and it seems like they may change the variable name and don't treat it as a breaking change.
To avoid further incompatibility I decided to re-work that piece and rely on presence of fabric manager provided by RN.
- rely on `global.nativeFabricUIManager` instead of `global._IS_FABRIC`;
Tested on iOS in paper/fabric example projects.

refactor: use `nativeFabricUIManager` instead of `IS_FABRIC` to detect new architecture in JS

---

src/components/KeyboardAvoidingView/hooks.ts

Fixed `KeyboardAvoidingView` not updating if the keyboard closes before binding event handlers.
There’s a short timing gap after `KeyboardAvoidingView` initializes and before it listens for keyboard changes. If the keyboard closes during this gap, it isn’t aware that the keyboard has already closed.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/836.
Related to:
$ https://github.com/Expensify/App/issues/56156
PROPOSAL: https://github.com/Expensify/App/issues/56156#issuecomment-2656597451
- set shared values in useLayoutEffect
Tested locally on OnePlus 8 Pro Android 13.
| Before | After |
| -- | -- |
| <video src="https://github.com/user-attachments/assets/9e476052-79cc-4c5d-a0de-33bafd04951a" alt="Before" /> | <video …

fix: set shared values in layout effects

---

android/src/main/java/com/reactnativekeyboardcontroller/listeners/WindowDimensionListener.kt

Exclude `StatusBar` height from `useWindowDimensions` if StatusBar is _**not translucent**_.
In https://github.com/kirillzyusko/react-native-keyboard-controller/pull/468 I added own implementation of `useWindowDimensions`
I mentioned this:
And as you can see returned values do not match values returned by `useSafeAreaInsets`. Turns out they should match each other to make components like `KeyboardAvoidingView` to work properly.
So in this PR I'm excluding the `marginTop` to match `useSafeAreaInsets` behavior.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/833
Reproduction code:
```tsx
import React from 'react';
import {
Button,
StyleSheet,
TextInput,
View,
} from 'react-native';
import { KeyboardAvoidingView, KeyboardProvider } from …
```

fix: exclude `StatusBar` height from `useWindowDimensions` if `StatusBar` is not translucent

---

src/module.ts

Allow to pass `onPress={KeyboardController.dismiss}`.
In https://github.com/kirillzyusko/react-native-keyboard-controller/pull/720 I added an ability to pass `keepFocus` param. To keep a backward compatibility I assigned an empty object by default:
```ts
const dismiss = async (
{ keepFocus }: DismissOptions = { keepFocus: false },
): Promise<void> => {
```
However if we pass touch event - we don't assign our default object. When we try to extract `keepFocus` we get `undefined` and further `undefined` can not be casted to boolean.
In this PR I re-work the approach by combining `?` and `??` operators and passing `false` as default value. In case if `options.keepFocus` is `undefined` I'll pass `false` value by default.
> [!NOTE]
> TS will still complain about incompatible signatures, but …

fix: crash when pass `dismiss` as event handler

---

FabricExample/src/screens/Examples/FocusedInputHandlers/index.tsx
android/src/main/java/com/reactnativekeyboardcontroller/extensions/EditText.kt
example/src/screens/Examples/FocusedInputHandlers/index.tsx

Fixed wrong selection coordinates in multiline input with `maxHeight` restriction.
To fix the issue where the cursor coordinates are incorrect when the EditText has a fixed height and the text content exceeds it, we need to adjust the vertical positioning calculation by considering the available space and the scroll position.
```kt
val availableVertical = editTextHeight - paddingVertical
```
Computes the space available for the text after accounting for padding
```kt
val verticalOffset = if (textHeight <= availableVertical) {
when (gravity) {
Gravity.CENTER_VERTICAL ->
(availableVertical - textHeight) / 2 + editText.paddingTop + lineHeightHalfHearted
Gravity.BOTTOM ->
editText.paddingTop + (availableVertical - textHeight) + lineHeightHalfHearted
else -> editText.paddingTop + …
```

fix: selection coordinates in container with static height

---

src/components/KeyboardToolbar/index.tsx

Don't show "Done" button, if text is empty.
If people want to hide "Done" button it may be intuitive guess that `doneText` should be empty text.
I don't want to introduce more props, because `KeyboardToolbar` already has a plenty of them, so let's make `doneText` behavior more predictable.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/847
- assign "Done" as default `doneText` instead of using `||` operator.
Tested on iPhone 15 Pro (iOS 17.5), fabric.

feat: ability to hide "Done" button in `KeyboardToolbar`

---

FabricExample/src/screens/Examples/Close/index.tsx
e2e/kit/012-close-keyboard.e2e.ts
example/src/screens/Examples/Close/index.tsx
src/module.ts

Specify `isClosed=true` by default.
By default when app starts the keyboard is closed. So `isClosed` should be `true` 🙂 
Code that I used for testing:
```tsx
import { StyleSheet, Alert, TextInput, TouchableOpacity, Text } from 'react-native';
import {
KeyboardAwareScrollView,
KeyboardController,
KeyboardProvider,
} from 'react-native-keyboard-controller';
export default function HomeScreen() {
return (
<KeyboardProvider>
<KeyboardAwareScrollView
bounces={false}
keyboardDismissMode="interactive"
keyboardShouldPersistTaps="handled"
style={styles.container}
>
<TextInput editable style={styles.input} />
<TouchableOpacity onPress={() => KeyboardController.dismiss().then(() => Alert.alert('Dismissed'))}>
<Text>Press me to dismiss</Text>
</TouchableOpacity>
</KeyboardAwareScrollView> …
```

fix: pending `dismiss` if keyboard wasn't shown in app yet

---

src/components/KeyboardToolbar/index.tsx

Apply arrow/done paddings on elements level, not entire container, so that conditional rendering will exclude potentially undesired paddings.
Potentially "padding by default" approach may be not desired when you want your custom element (content) to place that space.
So in this PR I re-worked an approach, and if done/arrows are hidden, then `content` will fill entire container.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/848
Successor of https://github.com/kirillzyusko/react-native-keyboard-controller/pull/851
- removed `paddingHorizontal` from main container;
- added container for arrows and apply padding there;
- apply padding (+8px) to Done button (to compensate removed padding from main container);
Tested manually on iPhone 15 Pro (iOS 17.5 Fabric). …

fix: allow keyboard toolbar take all available space

---

FabricExample/src/screens/Examples/Toolbar/index.tsx
docs/docs/api/components/keyboard-toolbar/index.mdx
docs/versioned_docs/version-1.16.0/api/components/keyboard-toolbar/index.mdx
example/src/screens/Examples/Toolbar/index.tsx
src/components/KeyboardToolbar/index.tsx

Handle safe-area paddings in `KeyboardToolbar` component (landscape mode).
I had a lot of ideas how to fix this problem. Some of them:
- pass `insets` as prop;
- automatically grab insets from `useSafeAreaInsets` hook;
- render view wrapper (users can add their own SafeAreaView implementation).
The **automatically grab insets from `useSafeAreaInsets` hook** idea has failed, because in my case `react-native-safe-area-context` was resolving to other packages (maybe it's the problem with package linking in example app). But this is still not a perfect approach, because I'll force users to install additional package.
The **render view wrapper (users can add their own SafeAreaView implementation)** was perspective, but it would be very complex for end users. Mostly because we have to provide …

feat: `insets` prop for `KeyboardToolbar`

---

FabricExample/src/screens/Examples/Toolbar/index.tsx
example/src/screens/Examples/Toolbar/index.tsx

I added it many times already, so let's include in example app.
Sometimes I have to test how `KeyboardToolbar` works in `Modal`, so I decided to include that example in test app so that I don't need to make these changes every time.
Reproduction for https://github.com/kirillzyusko/react-native-keyboard-controller/issues/867
- added KYC button in `KeyboardToolbar` screen;
Tested on Android (Medium Phone API 35) and iOS (iPhone 15 Pro, iOS 17.5) simulators.
|Android|iOS|
|--------|---|
|<img width="380" alt="image" src="https://github.com/user-attachments/assets/0e3207fa-4adc-4548-aea3-035da822d639" />|<image  width="380" src="https://github.com/user-attachments/assets/b5be7588-b1e8-4aa2-ba4d-509ba6186f52">|

example: toolbar in modal

---

docs/docs/installation.mdx
docs/versioned_docs/version-1.16.0/installation.mdx

Updated installation guide.
People sometimes complain about the problem when package is not linked, so I decided to improve docs to reduce similar issues in the future.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/786
- clearly mention expo setup (because expo uses its own installation command);
- mention a problem and solution of build caches;
- move expo note under expo installation tab.
Tested locally and via preview.

docs: updated Expo installation instruction

---

docs/versioned_docs/version-1.16.0/guides/first-animation.md

Fixing this error
```
Unused style detected: styles.boxeslint(react-native/no-unused-styles)
```
ESLint is yelling at me
Just copy/paste the code example on my codebase.

docs: remove useless box style from first animation

---

README.md

Replace installation instructions with a docs guide.
We still ahve to keep people aware, that reanimated is a mandatory dependency, that people need to wrap app in Provider, separate instructions for Expo, etc.
So let's use a single source of truth in documentation and just use link to docs in README.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/877
- use link to docs for installation step;
- removed "our" in documentation details;
- use "information" instead of "info";

docs: use documentation installation page in README

---

FabricExample/src/components/KeyboardAnimation/styles.ts
FabricExample/src/screens/Examples/KeyboardAnimation/styles.ts
docs/docs/guides/first-animation.md
example/src/components/KeyboardAnimation/styles.ts
example/src/screens/Examples/KeyboardAnimation/styles.ts

Follow-up for https://github.com/kirillzyusko/react-native-keyboard-controller/pull/875
We need to update `next` tag to make sure that changes will not be added to subsequent releases.
Also cleaned up example code.
Ideally we should have that eslint plugin installed and activated in the project, but maybe I'll handle it in separate PR.
- removed unused style in `next` version
- removed dead code from app;
Tested via CI.

chore: remove dead code

---

src/components/KeyboardAvoidingView/index.tsx

Fixed incorrect `KeyboardAvoidingView` layout when it's used together with input (`autoFocus`) in `native-stack`.
The problem happens because of this:
> The problem here is that onLayout get triggered two times (with 852 and 722 values). The correct value is 722 (because view doesn't occupy all screen, the header above takes ~80px).
> 
> The problem is that when onLayout with 722 gets triggered, then keyboard is already shown and we don't take this event into consideration, because that event may come from the fact, that layout of the view was changed because of KeyboardAvoidingView transformation
I added condition `initialFrame.value === null` in the beginning of implementation (we also discussed potential but in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/229/fi …

fix: `KeyboardAvoidingView` + `autoFocus` + `native-stack`

---

ios/KeyboardController-Bridging-Header.h
ios/objc/UITextView+DelegateManager.h
ios/objc/UITextView+DelegateManager.m
ios/observers/FocusedInputObserver.swift

Set delegate to all `UITextView`s.
We had a similar problem on Android: https://github.com/kirillzyusko/react-native-keyboard-controller/pull/776
Basically if we caste field to `RCTUITextView` then there is a chance, that we will not be able to cast it if it's a subclass of `UITextView` (i. e. other 3rd party libs).
So the correct solution is to cast current responder to its basic class. The reason why I added this code in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/426 was the fact that only `RCTUITextView` had own delegate setter. However since we operate on `ivar` level we can bypass any setter (not only for a specific class), so I decided to move that extensions to a basic class (UITextView). It'll fix two problems:
- potential incompatibility with other 4rd …

fix: set delegate to all `UITextView`

---

src/components/KeyboardStickyView/index.tsx

Fixed a problem when `KeyboardStickyView`/`KeyboardToolbar` changes other component behavior in unpredictable way.
The original problem comes from that issue: https://github.com/facebook/react-native/issues/49694
And it seems like it's affecting many open-source projects: `react-native-screens`, `react-native-reanimated`, and `react-native-keyboard-controller` as well because I'm heavily relying on reanimated usage.
This PR is rewriting `KeyboardStickyView` to plain `Animated.View`. At the moment it's possible to do that, but in future I'm planning to change interpolation when keyboard gets dismissed interactively.
Again it's not proper fix for a problem, but pipeline react-native fix -> react-native-reanimated fix -> verify fix in this library can take months I believe and will require …

feat: `KeyboardStickyView` using plain Animated

---

docs/docs/api/hooks/keyboard/use-keyboard-state.mdx
docs/docs/api/keyboard-controller.md
jest/index.js
src/hooks/useKeyboardState/index.ts
src/module.ts
src/types.ts

Revisited some concepts of `useKeyboardState`/`KeyboardController.state()` etc.
After preparing a new release I went through the changes and realized, that it would be better to take a step back and keep `isVisible`/`state` decoupled but `useKeyboardState` should return data to all variables (i. e. aggregate them).
- mention animated hooks alternatives;
- don't include `isVisible` in `.state` method
- update types declaration to show that state doesn't return `null` anymore;
Tested via CI.

fix: `useKeyboardState` tweaks

---

android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt

Wrapped touch events in `try`/`catch`.
The problem stems from the fact, that we are trying to cast `ViewRootImpl` to `ViewGroup` (viewrootimpl cannot be cast to android.view.viewgroup). Basically it happens when touch gets propagated until `RootView` and wasn't handled earlier. Such thing can happen when:
- view is not fully laid out but it already handles a touch;
- view is not stretched to full screen and you touch area that doesn't belong to `OverKeyboardView` (fixed in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/863)
I was aware about that issue (especially on Fabric) and decided not to fix it - the main motivation was to stretch view to full screen on Fabric. However now, when view gets stretched we still have a small race condition when users click fast (i. …

fix: `OverKeyboardView` crash

---

docs/docs/api/components/keyboard-aware-scroll-view.mdx
docs/versioned_docs/version-1.16.0/api/components/keyboard-aware-scroll-view.mdx
docs/versioned_docs/version-1.17.0/api/components/keyboard-aware-scroll-view.mdx

Updated documentation for `FlashList`.
Seems like in recent versions of `FlashList` ref-forwarding has changed, so now we need to wrap the callback in `forwardRef`. Funny thing - such wrapper doesn't work for `FlatList`. So I separated instructions 🤷‍♂️ 
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/888
- updated `FlashList` + `KeybaordAwareScrollView` integrations ection.
Tested in example app.

docs: `forwardRef` for `FlashList`+`renderScrollComponent`

---

cspell.json
ios/delegates/KCTextInputCompositeDelegate.swift
ios/observers/FocusedInputObserver.swift

Fixed an integration with Square SDK.
The current problem is that `SQIPTextFieldInputModifier` always redirects call to an injected (`KCCompositeDelegate`) delegate - and it causes infinite loop that eventually leads to a crash 🤷‍♂️ 
I've tried to find source code of `SQIPTextFieldInputModifier` but it's closed, and I can not read it.
So far I had two approaches to fix it:
While it solves the problem, it produces other problems - it looks like original delegate methods never gets called and in this case we break Square SDK, so it's not really an option.
While it breaks the principle that any focused input will intercept events it makes certain sense:
- seems like Square did such "protection" intentionally;
- Square handler keyboard appearance on their own and it's not possible to use …

fix: Square payment SDK integration

---

src/components/KeyboardAwareScrollView/index.tsx

- Completely remove the `Reanimated.View` from `KeyboardAwareScrollView` when it's not enabled
- There's an [open issue with react-native Fabric](https://github.com/facebook/react-native/issues/49694) that manifests as flickering and/or modal height issues when react-native-reanimated `useAnimatedStyle` values get out-of-sync with their underlying react native Fabric style values.
- Until the open issue is fixed, the simplest workaround for the issue seems to be removing instances of `useAnimatedStyle`
- This is the same underlying motivation as your recent PR: https://github.com/kirillzyusko/react-native-keyboard-controller/pull/898
- My app has an issue where utilizing `KeyboardAwareScrollView` and then navigating to a new screen causes flickering in the second screen (see repro video …

fix: disabling KeyboardAwareScrollView didn't prevent useAnimatedStyle flickering

---

src/components/KeyboardAwareScrollView/index.tsx
src/internal.ts
src/utils/findNodeHandle/index.native.ts
src/utils/findNodeHandle/index.ts

In the new version of `react-native-web` they added an error throw if you try to use findNodeHandle from `react-native` https://github.com/necolas/react-native-web/blob/922c134f2b7c428cc19daaeb3cac4b6a4c8ec6a3/packages/react-native-web/src/exports/findNodeHandle/index.js#L11. So I created a findNodeHandle utility that uses react-native's findNodeHandle for the native platform and returns Node or null for web.
This library should work well on all platforms
- added findNodeHandle util
tested in a web browser
Before:
https://github.com/user-attachments/assets/7056e962-3427-4127-86ad-c204d09df874
After: 
https://github.com/user-attachments/assets/a2593a86-38dd-4f8d-aa73-0be04f1b3227

fix: findNodeHandle on the web platform

---

android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt

Fixed wrong dimensions when phone gets rotated.
We need to update shadow node layout whenever screen dimensions changes, so in this PR I'm doing this. I use `onSizeChanged` method as a lifecycle method for updating layout. Technically I could use `onLayout`, but it's highly undesirable to block `onLayout` method, so it's better to do it in `onSizeChanged`.
Fixes Android issue described in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/915
- moved state wrapper to `hostView`;
- manage `ShadowNode` layout inside `hostView`.
Tested manually on Medium Phone API 35.
[okv-rotation.webm](https://github.com/user-attachments/assets/6b49d0b3-e266-47e7-89af-1a8a3b4de6ce)

fix: `OverKeyboardView` rotation (fabric)

---

cspell.json
docs/docs/troubleshooting.md
docs/versioned_docs/version-1.17.0/troubleshooting.md

Fixed CI after merging https://github.com/kirillzyusko/react-native-keyboard-controller/pull/933 https://github.com/kirillzyusko/react-native-keyboard-controller/pull/932
Probably a right decision would be to fix CI in corresponding PRs, but I felt like it can be a double work, so I merged them with failed CI and in this follow-up PR I'm fixing CI to make it green again.
- added spellcheck exception;
- fixed prettier.
Tested via CI on this PR.

fix: CI for docs

---

docs/docs/troubleshooting.md
docs/versioned_docs/version-1.17.0/troubleshooting.md

Updated tip for ninja setup.
I removed out-of-date `YOUR_NINJA_PATH` variable, because now the path is build automatically. The only thing to remember is to use proper ninja version.
So I updated tip to reflect these changes and also updated language of the code.
- use `kt` for `gradle` config;
- re-word tip to make sure people use correct path.

docs: update tip for ninja path

---

FabricExample/ios/Podfile.lock
example/ios/Podfile.lock
package.json

chore: release 1.17.2

---

src/hooks/useWindowDimensions/index.ts

Rely on screen dimensions instead of window dimensions.
Hook `useWindowDimensions` relies on `window` dimensions. Internally for `window` react-native uses `[RCTKeyWindowValuesProxy sharedInstance].windowSize` which may be not updated when screen gets rotated (in some cases), while `mainScreen.bounds.size` (that is used for `screen` dimensions) gets updated.
So it looks like it's better to rely on `screen` instead of `window` to handle screen rotation cases.
Last, but not least: react-native subscribes to rotation events, but doesn't call `beginGeneratingDeviceOrientationNotifications`. Without invoking this function `useWindowDimensions` will not receive updates when screen is getting rotated. At the moment it works, because other libs (`expo-screen-orientation`, `react-native-screens` …

fix: rely on screen dimensions instead of window dimensions

---

FabricExample/src/screens/Examples/AwareScrollViewStickyFooter/index.tsx
android/src/main/java/com/reactnativekeyboardcontroller/extensions/ThemedReactContext.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/KeyboardAnimationCallback.kt
example/src/screens/Examples/AwareScrollViewStickyFooter/index.tsx

Fixed a problem when `Pressable` doesn't trigger `onPress` callback if it's located in `KeyboardStickyView` (`KeyboardToolbar`).
The problem stems from the fact that C++ shadow nodes do not know about changes caused by `useKeyboardAnimation` hook (we drive animation by native driver, so C++ thinks that view hasn't changed its position).
I found out that `ScrollView` had the same problem: https://github.com/facebook/react-native/issues/36504#issuecomment-2898068182
Basically the fix is next:
- after finishing the animation we dispatch `onUserDrivenAnimationEnded`;
- in `useAnimatedProps`:
```ts
NativeAnimatedHelper.nativeEventEmitter.addListener(
'onUserDrivenAnimationEnded',
data => {
node.update();
},
);
```
Where:
```ts
new AnimatedProps(
props,
() => onUpdateRef.current?.(), …
```

fix: keep shadow nodes in sync

---

src/components/KeyboardAwareScrollView/index.tsx

React on `bottomOffset` changes reactively.
In current implementation we change callbacks and they will use an updated value in next calls, but the call to `maybeScroll` function is missing.
So in this PR I'm force-calling `maybeScroll` when `bottomOffset` gets changed, so in this way we always respect actual `bottomOffset` value 😊 
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/930 https://github.com/kirillzyusko/react-native-keyboard-controller/issues/743
- call `maybeScroll` when `bottomOffset` gets changed;
Tested manually in FabricExample app with next code modification:
```tsx
const [offset, setOffset] = useState(0);
// ...
<KeyboardAwareScrollView
bottomOffset={offset}
// ...
<TextInput
key={i}
contextMenuHidden={i === 4 && Platform.OS === "ios"} …
```

fix: support dynamic `bottomOffset` for `KeyboardAwareScrollView`

---

docs/docs/api/hooks/keyboard/use-keyboard-state.mdx
docs/versioned_docs/version-1.17.0/api/hooks/keyboard/use-keyboard-state.mdx

Improved SEO for `useKeyboardState` hook.
I found that people use this search:
And don't get results. In reality we have a hook that do that, jsut under a different name: `useKeyboardState`. In this PR I'm fixing it by adding more keywords to this page.
- added more `keywords` for `useKeyboardState` page;
There is no way to test it until google re-indexes the page.

docs: enhance `useKeyboardState` SEO

---

android/src/main/java/com/reactnativekeyboardcontroller/views/overlay/OverKeyboardViewGroup.kt

Fixed a crash when `TalkBack` is enabled on Android and you use `OverKeyboardView`.
The problem comes from the fact that the system tries to traverse the view hierarchy, but overlay views are not part of the main view hierarchy.
`OverKeyboardHostView` **pretends** that the views you pass to it are its own children. From the platform’s point of view those views **are not really descendants** of `OverKeyboardHostView` — they live in a completely different window created with `WindowManager.addView`.
When the Android accessibility framework walks the view-tree it calls `addChildrenForAccessibility()`, iterates over `getChildAt(i)` and finally calls:
```kt
offsetRectBetweenParentAndChild(parent, child);
```
That helper checks that child **is a true descendant** of parent, and if it isn’t it …

fix: `OverKeyboardView` crash with `a11y`

---

android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
android/src/main/java/com/reactnativekeyboardcontroller/extensions/ThemedReactContext.kt
android/src/main/java/com/reactnativekeyboardcontroller/listeners/WindowDimensionListener.kt
android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardControllerViewManagerImpl.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/EdgeToEdgeReactViewGroup.kt
android/src/paper/java/com/reactnativekeyboardcontroller/KeyboardControllerViewManager.kt
example/ios/Podfile.lock

This PR fixes 3 memory leaks:
- first is connected to `ModalAttachedWatcher` keeping itself as a listener in `EventDispatcher`, everytime the `EdgeToEdgeReactViewGroup` sets itself to `active`. I fixed it with calling `setActive(false)` in `onDropViewInstance` of its manager.
- second is connected to `EdgeToEdgeReactViewGroup` calling `setupWindowDimensionsListener` and not detaching it ever. It is a singleton listener, so I attach it once when the first `EdgeToEdgeReactViewGroup` instance is created in `createViewInstance` and remove it in `invalidate` of the whole managers module.
- ~~third is connected to `EdgeToEdgeReactViewGroup` also adding a listener on `rootView` each time when calling `setupWindowInsets` and never detaching it, so we detach it in `onDropViewInstance`.~~ <- will …

fix: 2 memory leaks

---

docs/docs/api/hooks/keyboard/use-keyboard-state.mdx
docs/versioned_docs/version-1.17.0/api/hooks/keyboard/use-keyboard-state.mdx

Improved `useKeyboardState` SEO search.
I looked at console search results and discovered that people are using `isOpen`/`isVisible` keywords. Since those words are used in the code samples they are not getting indexed, so in this PR I change that 🙂 
- added `isOpen`/`isVisible` keywords for `useKeyboardState` page;

docs: improve `useKeyboardState` SEO search

---

src/components/KeyboardToolbar/constants.ts
src/components/KeyboardToolbar/index.tsx

Adopt `KeyboardToolbar` UI for iOS 26.
⚠️ This is a temporary solution. ⚠️ 
Starting from iOS 26 we:
- have rounder corners for keyboard;
- proposed to use liquid glass effect.
An original implementation from Safari now uses rounded corners + glass effect. Also instead of "Done" button Apple shows ✔️ Overall current Safari implementation doesn't look so well (in my opinion).
If we have a look how `IQKeyboardManager` handles that... well, it's even worse:
<p align="center">
</p>
So I think the UI for this element is not finalized yet. 
Anyway current implementation in keyboard-controller doesn't look well at all, so in this PR I'm:
- rounding corners;
- adding horizontal margins (so toolbar doesn't take full width);
- moving toolbar a little bit up, so that it has a small spacing between …

fix: `KeyboardToolbar` on iOS 26

---

ios/observers/KeyboardMovementObserver.swift

Pause `DisplayLink` instead of re-creating it before any keyboard movement.
This is a known fact, that pausing `CADisplayLink` is faster operation rather than re-creating it and attaching to the thread. I decided to make some benchamrkes, and it seems like it takes `1ms` for `10` runs:
I tried to re-run test 40 times, and the function wasn't in a stack trace - that means that the time was so insignificant. I also measure function execution:
- pausing: 1.5-2e^-6
- re-creating: 7-10e-6
So roughly speaking this is 5x improvement, but we measure only creating instances of new object (most likely we don't track what happens underhood).
Anyway, this is an optimization and I don't think it introduces any breaking changes, so let's keep it.
- pause `DisplayLink` instead of re-creating it;
Tested …

perf: pause `CADisplayLink` instead of re-creation

---

android/src/base/java/com/reactnativekeyboardcontroller/KeyboardControllerPackage.kt
android/src/fabric/java/com/reactnativekeyboardcontroller/StatusBarManagerCompatModule.kt
android/src/main/java/com/reactnativekeyboardcontroller/modules/statusbar/StatusBarManagerCompatModuleImpl.kt
android/src/main/java/com/reactnativekeyboardcontroller/modules/statusbar/StatusBarModuleProxy.kt
android/src/paper/java/com/reactnativekeyboardcontroller/StatusBarManagerCompatModule.kt
android/src/turbo/java/com/reactnativekeyboardcontroller/KeyboardControllerPackage.kt

Use reflection for `StatusBarModule` usage.
It seems like in RN 0.80+ the `StatusBarModule` is `internal` now (kotlin). So we can't use ir directly anymore - moreover the usage of `internal` class will lead to compilation errors.
An ideal fix is to make it public again in react-native framework, but it'll take some time and some RN versions will still use `internal` modificator. So in order to assure better compatibility across different RN versions I decided to use reflection. We can not use the approach with Java's `protected` classes (where we create the same package name and export public wrapper), because kotlin has a stricter policy. So we have two options how to fix it:
- reflection
- copy-paste original code
We already use reflection in 2 places (though they will be removed in the …

fix: use reflection for original `StatusBar` implementation discovery

---

ios/views/KeyboardExtenderContainerView.swift
ios/views/KeyboardExtenderManager.mm

Fix UI for `KeyboardExtender` on iOS 26.
I've created a bug ticket `FB17922439`, but looking how liquid glass gets adopted at whole OS level for me it seems like Apple is not going to go back to old design guidelines and this rounded keyboard with divider above and inability to embed views into it is a new reality. At the moment `KeyboardExtender` looks very bad, so to make sure iOS 26 adaptation gets better on the launch I decided to match style of Settings/Safari and other apps 🤷‍♂️ 
To do that I created `KeyboardExtenderContainerView` that uses liquid glass concept on iOS 26+ and fallbacks to `UIInputView` + `.keyboard` style on earlier versions.
The `UIGlassEffect` is not available on old XCode versions, so I used `NSClassFromString` with runtime checks - this is not perfect solution …

fix: `KeyboardExtender` on iOS 26

---

FabricExample/src/App.tsx
README.md
android/src/fabric/java/com/reactnativekeyboardcontroller/KeyboardControllerModule.kt
android/src/main/java/com/reactnativekeyboardcontroller/modules/KeyboardControllerModuleImpl.kt
android/src/paper/java/com/reactnativekeyboardcontroller/KeyboardControllerModule.kt
docs/docs/api/keyboard-controller.md
example/src/App.tsx
ios/KeyboardControllerModule.mm
ios/extensions/UIResponder.swift
ios/observers/KeyboardMovementObserver.swift
jest/index.js
src/bindings.ts
src/module.ts
src/specs/NativeKeyboardController.ts
src/types/module.ts

Added new `KeyboardController.preload()` method.
Originally discovered in [this tweet](https://x.com/_jsmth/status/1943659768956023172) and later discovered in [StackOverflow](https://stackoverflow.com/questions/9108245/ios-how-can-i-preload-the-keyboard) and [GitHub lib](https://github.com/mbrandonw/UIResponder-KeyboardCache) it seems like this problem is actually present for long time in iOS ecosystem. To be honest I also noticed time-to-time that in some cases the TTI can be very big if you set focus for the first time since you opened a keyboard. I thought it could be a problem of `react-native` framework itself, but turns out it's the problem of iOS (not a particular framework).
So in this PR I decided to bring this native fix to `react-native-keyboard-controller` codebase and …

feat: preload

---

FabricExample/src/App.tsx
docs/docs/api/keyboard-controller.md
docs/docs/api/keyboard-provider.md
example/src/App.tsx
src/animated.tsx

Call `KeyboardController.preload()` when `KeyboardProvider` gets mounted.
It seems like additional setup will require hand engineering and some devs may forget to do that. Keeping in mind that preloading is a safe operation I decided to `preload` keyboard by default (with an ability to turn off such behavior).
I did various tests and couldn't spot any issues with different configurations. The performance impact is minimal, because we only perform a single function call and all warmup happens later on UI thread, so it shouldn't affect app performance.
- added documentation for new `preload` property;
- added `preload` property to `KeyboardProvider` (`true` by default);
Tested manually on fabric/paper. iOS 18/iOS 26.
Used this code to test edge case:
```tsx
export default function App() { …
```

feat: preload by default

---

ios/observers/FocusedInputObserver.swift

Currently in my library, I have a bug that if we have text input with autofocus, your library adds a delegate and it does it before my library, as I do it with decorator view, which is mounted on the screen by the next element. I think it is not so important for your library to put its delegate( in terms of as early as possible). So I added logic that does this on the next frame.
Advanced input mask issue: https://github.com/IvanIhnatsiuk/react-native-advanced-input-mask/issues/128
Allow other libraries to set their own delegates
- Wrapped substituteDelegate call with DispatchQueue.main.async
tested locally on iOS simulator
https://github.com/user-attachments/assets/bb9e4725-d7d4-4fcb-9e28-0d94282315c0

fix: delay delegate substitution

---

android/src/main/java/com/reactnativekeyboardcontroller/managers/KeyboardControllerViewManagerImpl.kt

Re-attach dimension listener after JS bundle reload.
When we reload the JS bundle we call `invalidate` method. In `invalidate` we detach our dimension listener (but we don't deallocate listener itself). When we create new `EdgeToEdge` view we check whether we have a listener - and actually we have it, because we didn't clear it inside `invalidate`, so we don't attach a new listener.
Because of this fact next time when we reload the bundle we will not get any window updates and `useWindowDimension` will report incorrect height (`850` vs expected `770`).
To fix the problem I simply clear the `listener` (`listener = null`) and it works 🎉 
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/1032
- cleanup `listener` in `invalidate` method.
Tested manually using …

fix: re-setup `WindowDimensionsListener`after JS bundle reload

---

android/src/main/java/com/reactnativekeyboardcontroller/views/background/KeyboardBackgroundViewGroup.kt

Don't use `BackgroundStyleApplicator` directly.
`BackgroundStyleApplicator` was added ~9 months ago and in older react-native versions this class doesn't exist. Taking this fact into consideration it seems like `BackgroundStyleApplicator` is an internal implementation, which can be removed in future versions and overall I don't think it's reliable to use internal things.
So in this PR I'm switching to `super.setBackgroundColor` - internally it uses `BackgroundStyleApplicator`, but this is a public API and it will work across all react-native versions 😎 
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/1038
- use `super.setBackgroundColor` instead of `BackgroundStyleApplicator`;
Tested via e2e tests.

fix: do not use `BackgroundStyleApplicator` directly

---

ios/protocols/TextInput.swift

Fix compilation error if minimal supported iOS < 12.
The `userInterfaceStyle` property was added in iOS 12. Before iOS 12 all user interfaces were only in light mode.
Since I started to use this property I need to wrap it in `#available` - otherwise projects targeting lower iOS versions will throw compilation errors.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/1042
- added `#available` before accessing `userInterfaceStyle` property;
Tested via patch in test project.

fix: `keyboardAppearanceValue` extension iOS < 12 compatibility

---

ios/observers/KeyboardMovementObserver.swift
ios/observers/KeyboardViewLocator.swift

Isolate keyboard view locating into separate class.
`KeyboardMovementObserver` almost reaches its cognitive complexity, so I decided to simplify that class a little bit and group a related logic for discovering keyboard into separate class.
- created `KeyboardViewLocator` class;
- use `KeyboardViewLocator` in `KeyboardMovementObserver`
Tested via e2e test.

refactor: isolate keyboard view locator

---

src/components/KeyboardAwareScrollView/index.tsx

Removed a redundant console.debug statement from the library that was unnecessarily polluting the logs. This is the only one in the code so I suppose it was a development log that has not been deleted.
No functional or behavioral changes were made to the codebase. This is purely a logging cleanup.
•	Removed noisy console.debug statement from the library.
The change was tested manually by running the application and confirming that:
•	The noisy debug message no longer appears in the console.
•	All existing functionality continues to work as expected.
•	No errors or regressions were introduced.
Unit tests were not affected as this change does not alter any logic or data flow.

fix: remove maybescroll console debug

---

ios/views/KeyboardControllerView.mm

We caught an iOS crash by the Sentry error monitoring, according to the stack trace, finally we found there is a bug in the `KeyboardControllerView` class, the stack trace is like the below screenshot.
This PR solved this crash with a very simple fix, seems that this bug is caused by a unconscious typo error...
- Changed the `KeyboardControllerView` class implementation to resolve this crash.
Actually this crash is occasional and at least I didn't manage to reproduce it locally, the current fix is totally from logic inference, however we have applied the fix in this PR in our prod app more than one month by patching the library file, and we didn't find any new relevant crash occurrences since the fix, so it proves to work on our end.

fix: iOS crash caused by the `KeyboardControllerView` class implementation

---

ios/views/KeyboardControllerView.mm

Fixed `clang` formatter after https://github.com/kirillzyusko/react-native-keyboard-controller/pull/1059 fix
I couldn't fix the issue directly in the fork, because the fix was made in `main` branch. Also didn't want to ask author again and again to fix it, so decided to merge PR with failure and then apply a post-fix.
- run `lint-clang` to fix all the issues;
Tested on CI.

fix: clang format

---

ios/observers/KeyboardMovementObserver.swift
ios/observers/KeyboardTrackingView.swift

Fixed interactive dismissal on iOS 26.
Fixed the issue with interactive keyboard dismissal on iOS 26. The problem is that we always subtracted `.offset` value, but it looks like KVO doesn't take into consideration `.inputAccessoryView` during interactive dismissal, so we don't need to subtract the value.
However if we simply move `- offset` to iOS < 18, then we'll get a bug, that if keyboard is fully open then it'll use `inputAccessoryView` height. So to fix that I added a condition, that if keyboard is fully open the we subtract, otherwise pass as is.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/973
- move `- KeyboardAreaExtender.shared.offset` to iOS 18 specific code.
- use `keyboardPosition - KeyboardAreaExtender.shared.offset` only if keyboard is …

fix: iOS 26 interactive dismissal

---

src/components/KeyboardAvoidingView/index.tsx

Fixes #1079 
Returns empty style for disabled KeyboardAvoidingView to turn off all behaviors
#1079 
-
-
-
-
-
-
Provided issue repo as well as in the example flatlist chat example of this repo

fix: fix disabling KeyboardAvoidingView

---

ios/KeyboardControllerModule.mm

Don't use `<FBReactNativeSpec/FBReactNativeSpec.h>` import anymore.
This import was added 3 years ago. I think back to times it was needed (I'm assuming that all specs could be generated in one file or that spec contained some declarations that were needed in other custom specs). However it seems like now it's unnecessary. Moreover in react-native 0.81 it will cause a compilation error (not sure why, maybe react-native doesn't expose this spec publicly anymore).
Anyway, this change seems to be compatible with react-native 0.78..0.81, so I think it's safe to merge it as is without additional conditional imports and other stuff.
Closes https://github.com/kirillzyusko/react-native-keyboard-controller/issues/1081
- removed `<FBReactNativeSpec/FBReactNativeSpec.h>` import;
Tested via compiling …

fix: avoid direct `FBReactNativeSpec` usage

---

android/src/main/jni/CMakeLists.txt

Added `target_compile_reactnative_options` for Android in `CMakeList.txt`.
As per [blogpost](https://reactnative.dev/blog/2025/08/12/react-native-0.81#rn_serializable_state-and-c-flags) we should add `target_compile_reactnative_options` to the lib in order to support RN 0.81.
We use custom C++ code (custom shadow nodes) and we don't rely on codegen, so we need to do it.
> We use custom shadow nodes since `1.17.0` to properly stretch `OverKeyboardView`.
The same fix was added to `react-native-safe-area-context` and `react-native-screens`.
- added `target_compile_reactnative_options(${LIB_TARGET_NAME} PRIVATE)` for RN 0.80+
Tested via this PR - it doesn't break old builds 🙂 Didn't test on RN 0.81 project yet because upgrade is blocked by Detox.

fix: add `target_compile_reactnative_options`

---

jest/index.js

This PR adds the missing `DefaultKeyboardToolbarTheme` export to the Jest mock file, which resolves test failures when components try to access theme properties during testing. The fix includes both light and dark theme configurations with proper color values for primary, disabled, background, and ripple properties.
Currently, when using this brilliant package in my work repo I used `react-native-keyboard-controller` in my tests, but encountered errors when trying to access `DefaultKeyboardToolbarTheme.dark` or `DefaultKeyboardToolbarTheme.light` properties. This happens because the Jest mock is missing the theme export, causing:
```
TypeError: Cannot read properties of undefined (reading 'dark')
```
This fix ensures that components can properly spread and customize the theme in their …

Add DefaultKeyboardToolbarTheme to Jest mock exports

---

android/src/main/java/com/reactnativekeyboardcontroller/extensions/View.kt
android/src/main/java/com/reactnativekeyboardcontroller/modules/statusbar/StatusBarManagerCompatModuleImpl.kt
android/src/main/java/com/reactnativekeyboardcontroller/views/KeyboardGestureAreaReactViewGroup.kt
android/src/paper/java/com/reactnativekeyboardcontroller/StatusBarManagerCompatModule.kt

Removed `@RequiresApi` annotations usage.
When I was getting compilation issues due to usage of API which is not available in older versions I was constantly using first option provided by Android Studio: to add `@RequiresApi` annotation.
However it has some downsides:
- if you mark one method with this annotation - all other methods must use the same annotation if they call this method;
- this method is kind of semantic, and if you somehow accidentally call this method on older devices it will lead to crash.
So to make code structure a little bit cleaner I decided to remove those annotations and switch to `if`-statements. Initially the idea was to fix https://github.com/kirillzyusko/react-native-keyboard-controller/issues/1104, but turned out that [ObsoleteSdkInt] checks also …

fix: don't use `@RequiresApi` with old SDK versions

---

FabricExample/babel.config.js
FabricExample/ios/KeyboardControllerFabricExample.xcodeproj/project.pbxproj
FabricExample/ios/Podfile.lock
FabricExample/package.json
FabricExample/yarn.lock

Update reanimated to v4 in fabric example app.
To test lib compatibility we need to assure that newest libs versions are supported. Since reanimated v4 is only fabric compatible I update it in fabric example only.
We don't have e2e tests for fabric project yet, but i tested manually and everything works well.
Verifies https://github.com/kirillzyusko/react-native-keyboard-controller/discussions/1094
- update reanimated to v4 in fabric example app.
Tested manually in example app.
https://github.com/user-attachments/assets/0c6b4d62-eda2-45db-983c-00a0b08bb8b1

chore: update `reanimated` to v4

---

FabricExample/package.json
FabricExample/src/screens/Examples/AwareScrollView/index.tsx
FabricExample/yarn.lock

Fixed a crash in `KeyboardAwareScrollView` example app after https://github.com/kirillzyusko/react-native-keyboard-controller/pull/1120
`@gorhom/bottom-sheet@4` is not compatible with reanimated v4. So in this PR I updated lib to v5 to fix an instant crash after opening a screen that uses `@gorhom/bottom-sheet` library.
- update `@gorhom/portal` lib to v5;
Tested manually in FabricExample in `KeyboardAwareScrollView` example screen (both iOS/Android).

chore: update `@gorhom/bottom-sheet` to v5

---

docs/docusaurus.config.js
docs/src/css/custom.css
docs/src/modules/page-transitions.ts

Added animated transitions to documentation.
Inspired by https://github.com/mrousavy/nitro/pull/901
I like animated transitions more than instant one (even on web), so in this PR I add them 👀 
- added scroll animation;
- added cross-page transition between pages (opacity)
Tested manually on `localhost:3000`
https://github.com/user-attachments/assets/6007441b-6f3a-4df2-a1e3-ebb9110655c8

docs: page transitions
